export const BUDGET_THRESHOLD = 75000

export const REQUEST_TYPES = ['Financial Request', 'General Request']

export const REQUESTS = [
    {
        requestId: 'AUD-REQ-2026-001',
        requestType: 'Financial Request',
        requestDate: '08-06-2026',
        purpose: 'HR audit software license renewal',
        requestedAmount: 48000,
        requestedBy: 'D. Joseph',
        department: 'HR Audit',
        status: 'Pending',
        description: 'Annual renewal of HR compliance tracking and document audit software used by HR Audit team.',
        exceedsBudget: false,
        items: '1 × AuditTrack HR license (12 months), 5 user seats',
        remarks: 'Required before Q2 employee file sampling begins.',
    },
    {
        requestId: 'AUD-REQ-2026-002',
        requestType: 'General Request',
        requestDate: '09-06-2026',
        purpose: 'Extended site visit hours — Canteen audit',
        requestedAmount: null,
        requestedBy: 'R. Mehta',
        department: 'Process Audit',
        status: 'Pending',
        description: 'Request to conduct Canteen process audit during operational hours (6:30 AM – 2:00 PM) for live workflow observation.',
        exceedsBudget: false,
        items: null,
        remarks: 'Needs Joint Director Audit approval for department coordination.',
        generalDetails: 'Proposed date: 16-06-2026 · Team: Process Audit Manager + Executive',
    },
    {
        requestId: 'AUD-REQ-2026-003',
        requestType: 'Financial Request',
        requestDate: '07-06-2026',
        purpose: 'Quality audit assessment data extraction tools',
        requestedAmount: 32000,
        requestedBy: 'V. Lakshmi',
        department: 'Quality Audit',
        status: 'Pending',
        description: 'Specialized tools for grade entry integrity checks and assessment rubric compliance analysis.',
        exceedsBudget: false,
        items: 'Data extraction utility license, 2 analyst workstations upgrade',
        remarks: 'Supports Academic quality audit scope AUD-2026-011.',
    },
    {
        requestId: 'AUD-REQ-2026-004',
        requestType: 'Financial Request',
        requestDate: '06-06-2026',
        purpose: 'External process audit consultant — Finance',
        requestedAmount: 95000,
        requestedBy: 'R. Mehta',
        department: 'Process Audit',
        status: 'Pending',
        description: 'Engage external consultant for specialized Finance process audit review beyond in-house capacity.',
        exceedsBudget: true,
        items: 'Consultant fees (10 days), travel, report submission',
        remarks: 'Amount exceeds audit team threshold — escalated to Joint Director Audit.',
    },
    {
        requestId: 'AUD-REQ-2026-005',
        requestType: 'General Request',
        requestDate: '05-06-2026',
        purpose: 'After-hours server access for IT process audit',
        requestedAmount: null,
        requestedBy: 'A. Khan',
        department: 'Process Audit',
        status: 'Approved',
        description: 'Scheduled after-hours access window to verify backup logs and network infrastructure for IT Support audit.',
        exceedsBudget: false,
        items: null,
        remarks: 'Approved for Saturday 14-06-2026, 8:00 PM – 11:00 PM.',
        generalDetails: 'Systems: ERP backup cluster, network switches · Escort: IT Support on-call',
    },
    {
        requestId: 'AUD-REQ-2026-006',
        requestType: 'Financial Request',
        requestDate: '04-06-2026',
        purpose: 'HR audit training — labor law updates',
        requestedAmount: 22000,
        requestedBy: 'S. Priya',
        department: 'HR Audit',
        status: 'Rejected',
        description: 'External workshop on updated labor law compliance for HR Audit team certification.',
        exceedsBudget: false,
        items: 'Workshop registration (2 attendees), study materials',
        remarks: 'Rejected — deferred to Q3 professional development budget.',
    },
    {
        requestId: 'AUD-REQ-2026-007',
        requestType: 'General Request',
        requestDate: '10-06-2026',
        purpose: 'Cross-audit team findings review meeting',
        requestedAmount: null,
        requestedBy: 'D. Joseph',
        department: 'HR Audit',
        status: 'Pending',
        description: 'Schedule joint review with all audit team leads to discuss open findings and compliance actions.',
        exceedsBudget: false,
        items: null,
        remarks: 'Proposed date: 18-06-2026, 11:00 AM — Audit Conference Room.',
        generalDetails: 'Attendees: HR Manager, Process Audit Manager, Quality Audit Principal · Duration: 2 hours',
    },
    {
        requestId: 'AUD-REQ-2026-008',
        requestType: 'Financial Request',
        requestDate: '03-06-2026',
        purpose: 'Audit field kit replenishment',
        requestedAmount: 18000,
        requestedBy: 'A. Khan',
        department: 'Process Audit',
        status: 'Approved',
        description: 'Replenish audit field kits — checklists, recording devices, and secure document pouches for site visits.',
        exceedsBudget: false,
        items: 'Field kits (5), secure pouches (10), digital recorders (2)',
        remarks: 'Approved for Q2 audit cycle site visits.',
    },
]

export const statusBadgeColor = {
    Pending: 'bg-[#FF980033] text-[#FF9800]',
    Approved: 'bg-[#4CAF5033] text-[#4CAF50]',
    Rejected: 'bg-[#FF000033] text-[#FF0000]',
}

export const requestTypeBadgeColor = {
    'Financial Request': 'bg-[#515DEF33] text-[#515DEF]',
    'General Request': 'bg-[#2196F333] text-[#2196F3]',
}

export const formatAmount = (amount) => (amount != null ? `₹${amount.toLocaleString('en-IN')}` : '—')
