const checklist = (doneUntil) => {
    const items = [
        'Offer Accepted', 'Appointment Letter Issued', 'Employee ID Created', 'Personal Details Completed',
        'Documents Collected', 'Department Assigned', 'Reporting Manager Assigned', 'HR Orientation',
        'Policy Acknowledgement', 'System Access', 'ID Card', 'Bank Details', 'Training Scheduled',
        'Shadow Mentor Assigned', 'Observation Scheduled', 'Onboarding Completed',
    ]
    return items.map((label, index) => ({
        label,
        status: index < doneUntil ? 'Completed' : index === doneUntil ? 'In Progress' : 'Not Started',
    }))
}

export const SEED = {
    employees: [
        { id: 'EMP-2026-001', name: 'Priya Sharma', gender: 'Female', dateOfBirth: '14-05-1988', contact: '+91 98765 43210', email: 'priya.sharma@school.com', address: '42, Green Park, Delhi — 110016', department: 'Academic', designation: 'Senior Teacher — Mathematics', joiningDate: '12-08-2019', status: 'Active', reportingManager: 'Dr. Meera Kapoor', role: 'Teacher', qualification: 'M.Sc. Mathematics, B.Ed.', experience: '8 years', emergencyContact: 'Rajesh Sharma (+91 98100 11223)', employmentType: 'Full Time', category: 'Academics', grossSalary: 65000, otherAllowance: 2000, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-002', name: 'Rahul Mehta', gender: 'Male', dateOfBirth: '02-11-1990', contact: '+91 98111 22001', email: 'rahul.mehta@school.com', address: '18, Lajpat Nagar, Delhi', department: 'Finance', designation: 'Accounts Executive', joiningDate: '05-03-2021', status: 'Active', reportingManager: 'Anita Desai', role: 'Accounts', qualification: 'B.Com', experience: '5 years', emergencyContact: 'Seema Mehta (+91 98111 22009)', employmentType: 'Full Time', category: 'Admin', grossSalary: 48000, otherAllowance: 1500, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-003', name: 'Anita Desai', gender: 'Female', dateOfBirth: '19-01-1986', contact: '+91 98200 33445', email: 'anita.desai@school.com', address: '9, Vasant Kunj, Delhi', department: 'HR', designation: 'HR Executive', joiningDate: '18-01-2022', status: 'Active', reportingManager: 'Director Academics', role: 'HR', qualification: 'MBA HR', experience: '7 years', emergencyContact: 'Kiran Desai (+91 98200 33440)', employmentType: 'Full Time', category: 'Admin', grossSalary: 52000, otherAllowance: 1000, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-004', name: 'Vikram Singh', gender: 'Male', dateOfBirth: '08-09-1984', contact: '+91 99000 11220', email: 'vikram.singh@school.com', address: 'Transport Colony, Delhi', department: 'Transport', designation: 'Fleet Supervisor', joiningDate: '22-11-2020', status: 'On Leave', reportingManager: 'Transport Manager', role: 'Supervisor', qualification: 'Diploma', experience: '10 years', emergencyContact: 'Sunita Singh (+91 99000 11221)', employmentType: 'Full Time', category: 'Admin', grossSalary: 38000, otherAllowance: 800, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-005', name: 'Neha Gupta', gender: 'Female', dateOfBirth: '21-04-1998', contact: '+91 97654 32100', email: 'neha.gupta@school.com', address: 'Dwarka Sector 12, Delhi', department: 'IT Support', designation: 'IT Support Engineer', joiningDate: '02-06-2026', status: 'Probation', reportingManager: 'IT Support Manager', role: 'Support', qualification: 'B.Tech IT', experience: '2 years', emergencyContact: 'Anil Gupta (+91 97654 32109)', employmentType: 'Full Time', category: 'Admin', grossSalary: 32000, otherAllowance: 500, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-006', name: 'Suresh Pillai', gender: 'Male', dateOfBirth: '30-07-1982', contact: '+91 94470 10020', email: 'suresh.pillai@school.com', address: 'Staff Quarters, Campus', department: 'Housekeeping', designation: 'Housekeeping Supervisor', joiningDate: '09-07-2018', status: 'Active', reportingManager: 'Admin Officer', role: 'Supervisor', qualification: 'Higher Secondary', experience: '12 years', emergencyContact: 'Latha Pillai (+91 94470 10021)', employmentType: 'Full Time', category: 'Housekeeping', grossSalary: 28000, otherAllowance: 400, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-007', name: 'Ramesh Yadav', gender: 'Male', dateOfBirth: '11-02-1987', contact: '+91 98180 44556', email: 'ramesh.yadav@school.com', address: 'Najafgarh, Delhi', department: 'Transport', designation: 'School Driver', joiningDate: '14-04-2019', status: 'Active', reportingManager: 'Vikram Singh', role: 'Driver', qualification: '10th, HMV Licence', experience: '9 years', emergencyContact: 'Geeta Yadav (+91 98180 44550)', employmentType: 'Full Time', category: 'Driver', grossSalary: 22000, otherAllowance: 300, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-008', name: 'Lakshmi Nair', gender: 'Female', dateOfBirth: '03-12-1992', contact: '+91 98460 77889', email: 'lakshmi.nair@school.com', address: 'Janakpuri, Delhi', department: 'Transport', designation: 'Bus Conductor', joiningDate: '01-06-2021', status: 'Active', reportingManager: 'Vikram Singh', role: 'Conductor', qualification: '12th', experience: '4 years', emergencyContact: 'Arun Nair (+91 98460 77880)', employmentType: 'Full Time', category: 'Conductor', grossSalary: 18000, otherAllowance: 200, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-009', name: 'Imran Khan', gender: 'Male', dateOfBirth: '16-08-1991', contact: '+91 98990 12121', email: 'imran.khan@school.com', address: 'Okhla, Delhi', department: 'Security', designation: 'Security Guard', joiningDate: '10-01-2020', status: 'Active', reportingManager: 'Security Supervisor', role: 'Security', qualification: '12th', experience: '6 years', emergencyContact: 'Ayesha Khan (+91 98990 12120)', employmentType: 'Full Time', category: 'Security', grossSalary: 20000, otherAllowance: 250, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-010', name: 'Meena Joshi', gender: 'Female', dateOfBirth: '25-03-1985', contact: '+91 97111 55667', email: 'meena.joshi@school.com', address: 'Hostel Block, Campus', department: 'Hostel', designation: 'Hostel Warden', joiningDate: '07-05-2017', status: 'Active', reportingManager: 'Principal', role: 'Warden', qualification: 'M.A.', experience: '11 years', emergencyContact: 'Ravi Joshi (+91 97111 55660)', employmentType: 'Full Time', category: 'Hostel', grossSalary: 36000, otherAllowance: 600, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-011', name: 'Arjun Patel', gender: 'Male', dateOfBirth: '09-09-1993', contact: '+91 98250 90909', email: 'arjun.patel@school.com', address: 'Saket, Delhi', department: 'Academic', designation: 'ECA Coach — Sports', joiningDate: '15-07-2023', status: 'Active', reportingManager: 'Dr. Meera Kapoor', role: 'Coach', qualification: 'B.P.Ed.', experience: '4 years', emergencyContact: 'Nita Patel (+91 98250 90900)', employmentType: 'Full Time', category: 'ECA', grossSalary: 35000, otherAllowance: 500, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-012', name: 'Kavita Rao', gender: 'Female', dateOfBirth: '12-06-1995', contact: '+91 98860 30303', email: 'kavita.rao@school.com', address: 'Rohini, Delhi', department: 'Academic', designation: 'Part Time Teacher — English', joiningDate: '04-04-2024', status: 'Active', reportingManager: 'Dr. Meera Kapoor', role: 'Teacher', qualification: 'M.A. English, B.Ed.', experience: '3 years', emergencyContact: 'Sridhar Rao (+91 98860 30300)', employmentType: 'Part Time', category: 'Part Time Academics', grossSalary: 18000, otherAllowance: 0, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-013', name: 'Deepak Verma', gender: 'Male', dateOfBirth: '28-10-1996', contact: '+91 99991 41414', email: 'deepak.verma@school.com', address: 'Pitampura, Delhi', department: 'Administration', designation: 'Part Time Clerk', joiningDate: '01-08-2026', status: 'Probation', reportingManager: 'Anita Desai', role: 'Clerk', qualification: 'B.A.', experience: '1 year', emergencyContact: 'Pooja Verma (+91 99991 41410)', employmentType: 'Part Time', category: 'Part Time Admin', grossSalary: 15000, otherAllowance: 0, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-014', name: 'Farah Qureshi', gender: 'Female', dateOfBirth: '17-02-1994', contact: '+91 98100 78787', email: 'farah.qureshi@school.com', address: 'Greater Kailash, Delhi', department: 'Academic', designation: 'Teacher — English', joiningDate: '16-09-2026', status: 'Probation', reportingManager: 'Dr. Meera Kapoor', role: 'Teacher', qualification: 'M.A. English, B.Ed.', experience: '4 years', emergencyContact: 'Imtiaz Qureshi (+91 98100 78780)', employmentType: 'Full Time', category: 'Academics', grossSalary: 40000, otherAllowance: 1000, specialDeduction: 0, otherEmployerBenefits: 0 },
        { id: 'EMP-2026-015', name: 'Mohan Das', gender: 'Male', dateOfBirth: '05-05-1980', contact: '+91 94400 65656', email: 'mohan.das@school.com', address: 'Staff Quarters, Campus', department: 'Housekeeping', designation: 'Housekeeping Attendant', joiningDate: '11-02-2016', status: 'Inactive', reportingManager: 'Suresh Pillai', role: 'Attendant', qualification: '10th', experience: '10 years', emergencyContact: 'Radha Das (+91 94400 65650)', employmentType: 'Full Time', category: 'Relieved', grossSalary: 16000, otherAllowance: 0, specialDeduction: 0, otherEmployerBenefits: 0 },
    ],
    documents: [
        { id: 'DOC-001', employeeId: 'EMP-2026-001', type: 'Offer Letter', name: 'Offer Letter — Priya Sharma', fileName: 'offer-priya.pdf', fileSize: '180 KB', uploadedDate: '01-08-2019', uploadedBy: 'HR Executive', expiryDate: '', status: 'Verified' },
        { id: 'DOC-002', employeeId: 'EMP-2026-001', type: 'Aadhaar Card', name: 'Aadhaar — Priya Sharma', fileName: 'aadhaar-priya.pdf', fileSize: '92 KB', uploadedDate: '05-08-2019', uploadedBy: 'HR Executive', expiryDate: '', status: 'Verified' },
        { id: 'DOC-003', employeeId: 'EMP-2026-005', type: 'ID Proof', name: 'ID Proof — Neha Gupta', fileName: 'id-neha.pdf', fileSize: '110 KB', uploadedDate: '02-06-2026', uploadedBy: 'Anita Desai', expiryDate: '02-06-2036', status: 'Pending' },
        { id: 'DOC-004', employeeId: 'EMP-2026-014', type: 'Educational Certificates', name: 'Certificates — Farah Qureshi', fileName: 'certs-farah.pdf', fileSize: '640 KB', uploadedDate: '10-09-2026', uploadedBy: 'Anita Desai', expiryDate: '', status: 'Verified' },
        { id: 'DOC-005', employeeId: 'EMP-2026-007', type: 'Driving Licence', name: 'HMV Licence — Ramesh Yadav', fileName: 'licence-ramesh.pdf', fileSize: '140 KB', uploadedDate: '14-04-2019', uploadedBy: 'HR Executive', expiryDate: '14-04-2027', status: 'Verified' },
    ],
    jobs: [
        { id: 'JOB-2026-001', position: 'Mathematics Teacher', department: 'Academic', designation: 'Teacher — Mathematics', openings: 2, employmentType: 'Full Time', experience: '3+ years', qualification: 'M.Sc., B.Ed.', location: 'Main Campus', postedDate: '01-09-2026', closingDate: '30-09-2026', hiringManager: 'Dr. Meera Kapoor', status: 'Open', description: 'Teach middle and senior mathematics.', internalPosting: true },
        { id: 'JOB-2026-002', position: 'Primary English Teacher', department: 'Academic', designation: 'Teacher — English', openings: 1, employmentType: 'Full Time', experience: '2+ years', qualification: 'B.Ed.', location: 'Main Campus', postedDate: '12-08-2026', closingDate: '20-09-2026', hiringManager: 'Dr. Meera Kapoor', status: 'Filled', description: 'Primary English language and literature.', internalPosting: false },
        { id: 'JOB-2026-003', position: 'School Driver', department: 'Transport', designation: 'School Driver', openings: 1, employmentType: 'Full Time', experience: '5+ years', qualification: 'HMV Licence', location: 'Transport Yard', postedDate: '05-09-2026', closingDate: '05-10-2026', hiringManager: 'Vikram Singh', status: 'Open', description: 'School bus route driving.', internalPosting: false },
        { id: 'JOB-2026-004', position: 'HR Executive', department: 'HR', designation: 'HR Executive', openings: 1, employmentType: 'Full Time', experience: '3+ years', qualification: 'MBA HR', location: 'Admin Block', postedDate: '18-08-2026', closingDate: '18-10-2026', hiringManager: 'Anita Desai', status: 'On Hold', description: 'Recruitment and employee relations.', internalPosting: true },
        { id: 'JOB-2026-005', position: 'Lab Assistant', department: 'Academic', designation: 'Lab Assistant', openings: 1, employmentType: 'Full Time', experience: '1+ year', qualification: 'B.Sc.', location: 'Science Block', postedDate: '02-07-2026', closingDate: '15-08-2026', hiringManager: 'Dr. Meera Kapoor', status: 'Closed', description: 'Support science practicals.', internalPosting: false },
    ],
    candidates: [
        { id: 'CAN-2026-001', jobId: 'JOB-2026-002', position: 'Primary English Teacher', name: 'Farah Qureshi', dateOfBirth: '17-02-1994', gender: 'Female', maritalStatus: 'Married', address: 'Greater Kailash, Delhi', mobile: '+91 98100 78787', email: 'farah.qureshi@email.com', qualification: 'M.A. English, B.Ed.', experience: '4 years', currentCompany: 'City Public School', currentSalary: 36000, expectedSalary: 42000, noticePeriod: '30 days', source: 'Employee Referral', reference: 'Priya Sharma', resumeName: 'farah-resume.pdf', resumeSize: '220 KB', applicationDate: '14-08-2026', status: 'Selected', employeeId: 'EMP-2026-014' },
        { id: 'CAN-2026-002', jobId: 'JOB-2026-001', position: 'Mathematics Teacher', name: 'Amit Khanna', dateOfBirth: '09-06-1991', gender: 'Male', maritalStatus: 'Single', address: 'Noida', mobile: '+91 98700 11122', email: 'amit.khanna@email.com', qualification: 'M.Sc. Mathematics', experience: '5 years', currentCompany: 'Sunrise Academy', currentSalary: 45000, expectedSalary: 52000, noticePeriod: '45 days', source: 'Job Portal', reference: '', resumeName: 'amit-resume.pdf', resumeSize: '180 KB', applicationDate: '03-09-2026', status: 'Interview' },
        { id: 'CAN-2026-003', jobId: 'JOB-2026-001', position: 'Mathematics Teacher', name: 'Sneha Iyer', dateOfBirth: '22-01-1996', gender: 'Female', maritalStatus: 'Single', address: 'South Delhi', mobile: '+91 99001 22334', email: 'sneha.iyer@email.com', qualification: 'B.Sc., B.Ed.', experience: '3 years', currentCompany: 'Green Valley School', currentSalary: 32000, expectedSalary: 38000, noticePeriod: '30 days', source: 'Consultancy', reference: 'ABC Consultants', resumeName: 'sneha-resume.pdf', resumeSize: '160 KB', applicationDate: '04-09-2026', status: 'Screening' },
        { id: 'CAN-2026-004', jobId: 'JOB-2026-003', position: 'School Driver', name: 'Harpreet Singh', dateOfBirth: '14-07-1988', gender: 'Male', maritalStatus: 'Married', address: 'Tilak Nagar', mobile: '+91 98111 66778', email: 'harpreet.singh@email.com', qualification: '10th, HMV', experience: '8 years', currentCompany: 'City Transport', currentSalary: 20000, expectedSalary: 24000, noticePeriod: '15 days', source: 'Walk-in', reference: '', resumeName: 'harpreet-resume.pdf', resumeSize: '90 KB', applicationDate: '06-09-2026', status: 'Interview' },
        { id: 'CAN-2026-005', jobId: 'JOB-2026-004', position: 'HR Executive', name: 'Pooja Malhotra', dateOfBirth: '30-11-1993', gender: 'Female', maritalStatus: 'Married', address: 'Rajouri Garden', mobile: '+91 98989 45454', email: 'pooja.malhotra@email.com', qualification: 'MBA HR', experience: '4 years', currentCompany: 'Edutech Pvt Ltd', currentSalary: 48000, expectedSalary: 55000, noticePeriod: '60 days', source: 'Job Portal', reference: '', resumeName: 'pooja-resume.pdf', resumeSize: '210 KB', applicationDate: '20-08-2026', status: 'On Hold' },
        { id: 'CAN-2026-006', jobId: 'JOB-2026-005', position: 'Lab Assistant', name: 'Rohan Das', dateOfBirth: '02-03-1998', gender: 'Male', maritalStatus: 'Single', address: 'Dwarka', mobile: '+91 97676 12121', email: 'rohan.das@email.com', qualification: 'B.Sc. Chemistry', experience: '1 year', currentCompany: '', currentSalary: 0, expectedSalary: 22000, noticePeriod: 'Immediate', source: 'Campus', reference: '', resumeName: 'rohan-resume.pdf', resumeSize: '140 KB', applicationDate: '10-07-2026', status: 'Rejected' },
        { id: 'CAN-2026-007', jobId: 'JOB-2026-001', position: 'Mathematics Teacher', name: 'Neha Gupta', dateOfBirth: '21-04-1998', gender: 'Female', maritalStatus: 'Single', address: 'Dwarka', mobile: '+91 97654 32100', email: 'neha.gupta@school.com', qualification: 'B.Tech IT', experience: '2 years', currentCompany: 'School ERP', currentSalary: 32000, expectedSalary: 36000, noticePeriod: 'Internal', source: 'Internal', reference: 'Anita Desai', resumeName: 'neha-internal.pdf', resumeSize: '80 KB', applicationDate: '02-09-2026', status: 'Screening' },
        { id: 'CAN-2026-008', jobId: 'JOB-2026-003', position: 'School Driver', name: 'Salim Ansari', dateOfBirth: '19-09-1986', gender: 'Male', maritalStatus: 'Married', address: 'Seelampur', mobile: '+91 98100 90909', email: 'salim.ansari@email.com', qualification: '8th, HMV', experience: '11 years', currentCompany: 'Private cab', currentSalary: 18000, expectedSalary: 22000, noticePeriod: 'Immediate', source: 'Other', reference: '', resumeName: 'salim-resume.pdf', resumeSize: '70 KB', applicationDate: '08-09-2026', status: 'Applied' },
    ],
    interviews: [
        { id: 'INT-2026-001', candidateId: 'CAN-2026-001', position: 'Primary English Teacher', level: 'HR', interviewer: 'Anita Desai', date: '20-08-2026', time: '10:30 AM', mode: 'In Person', status: 'Selected', score: 3, remarks: 'Strong classroom examples.', strengths: 'Communication', concerns: 'None material', recommendation: 'Select', nextStep: 'Offer', technical: 3, communication: 3, experienceMatch: 3, roleFit: 3, finalDecision: 'Selected' },
        { id: 'INT-2026-002', candidateId: 'CAN-2026-001', position: 'Primary English Teacher', level: 'Level 1', interviewer: 'Dr. Meera Kapoor', date: '18-08-2026', time: '11:00 AM', mode: 'In Person', status: 'Next Round', score: 3, remarks: 'Demo class was clear.', strengths: 'Planning', concerns: 'Pacing', recommendation: 'Next Round', nextStep: 'HR', technical: 3, communication: 2, experienceMatch: 3, roleFit: 3, finalDecision: 'Next Round' },
        { id: 'INT-2026-003', candidateId: 'CAN-2026-002', position: 'Mathematics Teacher', level: 'Screening', interviewer: 'Anita Desai', date: '08-09-2026', time: '09:30 AM', mode: 'Phone', status: 'Completed', score: 2, remarks: 'Eligible for demo.', strengths: 'Subject depth', concerns: 'Notice period', recommendation: 'Next Round', nextStep: 'Level 1', technical: 2, communication: 2, experienceMatch: 3, roleFit: 2, finalDecision: 'Next Round' },
        { id: 'INT-2026-004', candidateId: 'CAN-2026-002', position: 'Mathematics Teacher', level: 'Technical', interviewer: 'Priya Sharma', date: '25-09-2026', time: '02:00 PM', mode: 'In Person', status: 'Scheduled', score: 0, remarks: '', strengths: '', concerns: '', recommendation: '', nextStep: '', technical: 0, communication: 0, experienceMatch: 0, roleFit: 0, finalDecision: '' },
        { id: 'INT-2026-005', candidateId: 'CAN-2026-004', position: 'School Driver', level: 'HR', interviewer: 'Anita Desai', date: '12-09-2026', time: '04:00 PM', mode: 'In Person', status: 'Scheduled', score: 0, remarks: '', strengths: '', concerns: '', recommendation: '', nextStep: '', technical: 0, communication: 0, experienceMatch: 0, roleFit: 0, finalDecision: '' },
        { id: 'INT-2026-006', candidateId: 'CAN-2026-006', position: 'Lab Assistant', level: 'Level 1', interviewer: 'Science HOD', date: '18-07-2026', time: '11:30 AM', mode: 'In Person', status: 'Rejected', score: 1, remarks: 'Limited practical exposure.', strengths: 'Punctual', concerns: 'Safety awareness', recommendation: 'Reject', nextStep: 'Close', technical: 1, communication: 2, experienceMatch: 1, roleFit: 1, finalDecision: 'Rejected' },
    ],
    offers: [
        { id: 'OFR-2026-001', candidateId: 'CAN-2026-001', employeeId: 'EMP-2026-014', position: 'Primary English Teacher', department: 'Academic', designation: 'Teacher — English', joiningDate: '16-09-2026', employmentType: 'Full Time', grossSalary: 40000, ctc: 520000, probation: '6 months', reportingManager: 'Dr. Meera Kapoor', offerDate: '22-08-2026', validityDate: '05-09-2026', terms: 'Confirmation after satisfactory probation.', status: 'Accepted', kind: 'Offer' },
        { id: 'OFR-2026-002', candidateId: 'CAN-2026-001', employeeId: 'EMP-2026-014', position: 'Primary English Teacher', department: 'Academic', designation: 'Teacher — English', joiningDate: '16-09-2026', employmentType: 'Full Time', grossSalary: 40000, ctc: 520000, probation: '6 months', reportingManager: 'Dr. Meera Kapoor', offerDate: '06-09-2026', validityDate: '16-09-2026', terms: 'Appointment effective from joining date.', status: 'Issued', kind: 'Appointment' },
        { id: 'OFR-2026-003', candidateId: 'CAN-2026-002', employeeId: '', position: 'Mathematics Teacher', department: 'Academic', designation: 'Teacher — Mathematics', joiningDate: '01-11-2026', employmentType: 'Full Time', grossSalary: 50000, ctc: 650000, probation: '6 months', reportingManager: 'Dr. Meera Kapoor', offerDate: '20-09-2026', validityDate: '05-10-2026', terms: 'Draft pending final interview.', status: 'Draft', kind: 'Offer' },
    ],
    onboarding: [
        { id: 'ONB-2026-001', employeeId: 'EMP-2026-014', joiningDate: '16-09-2026', overallStatus: 'In Progress', checklist: checklist(8) },
        { id: 'ONB-2026-002', employeeId: 'EMP-2026-005', joiningDate: '02-06-2026', overallStatus: 'Completed', checklist: checklist(16) },
        { id: 'ONB-2026-003', employeeId: 'EMP-2026-013', joiningDate: '01-08-2026', overallStatus: 'In Progress', checklist: checklist(5) },
    ],
    observations: [
        { id: 'OBS-2026-001', employeeId: 'EMP-2026-013', template: 'Admin', reviewDate: '20-08-2026', status: 'Completed', reviewers: [{ name: 'Anita Desai', scores: { 'Job Knowledge': 2, Punctuality: 3, 'Quality of Work': 2, Communication: 2, Teamwork: 3, Presentation: 2, Reporting: 2 }, comments: 'Learning office flow.' }, { name: 'Rahul Mehta', scores: { 'Job Knowledge': 2, Punctuality: 2, 'Quality of Work': 2, Communication: 2, Teamwork: 2, Presentation: 2, Reporting: 2 }, comments: 'Needs filing accuracy.' }], appreciation: 'Willing to learn.', improvement: 'Document naming.', remarks: 'Continue shadowing.' },
        { id: 'OBS-2026-002', employeeId: 'EMP-2026-014', template: 'Academics', reviewDate: '22-09-2026', status: 'In Progress', reviewers: [{ name: 'Dr. Meera Kapoor', scores: { 'Planning & Preparation': 3, 'Classroom Management': 2, 'Teaching Practice': 3, Communication: 3, Teamwork: 2, 'Problem Solving': 2, 'Time Management': 2, Leadership: 2, 'Professional Responsibility': 3 } }, { name: 'Priya Sharma', scores: { 'Planning & Preparation': 2, 'Classroom Management': 2, 'Teaching Practice': 3, Communication: 3, Teamwork: 3, 'Problem Solving': 2, 'Time Management': 2, Leadership: 2, 'Professional Responsibility': 3 } }, { name: 'Arjun Patel', scores: { 'Planning & Preparation': 2, 'Classroom Management': 2, 'Teaching Practice': 2, Communication: 3, Teamwork: 3, 'Problem Solving': 2, 'Time Management': 2, Leadership: 2, 'Professional Responsibility': 2 } }], appreciation: 'Warm with students.', improvement: 'Lesson timing.', remarks: 'Second observation due in October.' },
    ],
    shadow: [
        { id: 'SHD-2026-001', employeeId: 'EMP-2026-014', mentorId: 'EMP-2026-001', startDate: '16-09-2026', endDate: '30-09-2026', duration: '15 days', schoolEthos: 3, adaptability: 2, acceptance: 3, menteeResponse: 'Asks useful questions.', practicalDifficulties: 'Timetable overlap on Wednesdays.', bestQualities: 'Clear speech and patience.', generalComments: 'Settling well.', mentorRemarks: 'Ready for independent sections next week.', reviewerRemarks: 'Continue paired classes.', status: 'In Progress' },
        { id: 'SHD-2026-002', employeeId: 'EMP-2026-005', mentorId: 'EMP-2026-003', startDate: '02-06-2026', endDate: '16-06-2026', duration: '15 days', schoolEthos: 3, adaptability: 3, acceptance: 3, menteeResponse: 'Quick on systems.', practicalDifficulties: 'None after week one.', bestQualities: 'Documentation.', generalComments: 'Completed.', mentorRemarks: 'Can handle tickets independently.', reviewerRemarks: 'Close shadow period.', status: 'Completed' },
    ],
    training: [
        { id: 'TRN-2026-001', title: 'Communication Skills', category: 'Soft Skills', trainer: 'External Faculty', department: 'Academic', participantIds: ['EMP-2026-001', 'EMP-2026-014', 'EMP-2026-012'], startDate: '25-09-2026', endDate: '25-09-2026', time: '10:00 AM', location: 'Seminar Hall', mode: 'In Person', description: 'Staff communication workshop.', status: 'Scheduled', photos: [], attendance: {}, feedback: [] },
        { id: 'TRN-2026-002', title: 'Classroom Management Workshop', category: 'Academics', trainer: 'Dr. Meera Kapoor', department: 'Academic', participantIds: ['EMP-2026-001', 'EMP-2026-011'], startDate: '15-03-2026', endDate: '15-03-2026', time: '09:00 AM', location: 'Academic Block A', mode: 'In Person', description: 'Classroom routines.', status: 'Completed', photos: [{ name: 'classroom-workshop.jpg', size: '1.2 MB' }], attendance: { 'EMP-2026-001': 'Present', 'EMP-2026-011': 'Present' }, feedback: [{ employeeId: 'EMP-2026-001', relevance: 3, trainer: 3, content: 3, usefulness: 3, overall: 3, comments: 'Practical examples.' }] },
        { id: 'TRN-2026-003', title: 'Transport Safety Briefing', category: 'Operations', trainer: 'Vikram Singh', department: 'Transport', participantIds: ['EMP-2026-007', 'EMP-2026-008'], startDate: '10-09-2026', endDate: '10-09-2026', time: '08:00 AM', location: 'Transport Yard', mode: 'In Person', description: 'Route safety and student boarding.', status: 'Completed', photos: [], attendance: { 'EMP-2026-007': 'Present', 'EMP-2026-008': 'Present' }, feedback: [] },
        { id: 'TRN-2026-004', title: 'HR Policy Orientation', category: 'HR', trainer: 'Anita Desai', department: 'HR', participantIds: ['EMP-2026-005', 'EMP-2026-013', 'EMP-2026-014'], startDate: '05-09-2026', endDate: '05-09-2026', time: '03:00 PM', location: 'HR Cabin', mode: 'In Person', description: 'Leave, conduct, and payroll basics.', status: 'Completed', photos: [], attendance: { 'EMP-2026-005': 'Present', 'EMP-2026-013': 'Present', 'EMP-2026-014': 'Absent' }, feedback: [{ employeeId: 'EMP-2026-005', relevance: 3, trainer: 2, content: 3, usefulness: 3, overall: 3, comments: 'Clear policies.' }] },
    ],
    leave: {
        policies: [
            { id: 'POL-001', name: 'Academic Casual Leave', category: 'Academics', leaveType: 'Casual Leave', entitlement: 12, carryForward: false, maxConsecutive: 3, paid: true, approvalRequired: true, active: true },
            { id: 'POL-002', name: 'Admin Earned Leave', category: 'Admin', leaveType: 'Earned Leave', entitlement: 15, carryForward: true, maxConsecutive: 7, paid: true, approvalRequired: true, active: true },
            { id: 'POL-003', name: 'Support Sick Leave', category: 'Support / Operations', leaveType: 'Sick Leave', entitlement: 8, carryForward: false, maxConsecutive: 5, paid: true, approvalRequired: true, active: true },
        ],
        requests: [
            { id: 'LVE-001', employeeId: 'EMP-2026-001', leaveType: 'Casual Leave', fromDate: '03-06-2026', toDate: '03-06-2026', days: 1, reason: 'Personal work', status: 'Approved', approvedBy: 'Dr. Meera Kapoor' },
            { id: 'LVE-002', employeeId: 'EMP-2026-004', leaveType: 'Sick Leave', fromDate: '18-09-2026', toDate: '20-09-2026', days: 3, reason: 'Medical rest', status: 'Approved', approvedBy: 'Transport Manager' },
            { id: 'LVE-003', employeeId: 'EMP-2026-012', leaveType: 'Casual Leave', fromDate: '28-09-2026', toDate: '28-09-2026', days: 1, reason: 'Family function', status: 'Pending', approvedBy: '' },
            { id: 'LVE-004', employeeId: 'EMP-2026-007', leaveType: 'Earned Leave', fromDate: '02-10-2026', toDate: '04-10-2026', days: 3, reason: 'Hometown visit', status: 'Pending', approvedBy: '' },
        ],
    },
    attendance: [
        { id: 'ATT-001', employeeId: 'EMP-2026-001', date: '22-09-2026', checkIn: '08:25 AM', checkOut: '04:30 PM', status: 'Present', source: 'ESSL Demo', punchIn: '08:25', punchOut: '16:30' },
        { id: 'ATT-002', employeeId: 'EMP-2026-004', date: '22-09-2026', checkIn: '—', checkOut: '—', status: 'Leave', source: 'ESSL Demo', punchIn: '', punchOut: '' },
        { id: 'ATT-003', employeeId: 'EMP-2026-007', date: '22-09-2026', checkIn: '07:10 AM', checkOut: '05:05 PM', status: 'Present', source: 'ESSL Demo', punchIn: '07:10', punchOut: '17:05' },
        { id: 'ATT-004', employeeId: 'EMP-2026-014', date: '22-09-2026', checkIn: '08:42 AM', checkOut: '04:20 PM', status: 'Late', source: 'ESSL Demo', punchIn: '08:42', punchOut: '16:20' },
        { id: 'ATT-005', employeeId: 'EMP-2026-009', date: '22-09-2026', checkIn: '—', checkOut: '—', status: 'Absent', source: 'ESSL Demo', punchIn: '', punchOut: '' },
    ],
    payroll: {
        months: [
            { employeeId: 'EMP-2026-001', month: 'June', year: 2026, workingDays: 26, lates: 2, permission: 1, casualLeave: 1, otherLeave: 0, absent: 0, notPunched: 0, paymentStatus: 'Paid', bankRef: 'NEFT-JUN-001', paymentDate: '30-06-2026', paymentMode: 'Bank Transfer' },
            { employeeId: 'EMP-2026-007', month: 'June', year: 2026, workingDays: 26, lates: 4, permission: 0, casualLeave: 0, otherLeave: 1, absent: 1, notPunched: 1, paymentStatus: 'Paid', bankRef: 'NEFT-JUN-007', paymentDate: '30-06-2026', paymentMode: 'Bank Transfer' },
            { employeeId: 'EMP-2026-008', month: 'June', year: 2026, workingDays: 26, lates: 1, permission: 0, casualLeave: 0, otherLeave: 0, absent: 0, notPunched: 0, paymentStatus: 'Unpaid', bankRef: '', paymentDate: '', paymentMode: 'Bank Transfer' },
            { employeeId: 'EMP-2026-012', month: 'June', year: 2026, workingDays: 26, lates: 0, permission: 2, casualLeave: 2, otherLeave: 0, absent: 0, notPunched: 0, paymentStatus: 'Unpaid', bankRef: '', paymentDate: '', paymentMode: 'Bank Transfer' },
        ],
        revisions: [
            { id: 'REV-2026-001', employeeId: 'EMP-2026-001', effectiveDate: '01-04-2026', currentDesignation: 'Teacher — Mathematics', newDesignation: 'Senior Teacher — Mathematics', currentGross: 60000, revisionPercent: 8.33, revisedGross: 65000, promotion: true, incrementType: 'Promotion', reason: 'Annual review and additional section load.', approvedBy: 'Director Academics', status: 'Applied' },
            { id: 'REV-2026-002', employeeId: 'EMP-2026-002', effectiveDate: '01-04-2026', currentDesignation: 'Accounts Executive', newDesignation: 'Accounts Executive', currentGross: 45000, revisionPercent: 6.67, revisedGross: 48000, promotion: false, incrementType: 'Annual Increment', reason: 'Satisfactory audit support.', approvedBy: 'MD', status: 'Approved' },
        ],
    },
    payslips: [],
    advances: [
        { id: 'ADV-2026-001', employeeId: 'EMP-2026-007', amount: 20000, reason: 'Medical expense for parent.', requestedDate: '05-06-2026', months: 10, existingLoan: false, existingAmount: 0, outstanding: 16000, emi: 2000, currentDeduction: 2000, disciplinary: 'None', remarks: 'Recover from June payroll.', status: 'APPROVED', chain: [{ actor: 'HR', decision: 'Recommended', at: '06-06-2026', comments: 'Genuine need.' }, { actor: 'Finance', decision: 'Recommended', at: '07-06-2026', comments: 'Within limit.' }, { actor: 'JD Admin', decision: 'Recommended', at: '08-06-2026', comments: '' }, { actor: 'Director Academics', decision: 'Recommended', at: '09-06-2026', comments: '' }, { actor: 'MD', decision: 'Approved', at: '10-06-2026', comments: 'Approve recovery.' }] },
        { id: 'ADV-2026-002', employeeId: 'EMP-2026-006', amount: 15000, reason: 'House repair.', requestedDate: '12-09-2026', months: 6, existingLoan: true, existingAmount: 4000, outstanding: 4000, emi: 2500, currentDeduction: 0, disciplinary: 'None', remarks: '', status: 'FINANCE_REVIEW', chain: [{ actor: 'HR', decision: 'Recommended', at: '13-09-2026', comments: 'Forward to finance.' }] },
    ],
    referrals: [
        { id: 'REF-2026-001', referrerId: 'EMP-2026-001', candidateId: 'CAN-2026-001', position: 'Primary English Teacher', department: 'Academic', joiningDate: '16-09-2026', grossSalary: 40000, referralDate: '14-08-2026', eligibilityDate: '16-12-2026', percent: 15, amount: 6000, status: 'Eligible', remarks: 'Candidate joined. Bonus after 3 months.' },
        { id: 'REF-2026-002', referrerId: 'EMP-2026-003', candidateId: 'CAN-2026-007', position: 'Mathematics Teacher', department: 'Academic', joiningDate: '', grossSalary: 0, referralDate: '02-09-2026', eligibilityDate: '', percent: 15, amount: 0, status: 'Pending', remarks: 'Internal application still in screening.' },
    ],
    concessions: [
        { id: 'CON-2026-001', employeeId: 'EMP-2026-001', studentName: 'Aarav Sharma', relationship: 'Son', admissionNumber: 'ADM-2024-014', className: 'Class 6', academicYear: '2026-27', type: 'Staff Child Tuition', percent: 50, amount: 24000, from: '01-04-2026', to: '31-03-2027', status: 'Approved', approvedBy: 'Director Academics' },
        { id: 'CON-2026-002', employeeId: 'EMP-2026-010', studentName: 'Kiara Joshi', relationship: 'Daughter', admissionNumber: 'ADM-2025-033', className: 'Class 3', academicYear: '2026-27', type: 'Hostel Fee Concession', percent: 25, amount: 12000, from: '01-04-2026', to: '31-03-2027', status: 'Pending', approvedBy: '' },
    ],
    disciplinary: [
        { id: 'DSC-2026-001', employeeId: 'EMP-2026-009', date: '04-08-2026', actionType: 'Warning', incident: 'Late reporting at main gate.', details: 'Two late arrivals in one week without prior permission.', previous: 'None', explanation: 'Traffic delay. Will report earlier.', acknowledgement: 'Acknowledged', remarks: 'Verbal counselling recorded.', status: 'APPROVED', chain: [{ actor: 'HR Manager', decision: 'Recommended', at: '04-08-2026', comments: '' }, { actor: 'JD Admin', decision: 'Recommended', at: '05-08-2026', comments: '' }, { actor: 'Director Academics', decision: 'Recommended', at: '06-08-2026', comments: '' }, { actor: 'Managing Director', decision: 'Approved', at: '07-08-2026', comments: 'Issue warning.' }] },
        { id: 'DSC-2026-002', employeeId: 'EMP-2026-008', date: '18-09-2026', actionType: 'Memo', incident: 'Student headcount mismatch on Route 4.', details: 'One student was not marked at drop.', previous: 'None', explanation: 'Pending.', acknowledgement: 'Pending', remarks: '', status: 'JD_REVIEW', chain: [{ actor: 'HR Manager', decision: 'Recommended', at: '18-09-2026', comments: 'Issue memo.' }] },
        { id: 'DSC-2026-003', employeeId: 'EMP-2026-001', date: '10-06-2026', actionType: 'Memo', incident: 'Uninformed late arrival.', details: 'Approved memo for June payroll.', previous: 'None', explanation: '', acknowledgement: 'Acknowledged', remarks: 'One day salary deduction.', status: 'APPROVED', chain: [{ actor: 'Managing Director', decision: 'Approved', at: '11-06-2026', comments: 'Issue memo.' }] },
        { id: 'DSC-2026-004', employeeId: 'EMP-2026-002', date: '12-06-2026', actionType: 'Suspended', incident: 'Repeated policy breach.', details: 'Approved suspension for June payroll.', previous: 'Warning', explanation: '', acknowledgement: 'Acknowledged', remarks: 'Two day salary deduction.', status: 'APPROVED', chain: [{ actor: 'Managing Director', decision: 'Approved', at: '13-06-2026', comments: 'Suspend for two days pay.' }] },
    ],
    exits: [
        { id: 'EXT-2026-001', employeeId: 'EMP-2026-015', lastWorkingDate: '31-08-2026', exitType: 'Resignation', reason: 'Relocation.', noticePeriod: '30 days', noticeServed: true, handover: true, assets: true, documents: true, finance: true, departmentClearance: true, hrClearance: true, exitInterview: true, remarks: 'Cleared.', status: 'Completed' },
        { id: 'EXT-2026-002', employeeId: 'EMP-2026-004', lastWorkingDate: '15-11-2026', exitType: 'Resignation', reason: 'Personal.', noticePeriod: '30 days', noticeServed: false, handover: false, assets: false, documents: false, finance: false, departmentClearance: false, hrClearance: false, exitInterview: false, remarks: 'Notice started.', status: 'Initiated' },
    ],
    performance: [
        { id: 'PRF-2026-001', employeeId: 'EMP-2026-001', period: '2025–26', reviewer: 'Dr. Meera Kapoor', goals: 'Improve board result average.', bsc: 86, audit: 82, score: 4.2, strengths: 'Subject command', improvement: 'Differentiated worksheets', remarks: 'Above average contribution.', rating: 'Above Average', status: 'Completed' },
        { id: 'PRF-2026-002', employeeId: 'EMP-2026-002', period: '2025–26', reviewer: 'Account Head', goals: 'Close fee reconciliation by the 5th.', bsc: 74, audit: 78, score: 3.6, strengths: 'Accuracy', improvement: 'Faster follow-up', remarks: 'Steady.', rating: 'Average', status: 'Completed' },
        { id: 'PRF-2026-003', employeeId: 'EMP-2026-011', period: '2025–26', reviewer: 'Dr. Meera Kapoor', goals: 'Inter-school sports participation.', bsc: 68, audit: 70, score: 3.1, strengths: 'Energy', improvement: 'Attendance of practice', remarks: 'Needs consistency.', rating: 'Average', status: 'Pending' },
        { id: 'PRF-2026-004', employeeId: 'EMP-2026-006', period: '2025–26', reviewer: 'Admin Officer', goals: 'Reduce complaint tickets.', bsc: 60, audit: 58, score: 2.4, strengths: 'Coverage', improvement: 'Checklist closure', remarks: 'Below target this term.', rating: 'Below Average', status: 'Pending' },
    ],
    notifications: [
        { id: 'HR-NTF-001', type: 'Training', title: 'Upcoming Training', message: 'Communication Skills on 25 Sep 2026 at 10:00 AM, Seminar Hall.', relatedDate: '25-09-2026', notificationDate: '18-09-2026', postedBy: 'HR', isRead: false },
        { id: 'HR-NTF-002', type: 'Recruitment', title: 'Interview Scheduled', message: 'Technical interview for Amit Khanna on 25 Sep 2026 at 02:00 PM.', relatedDate: '25-09-2026', notificationDate: '10-09-2026', postedBy: 'HR', isRead: false },
        { id: 'HR-NTF-003', type: 'Payroll', title: 'Salary Advance Pending', message: 'Salary advance ADV-2026-002 is waiting at Finance review.', relatedDate: '12-09-2026', notificationDate: '13-09-2026', postedBy: 'HR', isRead: true },
        { id: 'HR-NTF-004', type: 'Internal Job', title: 'Internal Job Opening', message: 'Mathematics Teacher is open for internal applicants.', relatedDate: '30-09-2026', notificationDate: '01-09-2026', postedBy: 'HR', isRead: false },
    ],
    claims: [],
    announcements: [],
    comms: [
        { id: 'COM-001', channel: 'Email', subject: 'Offer letter — Farah Qureshi', audience: 'farah.qureshi@email.com', status: 'DEMO_SENT', at: '22-08-2026 11:05' },
        { id: 'COM-002', channel: 'WhatsApp', subject: 'Interview schedule — Amit Khanna', audience: '+91 98700 11122', status: 'QUEUED', at: '10-09-2026 09:10' },
    ],
}

export const ADMIN_CRITERIA = ['Job Knowledge', 'Punctuality', 'Quality of Work', 'Communication', 'Teamwork', 'Presentation', 'Reporting']
export const ACADEMIC_CRITERIA = ['Planning & Preparation', 'Classroom Management', 'Teaching Practice', 'Communication', 'Teamwork', 'Problem Solving', 'Time Management', 'Leadership', 'Professional Responsibility']
export const ONBOARDING_ITEMS = [
    'Offer Accepted', 'Appointment Letter Issued', 'Employee ID Created', 'Personal Details Completed',
    'Documents Collected', 'Department Assigned', 'Reporting Manager Assigned', 'HR Orientation',
    'Policy Acknowledgement', 'System Access', 'ID Card', 'Bank Details', 'Training Scheduled',
    'Shadow Mentor Assigned', 'Observation Scheduled', 'Onboarding Completed',
]
export const ADVANCE_FLOW = ['DRAFT', 'SUBMITTED', 'HR_REVIEW', 'FINANCE_REVIEW', 'JD_REVIEW', 'DIRECTOR_REVIEW', 'MD_REVIEW', 'APPROVED']
export const ADVANCE_ACTORS = { HR_REVIEW: 'HR', FINANCE_REVIEW: 'Finance', JD_REVIEW: 'JD Admin', DIRECTOR_REVIEW: 'Director Academics', MD_REVIEW: 'MD' }
export const DISCIPLINE_FLOW = ['DRAFT', 'HR_REVIEW', 'JD_REVIEW', 'DIRECTOR_REVIEW', 'MD_REVIEW', 'APPROVED']
export const DISCIPLINE_ACTORS = { HR_REVIEW: 'HR Manager', JD_REVIEW: 'JD Admin', DIRECTOR_REVIEW: 'Director Academics', MD_REVIEW: 'Managing Director' }
