export const ACCOUNTING_SECTIONS = [
    { id: 'day-book', label: 'Day Book' },
    { id: 'online-book', label: 'Online Book' },
    { id: 'general-ledger', label: 'General Ledger' },
    { id: 'cash-book', label: 'Cash Book' },
    { id: 'bank-book', label: 'Bank Book' },
    { id: 'chart-of-accounts', label: 'Chart of Accounts' },
    { id: 'journal-vouchers', label: 'Journal Vouchers' },
    { id: 'bank-reconciliation', label: 'Bank Reconciliation' },
    { id: 'financial-statements', label: 'Financial Statements' },
]

export const DEFAULT_ACCOUNTING_SECTION = 'day-book'

export const ACCOUNTING_YEARS = ['2026–27', '2025–26', '2024–25', '2023–24']

export const GENERAL_LEDGER_ACCOUNTS = [
    'All Accounts',
    'Bank — SBI Current A/c',
    'Cash in Hand',
    'Fee Income — Tuition',
    'Fee Income — Transport',
    'Salary Expense — Teaching',
    'Transport Expense — Fuel',
    'Utilities & Maintenance',
    'Donations & Grants',
    'Wallet Float (User Wallets)',
]

export const GENERAL_LEDGER_VOUCHER_TYPES = ['All Types', 'Receipt', 'Payment', 'Journal', 'Contra']
export const GENERAL_LEDGER_DEPARTMENTS = ['All Departments', 'Fees', 'Transport', 'Payroll', 'Admin', 'Facilities', 'Accounting']
export const GENERAL_LEDGER_FINANCIAL_YEARS = ACCOUNTING_YEARS

export const GENERAL_LEDGER_REGISTER = [
    {
        id: 'GL-001',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucherNo: 'JV-2026-0884',
        ledgerAccount: 'Bank — SBI Current A/c',
        description: 'Fee receipt — Arun Raj (10-A)',
        debit: '₹12,400',
        credit: '—',
        balance: '₹52,92,400',
        referenceModule: 'Fees Management',
        voucherType: 'Receipt',
        department: 'Fees',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-002',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucherNo: 'JV-2026-0884',
        ledgerAccount: 'Fee Income — Tuition',
        description: 'Fee receipt — Arun Raj (10-A)',
        debit: '—',
        credit: '₹12,400',
        balance: '₹2,41,12,400',
        referenceModule: 'Fees Management',
        voucherType: 'Receipt',
        department: 'Fees',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-003',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucherNo: 'JV-2026-0883',
        ledgerAccount: 'Cash in Hand',
        description: 'Transport fee — Route 4 collection',
        debit: '₹1,800',
        credit: '—',
        balance: '₹3,42,000',
        referenceModule: 'Day Book',
        voucherType: 'Receipt',
        department: 'Transport',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-004',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucherNo: 'JV-2026-0883',
        ledgerAccount: 'Fee Income — Transport',
        description: 'Transport fee — Route 4 collection',
        debit: '—',
        credit: '₹1,800',
        balance: '₹28,41,800',
        referenceModule: 'Day Book',
        voucherType: 'Receipt',
        department: 'Transport',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-005',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucherNo: 'JV-2026-0881',
        ledgerAccount: 'Salary Expense — Teaching',
        description: 'June salary disbursal — 84 teaching staff',
        debit: '₹14,80,000',
        credit: '—',
        balance: '₹1,68,80,000',
        referenceModule: 'Payroll',
        voucherType: 'Payment',
        department: 'Payroll',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-006',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucherNo: 'JV-2026-0881',
        ledgerAccount: 'Bank — SBI Current A/c',
        description: 'June salary disbursal — 84 teaching staff',
        debit: '—',
        credit: '₹14,80,000',
        balance: '₹52,80,000',
        referenceModule: 'Payroll',
        voucherType: 'Payment',
        department: 'Payroll',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-007',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucherNo: 'JV-2026-0880',
        ledgerAccount: 'Bank — SBI Current A/c',
        description: 'Online fee settlement — Razorpay batch',
        debit: '₹1,86,400',
        credit: '—',
        balance: '₹67,60,000',
        referenceModule: 'Online Book',
        voucherType: 'Receipt',
        department: 'Fees',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-008',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucherNo: 'JV-2026-0880',
        ledgerAccount: 'Fee Income — Tuition',
        description: 'Online fee settlement — Razorpay batch',
        debit: '—',
        credit: '₹1,86,400',
        balance: '₹2,41,86,400',
        referenceModule: 'Online Book',
        voucherType: 'Receipt',
        department: 'Fees',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-009',
        date: '24 Jun 2026',
        dateIso: '2026-06-24',
        voucherNo: 'JV-2026-0878',
        ledgerAccount: 'Transport Expense — Fuel',
        description: 'Vehicle service payment — Sri Balaji Motors',
        debit: '₹6,200',
        credit: '—',
        balance: '₹18,66,200',
        referenceModule: 'Transport Finance',
        voucherType: 'Payment',
        department: 'Transport',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-010',
        date: '24 Jun 2026',
        dateIso: '2026-06-24',
        voucherNo: 'JV-2026-0878',
        ledgerAccount: 'Bank — SBI Current A/c',
        description: 'Vehicle service payment — Sri Balaji Motors',
        debit: '—',
        credit: '₹6,200',
        balance: '₹65,73,600',
        referenceModule: 'Transport Finance',
        voucherType: 'Payment',
        department: 'Transport',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-011',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        voucherNo: 'JV-2026-0875',
        ledgerAccount: 'Cash in Hand',
        description: 'Cash deposit to bank — daily collection',
        debit: '—',
        credit: '₹1,20,000',
        balance: '₹3,40,200',
        referenceModule: 'Day Book',
        voucherType: 'Contra',
        department: 'Accounting',
        financialYear: '2025–26',
        status: 'Posted',
    },
    {
        id: 'GL-012',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        voucherNo: 'JV-2026-0875',
        ledgerAccount: 'Bank — SBI Current A/c',
        description: 'Cash deposit to bank — daily collection',
        debit: '₹1,20,000',
        credit: '—',
        balance: '₹65,79,800',
        referenceModule: 'Day Book',
        voucherType: 'Contra',
        department: 'Accounting',
        financialYear: '2025–26',
        status: 'Posted',
    },
]

export const COA_ACCOUNT_TYPES = ['Asset', 'Liability', 'Income', 'Expense', 'Equity']

export const COA_PARENT_ACCOUNTS = [
    'None (Top-level)',
    '1000 · Current Assets',
    '1100 · Receivables',
    '2000 · Current Liabilities',
    '4000 · Fee Income',
    '5000 · Salary Expense',
    '5100 · Operational Expense',
]

export const DEFAULT_ADD_ACCOUNT_FORM = {
    accountCode: '',
    accountName: '',
    parentAccount: 'None (Top-level)',
    accountType: 'Expense',
    openingBalance: '',
}

export const COA_ACCOUNT_TREE = [
    {
        title: 'Assets',
        children: ['Cash', 'Bank', 'Receivables'],
    },
    {
        title: 'Liabilities',
        children: ['Payables'],
    },
    {
        title: 'Income',
        children: ['Tuition Fee', 'Transport Fee', 'Hostel Fee'],
    },
    {
        title: 'Expenses',
        children: ['Salary', 'Electricity', 'Fuel', 'Maintenance'],
    },
]

export const COA_ACCOUNTS = [
    { id: 'COA-001', accountCode: '1010', accountName: 'Cash in Hand', accountType: 'Asset', parentAccount: '1000 · Current Assets', status: 'Active', balance: '₹3,40,200' },
    { id: 'COA-002', accountCode: '1011', accountName: 'Petty Cash — Office', accountType: 'Asset', parentAccount: 'Cash', status: 'Active', balance: '₹24,150' },
    { id: 'COA-003', accountCode: '1020', accountName: 'Bank — SBI Current A/c', accountType: 'Asset', parentAccount: 'Bank', status: 'Active', balance: '₹52,80,000' },
    { id: 'COA-004', accountCode: '1021', accountName: 'Bank — ICICI Savings A/c', accountType: 'Asset', parentAccount: 'Bank', status: 'Active', balance: '₹2,00,000' },
    { id: 'COA-005', accountCode: '1110', accountName: 'Student Fee Receivable', accountType: 'Asset', parentAccount: 'Receivables', status: 'Active', balance: '₹9,50,000' },
    { id: 'COA-006', accountCode: '2020', accountName: 'Vendor Payables', accountType: 'Liability', parentAccount: 'Payables', status: 'Active', balance: '₹4,20,000' },
    { id: 'COA-007', accountCode: '2010', accountName: 'TDS Payable', accountType: 'Liability', parentAccount: 'Payables', status: 'Active', balance: '₹1,40,000' },
    { id: 'COA-008', accountCode: '4010', accountName: 'Tuition Fee', accountType: 'Income', parentAccount: 'Tuition Fee', status: 'Active', balance: '₹1,86,00,000' },
    { id: 'COA-009', accountCode: '4020', accountName: 'Transport Fee', accountType: 'Income', parentAccount: 'Transport Fee', status: 'Active', balance: '₹28,40,000' },
    { id: 'COA-010', accountCode: '4030', accountName: 'Hostel Fee', accountType: 'Income', parentAccount: 'Hostel Fee', status: 'Active', balance: '₹12,60,000' },
    { id: 'COA-011', accountCode: '5010', accountName: 'Salary — Teaching Staff', accountType: 'Expense', parentAccount: 'Salary', status: 'Active', balance: '₹1,68,00,000' },
    { id: 'COA-012', accountCode: '5120', accountName: 'Electricity', accountType: 'Expense', parentAccount: 'Electricity', status: 'Active', balance: '₹8,40,000' },
    { id: 'COA-013', accountCode: '5110', accountName: 'Fuel', accountType: 'Expense', parentAccount: 'Fuel', status: 'Active', balance: '₹18,60,000' },
    { id: 'COA-014', accountCode: '5121', accountName: 'Maintenance', accountType: 'Expense', parentAccount: 'Maintenance', status: 'Active', balance: '₹11,40,000' },
    { id: 'COA-015', accountCode: '1030', accountName: 'Wallet Float (User Wallets)', accountType: 'Asset', parentAccount: '1000 · Current Assets', status: 'Active', balance: '₹5,40,000' },
    { id: 'COA-016', accountCode: '5130', accountName: 'Office Supplies', accountType: 'Expense', parentAccount: '5100 · Operational Expense', status: 'Inactive', balance: '₹0' },
]

export const coaStatusBadgeColor = {
    Active: 'bg-[#4CAF5033] text-[#4CAF50]',
    Inactive: 'bg-[#EDEEF5] text-[#667085]',
}

export const coaTypeBadgeColor = {
    Asset: 'bg-[#515DEF33] text-[#515DEF]',
    Liability: 'bg-[#FF980033] text-[#FF9800]',
    Income: 'bg-[#4CAF5033] text-[#4CAF50]',
    Expense: 'bg-[#FF572233] text-[#FF5722]',
    Equity: 'bg-[#66708533] text-[#667085]',
}

/** @deprecated Use COA_ACCOUNT_TREE and COA_ACCOUNTS */
export const CHART_OF_ACCOUNTS = {
    assets: {
        title: 'Assets',
        rows: [
            { label: '1000 · Current Assets', amount: '₹61.4L', head: true },
            { label: '1010 · Bank — SBI Current A/c', amount: '₹52.8L' },
            { label: '1020 · Cash in Hand', amount: '₹3.2L' },
            { label: '1030 · Wallet Float (User Wallets)', amount: '₹5.4L' },
            { label: '1100 · Receivables', amount: '₹9.5L', head: true },
            { label: '1110 · Student Fee Receivable', amount: '₹9.5L' },
        ],
    },
    liabilities: {
        title: 'Liabilities & Equity',
        rows: [
            { label: '2000 · Current Liabilities', amount: '₹6.8L', head: true },
            { label: '2010 · TDS Payable', amount: '₹1.4L' },
            { label: '2020 · Vendor Payables', amount: '₹4.2L' },
            { label: '2030 · Wallet Liability (User Balances)', amount: '₹1.2L' },
        ],
    },
    income: {
        title: 'Income',
        rows: [
            { label: '4000 · Fee Income', amount: '₹2.41 Cr', head: true },
            { label: '4010 · Tuition Fee', amount: '₹1.86 Cr' },
            { label: '4020 · Transport Fee', amount: '₹28.4L' },
            { label: '4030 · Other Income (Canteen, Donations)', amount: '₹26.6L' },
        ],
    },
    expenses: {
        title: 'Expenses',
        rows: [
            { label: '5000 · Salary Expense', amount: '₹1.92 Cr', head: true },
            { label: '5010 · Teaching Staff', amount: '₹1.68 Cr' },
            { label: '5020 · Non-Teaching / Transport Staff', amount: '₹24L' },
            { label: '5100 · Operational Expense', amount: '₹38.4L', head: true },
            { label: '5110 · Transport (Fuel, Service)', amount: '₹18.6L' },
            { label: '5120 · Utilities & Maintenance', amount: '₹19.8L' },
        ],
    },
}

export const JOURNAL_LEDGER_ACCOUNTS = [
    'Bank — SBI Current A/c',
    'Cash in Hand',
    'Fee Income — Tuition',
    'Fee Income — Transport',
    'Salary Expense — Teaching',
    'Transport Expense — Fuel',
    'Utilities & Maintenance',
    'Student Fee Receivable',
    'Vendor Payables',
    'Donations & Grants',
]

export const DEFAULT_JOURNAL_VOUCHER_FORM = {
    date: '',
    voucherNo: '',
    narration: '',
    debitAccount: '',
    creditAccount: '',
    amount: '',
    remarks: '',
}

export const generateJournalVoucherNo = () => `JV-2026-${Date.now().toString().slice(-4)}`

export const JOURNAL_VOUCHERS_REGISTER = [
    {
        id: 'JV-001',
        voucherNo: 'JV-2026-0884',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        description: 'Fee receipt — Arun Raj (10-A)',
        debit: 'Bank — SBI Current A/c · ₹12,400',
        credit: 'Fee Income — Tuition · ₹12,400',
        debitAccount: 'Bank — SBI Current A/c',
        creditAccount: 'Fee Income — Tuition',
        amount: '₹12,400',
        status: 'Posted',
        createdBy: 'Finance Manager',
    },
    {
        id: 'JV-002',
        voucherNo: 'JV-2026-0881',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        description: 'June salary disbursal — 84 teaching staff',
        debit: 'Salary Expense — Teaching · ₹14,80,000',
        credit: 'Bank — SBI Current A/c · ₹14,80,000',
        debitAccount: 'Salary Expense — Teaching',
        creditAccount: 'Bank — SBI Current A/c',
        amount: '₹14,80,000',
        status: 'Posted',
        createdBy: 'Finance Manager',
    },
    {
        id: 'JV-003',
        voucherNo: 'JV-2026-0878',
        date: '24 Jun 2026',
        dateIso: '2026-06-24',
        description: 'Transport service accrual — Sri Balaji Motors',
        debit: 'Transport Expense — Fuel · ₹6,200',
        credit: 'Vendor Payables · ₹6,200',
        debitAccount: 'Transport Expense — Fuel',
        creditAccount: 'Vendor Payables',
        amount: '₹6,200',
        status: 'Draft',
        createdBy: 'K. Anand',
    },
    {
        id: 'JV-004',
        voucherNo: 'JV-2026-0876',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        description: 'Electricity expense accrual — TANGEDCO',
        debit: 'Utilities & Maintenance · ₹84,000',
        credit: 'Vendor Payables · ₹84,000',
        debitAccount: 'Utilities & Maintenance',
        creditAccount: 'Vendor Payables',
        amount: '₹84,000',
        status: 'Pending Approval',
        createdBy: 'K. Anand',
    },
    {
        id: 'JV-005',
        voucherNo: 'JV-2026-0875',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        description: 'Cash deposit to bank — daily collection',
        debit: 'Bank — SBI Current A/c · ₹1,20,000',
        credit: 'Cash in Hand · ₹1,20,000',
        debitAccount: 'Bank — SBI Current A/c',
        creditAccount: 'Cash in Hand',
        amount: '₹1,20,000',
        status: 'Posted',
        createdBy: 'R. Meenakshi',
    },
    {
        id: 'JV-006',
        voucherNo: 'JV-2026-0872',
        date: '22 Jun 2026',
        dateIso: '2026-06-22',
        description: 'Fee receivable correction — Priya M.',
        debit: 'Student Fee Receivable · ₹2,400',
        credit: 'Fee Income — Tuition · ₹2,400',
        debitAccount: 'Student Fee Receivable',
        creditAccount: 'Fee Income — Tuition',
        amount: '₹2,400',
        status: 'Draft',
        createdBy: 'Finance Manager',
    },
    {
        id: 'JV-007',
        voucherNo: 'JV-2026-0870',
        date: '21 Jun 2026',
        dateIso: '2026-06-21',
        description: 'Donation recognition — Alumni Trust',
        debit: 'Bank — SBI Current A/c · ₹50,000',
        credit: 'Donations & Grants · ₹50,000',
        debitAccount: 'Bank — SBI Current A/c',
        creditAccount: 'Donations & Grants',
        amount: '₹50,000',
        status: 'Pending Approval',
        createdBy: 'Finance Manager',
    },
]

/** @deprecated Use JOURNAL_VOUCHERS_REGISTER */
export const JOURNAL_VOUCHERS = [
    {
        id: 'JV-2026-0884',
        type: 'Receipt',
        date: '26 Jun',
        narration: 'Fee receipt — Arun Raj',
        amount: '₹12,400',
        status: 'Posted',
    },
    {
        id: 'JV-2026-0881',
        type: 'Payment',
        date: '25 Jun',
        narration: 'June salary disbursal',
        amount: '₹14,80,000',
        status: 'Posted',
    },
    {
        id: 'JV-2026-0878',
        type: 'Journal',
        date: '24 Jun',
        narration: 'Transport service accrual',
        amount: '₹6,200',
        status: 'Draft',
    },
    {
        id: 'JV-2026-0875',
        type: 'Contra',
        date: '23 Jun',
        narration: 'Cash deposit to bank',
        amount: '₹1,20,000',
        status: 'Posted',
    },
]

export const BANK_RECONCILIATION_BANKS = ['All Banks', 'SBI Current A/c', 'HDFC Savings A/c']

export const BANK_RECONCILIATION_REGISTER = [
    {
        id: 'BRC-001',
        date: '26 Jun',
        dateIso: '2026-06-26',
        voucher: 'BB-2026-0042',
        erpAmount: '₹4,12,000',
        bankAmount: '₹4,12,000',
        difference: '₹0',
        status: 'Matched',
        bank: 'SBI Current A/c',
        detail: {
            erpEntry: {
                date: '26 Jun 2026',
                voucher: 'BB-2026-0042',
                description: 'NEFT — fee collections batch',
                amount: '₹4,12,000',
            },
            bankEntry: {
                date: '26 Jun 2026',
                reference: 'NEFT/HDFC/412000',
                description: 'NEFT CREDIT — fee collections',
                amount: '₹4,12,000',
            },
            suggestions: [],
        },
    },
    {
        id: 'BRC-002',
        date: '25 Jun',
        dateIso: '2026-06-25',
        voucher: 'BB-2026-0038',
        erpAmount: '₹14,80,000',
        bankAmount: '₹14,80,000',
        difference: '₹0',
        status: 'Matched',
        bank: 'SBI Current A/c',
        detail: {
            erpEntry: {
                date: '25 Jun 2026',
                voucher: 'BB-2026-0038',
                description: 'Salary disbursal — June',
                amount: '₹14,80,000',
            },
            bankEntry: {
                date: '25 Jun 2026',
                reference: 'NEFT/SAL/JUN2026',
                description: 'BULK NEFT — staff salaries',
                amount: '₹14,80,000',
            },
            suggestions: [],
        },
    },
    {
        id: 'BRC-003',
        date: '23 Jun',
        dateIso: '2026-06-23',
        voucher: '—',
        erpAmount: '—',
        bankAmount: '₹450',
        difference: '₹450',
        status: 'Unmatched',
        bank: 'SBI Current A/c',
        detail: {
            erpEntry: null,
            bankEntry: {
                date: '23 Jun 2026',
                reference: 'CHG/Q2/2026',
                description: 'Bank charges — quarterly maintenance',
                amount: '₹450',
            },
            suggestions: [
                {
                    id: 'sug-brc-003-1',
                    label: 'Bank Charges — Quarterly (JV-2026-0118)',
                    confidence: 'High',
                    erpAmount: '₹450',
                    bankAmount: '₹450',
                    erpVoucher: 'JV-2026-0118',
                    erpDescription: 'Bank charges — Q2 maintenance',
                },
            ],
        },
    },
    {
        id: 'BRC-004',
        date: '21 Jun',
        dateIso: '2026-06-21',
        voucher: '—',
        erpAmount: '—',
        bankAmount: '₹1,250',
        difference: '₹1,250',
        status: 'Unmatched',
        bank: 'SBI Current A/c',
        detail: {
            erpEntry: null,
            bankEntry: {
                date: '21 Jun 2026',
                reference: 'INT/CR/JUN2026',
                description: 'Interest credited on savings balance',
                amount: '₹1,250',
            },
            suggestions: [
                {
                    id: 'sug-brc-004-1',
                    label: 'Interest Income — SBI A/c (JV-2026-0104)',
                    confidence: 'High',
                    erpAmount: '₹1,250',
                    bankAmount: '₹1,250',
                    erpVoucher: 'JV-2026-0104',
                    erpDescription: 'Interest income — SBI current account',
                },
            ],
        },
    },
    {
        id: 'BRC-005',
        date: '18 Jun',
        dateIso: '2026-06-18',
        voucher: 'CHQ-004821',
        erpAmount: '₹22,000',
        bankAmount: '—',
        difference: '₹22,000',
        status: 'Pending Reconciliation',
        bank: 'SBI Current A/c',
        detail: {
            erpEntry: {
                date: '18 Jun 2026',
                voucher: 'CHQ-004821',
                description: 'Cheque issued — Anand Auto Works (maintenance)',
                amount: '₹22,000',
            },
            bankEntry: null,
            suggestions: [
                {
                    id: 'sug-brc-005-1',
                    label: 'Cheque #004821 clearing — expected 20 Jun',
                    confidence: 'Medium',
                    erpAmount: '₹22,000',
                    bankAmount: '₹22,000',
                    erpVoucher: 'CHQ-004821',
                    erpDescription: 'Cheque clearing — Anand Auto Works',
                },
            ],
        },
    },
    {
        id: 'BRC-006',
        date: '17 Jun',
        dateIso: '2026-06-17',
        voucher: 'BB-2026-0031',
        erpAmount: '₹85,000',
        bankAmount: '₹84,500',
        difference: '₹500',
        status: 'Unmatched',
        bank: 'HDFC Savings A/c',
        detail: {
            erpEntry: {
                date: '17 Jun 2026',
                voucher: 'BB-2026-0031',
                description: 'Vendor payment — stationery supplies',
                amount: '₹85,000',
            },
            bankEntry: {
                date: '17 Jun 2026',
                reference: 'NEFT/VND/84500',
                description: 'NEFT DEBIT — stationery vendor',
                amount: '₹84,500',
            },
            suggestions: [
                {
                    id: 'sug-brc-006-1',
                    label: 'Partial payment — ₹500 bank charges deducted',
                    confidence: 'Medium',
                    erpAmount: '₹85,000',
                    bankAmount: '₹84,500',
                    erpVoucher: 'BB-2026-0031',
                    erpDescription: 'Vendor payment net of bank charges',
                },
            ],
        },
    },
]

/** @deprecated Use BANK_RECONCILIATION_REGISTER */
export const RECONCILIATION_ITEMS = BANK_RECONCILIATION_REGISTER

export const FINANCIAL_STATEMENT_DEPARTMENTS = ['All Departments', 'Fees', 'Transport', 'Payroll', 'Admin', 'Facilities', 'Accounting']

export const FINANCIAL_STATEMENT_CAMPUSES = ['All Campuses', 'Main Campus', 'North Campus', 'East Campus', 'West Campus', 'South Campus']

export const FINANCIAL_STATEMENT_CARDS = [
    {
        id: 'trial-balance',
        label: 'Trial Balance',
        description: 'Debit and credit balances by account',
        iconTone: 'info',
    },
    {
        id: 'profit-loss',
        label: 'Profit & Loss Statement',
        description: 'Income, expenses, and net result',
        iconTone: 'success',
    },
    {
        id: 'balance-sheet',
        label: 'Balance Sheet',
        description: 'Assets, liabilities, and equity',
        iconTone: 'info',
    },
    {
        id: 'cash-flow',
        label: 'Cash Flow Statement',
        description: 'Operating, investing, and financing flows',
        iconTone: 'warning',
    },
]

export const TRIAL_BALANCE_REGISTER = [
    { id: 'TB-001', account: 'Cash in Hand', debit: '₹2,45,000', credit: '—', department: 'Accounting', campus: 'Main Campus' },
    { id: 'TB-002', account: 'Bank — SBI Current A/c', debit: '₹52,80,000', credit: '—', department: 'Accounting', campus: 'Main Campus' },
    { id: 'TB-003', account: 'Bank — HDFC Savings A/c', debit: '₹8,40,000', credit: '—', department: 'Accounting', campus: 'Main Campus' },
    { id: 'TB-004', account: 'Fee Income — Tuition', debit: '—', credit: '₹1,92,00,000', department: 'Fees', campus: 'Main Campus' },
    { id: 'TB-005', account: 'Fee Income — Transport', debit: '—', credit: '₹49,00,000', department: 'Fees', campus: 'North Campus' },
    { id: 'TB-006', account: 'Other Income', debit: '—', credit: '₹9,00,000', department: 'Admin', campus: 'Main Campus' },
    { id: 'TB-007', account: 'Salary Expense — Teaching', debit: '₹1,44,00,000', credit: '—', department: 'Payroll', campus: 'Main Campus' },
    { id: 'TB-008', account: 'Salary Expense — Non-Teaching', debit: '₹48,00,000', credit: '—', department: 'Payroll', campus: 'East Campus' },
    { id: 'TB-009', account: 'Transport Expense — Fuel', debit: '₹18,40,000', credit: '—', department: 'Transport', campus: 'North Campus' },
    { id: 'TB-010', account: 'Utilities & Maintenance', debit: '₹12,00,000', credit: '—', department: 'Facilities', campus: 'Main Campus' },
    { id: 'TB-011', account: 'Donations & Grants', debit: '—', credit: '₹6,50,000', department: 'Admin', campus: 'West Campus' },
    { id: 'TB-012', account: 'Accounts Payable', debit: '—', credit: '₹4,20,000', department: 'Accounting', campus: 'Main Campus' },
    { id: 'TB-013', account: 'Prepaid Expenses', debit: '₹3,15,000', credit: '—', department: 'Facilities', campus: 'South Campus' },
    { id: 'TB-014', account: 'Accumulated Depreciation', debit: '—', credit: '₹22,00,000', department: 'Facilities', campus: 'Main Campus' },
]

export const PROFIT_LOSS_STATEMENT = [
    { type: 'section', label: 'Income' },
    { type: 'item', label: 'Fee Income — Tuition', amount: '1,92,00,000', indent: true },
    { type: 'item', label: 'Fee Income — Transport', amount: '49,00,000', indent: true },
    { type: 'item', label: 'Other Income', amount: '9,00,000', indent: true },
    { type: 'total', label: 'Total Income', amount: '2,50,00,000' },
    { type: 'section', label: 'Expenses' },
    { type: 'item', label: 'Salary Expense — Teaching', amount: '1,44,00,000', indent: true },
    { type: 'item', label: 'Salary Expense — Non-Teaching', amount: '48,00,000', indent: true },
    { type: 'item', label: 'Transport Expense', amount: '18,40,000', indent: true },
    { type: 'item', label: 'Utilities & Maintenance', amount: '12,00,000', indent: true },
    { type: 'item', label: 'Administrative Expense', amount: '8,00,000', indent: true },
    { type: 'total', label: 'Total Expenses', amount: '2,30,40,000' },
    { type: 'net', label: 'Net Profit / Loss', amount: '19,60,000', profit: true },
]

export const BALANCE_SHEET_STATEMENT = [
    { type: 'section', label: 'Assets' },
    { type: 'item', label: 'Cash in Hand', amount: '2,45,000', indent: true },
    { type: 'item', label: 'Bank — SBI Current A/c', amount: '52,80,000', indent: true },
    { type: 'item', label: 'Bank — HDFC Savings A/c', amount: '8,40,000', indent: true },
    { type: 'item', label: 'Accounts Receivable', amount: '6,20,000', indent: true },
    { type: 'item', label: 'Prepaid Expenses', amount: '3,15,000', indent: true },
    { type: 'item', label: 'Fixed Assets (Net)', amount: '1,18,00,000', indent: true },
    { type: 'total', label: 'Total Assets', amount: '1,91,00,000' },
    { type: 'section', label: 'Liabilities' },
    { type: 'item', label: 'Accounts Payable', amount: '4,20,000', indent: true },
    { type: 'item', label: 'Salaries Payable', amount: '12,80,000', indent: true },
    { type: 'item', label: 'Fee Advances Received', amount: '8,40,000', indent: true },
    { type: 'item', label: 'Long-term Borrowings', amount: '45,00,000', indent: true },
    { type: 'total', label: 'Total Liabilities', amount: '70,40,000' },
    { type: 'section', label: 'Equity' },
    { type: 'item', label: 'Corpus Fund', amount: '80,00,000', indent: true },
    { type: 'item', label: 'General Reserve', amount: '21,00,000', indent: true },
    { type: 'item', label: 'Surplus for the Year', amount: '19,60,000', indent: true },
    { type: 'total', label: 'Total Equity', amount: '1,20,60,000' },
]

export const CASH_FLOW_STATEMENT = [
    { type: 'section', label: 'Operating Activities' },
    { type: 'item', label: 'Fee collections received', amount: '2,38,00,000', indent: true },
    { type: 'item', label: 'Salary and wage payments', amount: '(1,92,00,000)', indent: true },
    { type: 'item', label: 'Transport and utilities paid', amount: '(30,40,000)', indent: true },
    { type: 'item', label: 'Other operating payments', amount: '(8,00,000)', indent: true },
    { type: 'total', label: 'Net Cash from Operating Activities', amount: '7,60,000' },
    { type: 'section', label: 'Investing Activities' },
    { type: 'item', label: 'Purchase of lab equipment', amount: '(12,00,000)', indent: true },
    { type: 'item', label: 'Sale of old furniture', amount: '1,50,000', indent: true },
    { type: 'total', label: 'Net Cash from Investing Activities', amount: '(10,50,000)' },
    { type: 'section', label: 'Financing Activities' },
    { type: 'item', label: 'Loan repayment — term loan', amount: '(5,00,000)', indent: true },
    { type: 'item', label: 'Donations received', amount: '6,50,000', indent: true },
    { type: 'total', label: 'Net Cash from Financing Activities', amount: '1,50,000' },
    { type: 'net', label: 'Net Increase in Cash', amount: '(1,40,000)', profit: false },
]

/** @deprecated Use FINANCIAL_STATEMENT_CARDS */
export const FINANCIAL_STATEMENT_TYPES = ['Income & Expenditure', 'Balance Sheet', 'Receipts & Payments']

/** @deprecated Use PROFIT_LOSS_STATEMENT */
export const INCOME_EXPENDITURE = PROFIT_LOSS_STATEMENT

export const DAY_BOOK_PAYMENT_METHODS = ['All Methods', 'Cash', 'Cheque', 'DD', 'NEFT (Manual)', 'Petty Cash']
export const DAY_BOOK_TRANSACTION_TYPES = ['All Types', 'Income', 'Expense']
export const DAY_BOOK_CHANNELS = ['All Channels', 'Cash', 'Bank']
export const DAY_BOOK_STATUS_FILTERS = ['All Status', 'Posted', 'Draft', 'Pending Verification', 'Pending Clearance']
export const DAY_BOOK_DEPARTMENTS = ['All Departments', 'Fees', 'Transport', 'Admin', 'Facilities', 'Payroll', 'General']
export const DAY_BOOK_LEDGER_ACCOUNTS = [
    'Cash in Hand',
    'Fee Income — Tuition',
    'Fee Income — Transport',
    'Transport Expense — Fuel',
    'Salary Expense — Teaching',
    'Utilities & Maintenance',
    'Petty Cash',
    'Donations & Grants',
]
export const DAY_BOOK_ENTRY_PAYMENT_METHODS = ['Cash', 'Cheque', 'DD', 'NEFT (Manual)', 'Petty Cash']
export const DAY_BOOK_ENTRY_TRANSACTION_TYPES = ['Income', 'Expense']

export const DEFAULT_OFFLINE_ENTRY_FORM = {
    date: '',
    voucherNo: '',
    ledgerAccount: '',
    transactionType: 'Income',
    paymentMethod: 'Cash',
    amount: '',
    description: '',
    remarks: '',
}

export const DAY_BOOK_OPENING_BALANCE = 284000

export const DAY_BOOK_REGISTER = [
    {
        id: 'DB-001',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0142',
        transactionType: 'Income',
        ledgerHead: 'Fee Income — Tuition',
        description: 'Term fee — Arun Raj (10-A)',
        paymentMethod: 'Cash',
        debit: '₹12,400',
        credit: '—',
        balance: '₹2,96,400',
        enteredBy: 'R. Meenakshi',
        status: 'Posted',
        department: 'Fees',
    },
    {
        id: 'DB-002',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0141',
        transactionType: 'Income',
        ledgerHead: 'Fee Income — Transport',
        description: 'Transport fee — Route 4 collection',
        paymentMethod: 'Cash',
        debit: '₹1,800',
        credit: '—',
        balance: '₹2,98,200',
        enteredBy: 'R. Meenakshi',
        status: 'Posted',
        department: 'Transport',
    },
    {
        id: 'DB-003',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0140',
        transactionType: 'Expense',
        ledgerHead: 'Petty Cash',
        description: 'Stationery purchase — front office',
        paymentMethod: 'Petty Cash',
        debit: '—',
        credit: '₹2,400',
        balance: '₹2,95,800',
        enteredBy: 'K. Anand',
        status: 'Posted',
        department: 'Admin',
    },
    {
        id: 'DB-004',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0139',
        transactionType: 'Income',
        ledgerHead: 'Fee Income — Tuition',
        description: 'Term fee — Priya M. (9-B)',
        paymentMethod: 'Cheque',
        debit: '₹11,600',
        credit: '—',
        balance: '₹2,98,200',
        enteredBy: 'R. Meenakshi',
        status: 'Pending Verification',
        department: 'Fees',
    },
    {
        id: 'DB-005',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0138',
        transactionType: 'Expense',
        ledgerHead: 'Transport Expense — Fuel',
        description: 'Driver advance — Route 7 (cash)',
        paymentMethod: 'Cash',
        debit: '—',
        credit: '₹10,000',
        balance: '₹2,86,600',
        enteredBy: 'K. Anand',
        status: 'Posted',
        department: 'Transport',
    },
    {
        id: 'DB-006',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0137',
        transactionType: 'Income',
        ledgerHead: 'Donations & Grants',
        description: 'Alumni donation — cheque deposit',
        paymentMethod: 'Cheque',
        debit: '₹50,000',
        credit: '—',
        balance: '₹3,36,600',
        enteredBy: 'Finance Manager',
        status: 'Draft',
        department: 'General',
    },
    {
        id: 'DB-007',
        date: '26 Jun 2026',
        voucherNo: 'OB-2026-0136',
        transactionType: 'Expense',
        ledgerHead: 'Utilities & Maintenance',
        description: 'AC repair advance — Facilities',
        paymentMethod: 'NEFT (Manual)',
        debit: '—',
        credit: '₹8,600',
        balance: '₹3,28,000',
        enteredBy: 'K. Anand',
        status: 'Posted',
        department: 'Facilities',
    },
]

export const dayBookTransactionTypeBadgeColor = {
    Income: 'bg-[#4CAF5033] text-[#4CAF50]',
    Expense: 'bg-[#FF572233] text-[#FF5722]',
}

export const dayBookStatusBadgeColor = {
    Posted: 'bg-[#4CAF5033] text-[#4CAF50]',
    Draft: 'bg-[#FF980033] text-[#FF9800]',
    'Pending Verification': 'bg-[#515DEF33] text-[#515DEF]',
    'Pending Clearance': 'bg-[#FF980033] text-[#FF9800]',
    DRAFT: 'bg-[#FF980033] text-[#FF9800]',
}

export const parseRupeeAmount = (value) => Number(String(value).replace(/[₹,\s]/g, '')) || 0

export const formatRupeeAmount = (amount) => `₹${amount.toLocaleString('en-IN')}`

export const generateOfflineVoucherNo = () => {
    const suffix = Date.now().toString().slice(-4)
    return `OB-2026-${suffix}`
}

export const ONLINE_BOOK_DATE_RANGES = ['Today', 'This Week', 'This Month', 'Custom Range']
export const ONLINE_BOOK_GATEWAYS = ['All Gateways', 'Razorpay', 'PayU', 'CCAvenue', 'Net Banking Portal']
export const ONLINE_BOOK_PAYMENT_METHODS = ['All Methods', 'UPI', 'Card', 'Net Banking', 'Wallet']
export const ONLINE_BOOK_STATUSES = ['All Status', 'Successful', 'Processing', 'Failed', 'Refunded']

export const ONLINE_BOOK_REGISTER = [
    {
        id: 'OLT-001',
        dateTime: '26 Jun 2026, 10:32am',
        dateIso: '2026-06-26',
        transactionId: 'TXN-8842102',
        party: 'Arun Raj',
        transactionType: 'Income',
        paymentGateway: 'Razorpay',
        paymentMethod: 'UPI',
        amount: '₹12,400',
        bankReference: 'UPI/ARUNRAJ@okicici/8842102',
        status: 'Successful',
        detail: {
            gatewayResponse: 'payment.captured — signature verified',
            referenceNumber: 'RZP-8842102',
            paymentDetails: {
                orderId: 'ORD-FEE-1022',
                feeHead: 'Tuition Fee — Term 1',
                paidBy: 'Parent — S. Rajan',
                settlementDate: '26 Jun 2026',
            },
            refundHistory: [],
            remarks: 'Auto-posted to fee ledger on settlement.',
        },
    },
    {
        id: 'OLT-002',
        dateTime: '26 Jun 2026, 9:48am',
        dateIso: '2026-06-26',
        transactionId: 'TXN-8842098',
        party: 'Parent — Kumar S.',
        transactionType: 'Income',
        paymentGateway: 'Razorpay',
        paymentMethod: 'UPI',
        amount: '₹2,000',
        bankReference: 'UPI/KUMARS@paytm/8842098',
        status: 'Successful',
        detail: {
            gatewayResponse: 'payment.captured — signature verified',
            referenceNumber: 'RZP-8842098',
            paymentDetails: {
                orderId: 'ORD-WLT-0312',
                feeHead: 'Wallet Recharge',
                paidBy: 'Parent — Kumar S.',
                settlementDate: '26 Jun 2026',
            },
            refundHistory: [],
            remarks: 'Credited to student wallet WLT-10391.',
        },
    },
    {
        id: 'OLT-003',
        dateTime: '25 Jun 2026, 4:15pm',
        dateIso: '2026-06-25',
        transactionId: 'TXN-8842055',
        party: 'Alumni Trust',
        transactionType: 'Income',
        paymentGateway: 'Net Banking Portal',
        paymentMethod: 'Net Banking',
        amount: '₹50,000',
        bankReference: 'NEFT/SBIN0001234/4421901',
        status: 'Processing',
        detail: {
            gatewayResponse: 'payment.authorized — awaiting bank confirmation',
            referenceNumber: 'NBK-4421901',
            paymentDetails: {
                orderId: 'ORD-DON-0044',
                feeHead: 'Donation',
                paidBy: 'Alumni Trust',
                settlementDate: 'Pending',
            },
            refundHistory: [],
            remarks: 'Donation receipt to be generated after clearance.',
        },
    },
    {
        id: 'OLT-004',
        dateTime: '25 Jun 2026, 11:20am',
        dateIso: '2026-06-25',
        transactionId: 'TXN-8841988',
        party: 'Sowmiya M.',
        transactionType: 'Income',
        paymentGateway: 'Razorpay',
        paymentMethod: 'Card',
        amount: '₹10,800',
        bankReference: 'CARD/XXXX-4821/8841988',
        status: 'Successful',
        detail: {
            gatewayResponse: 'payment.captured — 3DS authenticated',
            referenceNumber: 'RZP-8841988',
            paymentDetails: {
                orderId: 'ORD-FEE-1020',
                feeHead: 'Tuition Fee — Term 1',
                paidBy: 'Parent — M. Sowmiya',
                settlementDate: '25 Jun 2026',
            },
            refundHistory: [],
            remarks: 'Card settlement T+1.',
        },
    },
    {
        id: 'OLT-005',
        dateTime: '24 Jun 2026, 2:40pm',
        dateIso: '2026-06-24',
        transactionId: 'TXN-8841920',
        party: 'R. Balakrishnan',
        transactionType: 'Income',
        paymentGateway: 'Razorpay',
        paymentMethod: 'Card',
        amount: '₹8,400',
        bankReference: '—',
        status: 'Failed',
        detail: {
            gatewayResponse: 'payment.failed — insufficient_funds',
            referenceNumber: 'RZP-8841920',
            paymentDetails: {
                orderId: 'ORD-FEE-1018',
                feeHead: 'Tuition Fee — Term 1',
                paidBy: 'Parent — R. Balakrishnan',
                settlementDate: '—',
            },
            refundHistory: [],
            remarks: 'Parent notified via SMS. Retry link sent.',
        },
    },
    {
        id: 'OLT-006',
        dateTime: '24 Jun 2026, 9:10am',
        dateIso: '2026-06-24',
        transactionId: 'TXN-8841888',
        party: 'Sri Balaji Motors',
        transactionType: 'Expense',
        paymentGateway: 'Net Banking Portal',
        paymentMethod: 'Net Banking',
        amount: '₹6,200',
        bankReference: 'NEFT/ICIC0005678/8841888',
        status: 'Successful',
        detail: {
            gatewayResponse: 'payout.processed — vendor disbursement',
            referenceNumber: 'PAY-8841888',
            paymentDetails: {
                orderId: 'ORD-VND-0624',
                feeHead: 'Transport — Vehicle Service',
                paidBy: 'Finance Manager',
                settlementDate: '24 Jun 2026',
            },
            refundHistory: [],
            remarks: 'Linked to approval APR-1135.',
        },
    },
    {
        id: 'OLT-007',
        dateTime: '23 Jun 2026, 3:55pm',
        dateIso: '2026-06-23',
        transactionId: 'TXN-8841801',
        party: 'Priya M.',
        transactionType: 'Income',
        paymentGateway: 'PayU',
        paymentMethod: 'UPI',
        amount: '₹11,600',
        bankReference: 'UPI/PRIYAM@ybl/8841801',
        status: 'Refunded',
        detail: {
            gatewayResponse: 'refund.processed — duplicate payment',
            referenceNumber: 'PAYU-8841801',
            paymentDetails: {
                orderId: 'ORD-FEE-1015',
                feeHead: 'Tuition Fee — Term 1',
                paidBy: 'Parent — M. Priya',
                settlementDate: '23 Jun 2026',
            },
            refundHistory: [
                { date: '24 Jun 2026', amount: '₹11,600', reason: 'Duplicate payment', status: 'Completed' },
            ],
            remarks: 'Original receipt RCP-2026-1015 voided.',
        },
    },
]

export const SYNC_TRANSACTION_TEMPLATE = {
    dateTime: () => {
        const now = new Date()
        return now.toLocaleString('en-IN', {
            day: '2-digit',
            month: 'short',
            year: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
            hour12: true,
        })
    },
    dateIso: () => new Date().toISOString().slice(0, 10),
    transactionId: () => `TXN-${Date.now().toString().slice(-7)}`,
    party: 'Synced Payment',
    transactionType: 'Income',
    paymentGateway: 'Razorpay',
    paymentMethod: 'UPI',
    amount: '₹4,800',
    bankReference: 'UPI/SYNC@razorpay/auto',
    status: 'Successful',
    detail: {
        gatewayResponse: 'payment.captured — synced from gateway',
        referenceNumber: () => `RZP-${Date.now().toString().slice(-7)}`,
        paymentDetails: {
            orderId: 'ORD-SYNC-AUTO',
            feeHead: 'Fee Payment',
            paidBy: 'Gateway Sync',
            settlementDate: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
        },
        refundHistory: [],
        remarks: 'Imported via Sync Transactions.',
    },
}

export const onlineBookTransactionTypeBadgeColor = {
    Income: 'bg-[#4CAF5033] text-[#4CAF50]',
    Expense: 'bg-[#FF572233] text-[#FF5722]',
}

export const onlineBookStatusBadgeColor = {
    Successful: 'bg-[#4CAF5033] text-[#4CAF50]',
    Processing: 'bg-[#FF980033] text-[#FF9800]',
    Failed: 'bg-[#FF572233] text-[#FF5722]',
    Refunded: 'bg-[#515DEF33] text-[#515DEF]',
}

export const CASH_BOOK_OPENING_BALANCE = 284000

export const CASH_BOOK_ACCOUNTS = ['All Accounts', 'Cash in Hand', 'Petty Cash — Office', 'Petty Cash — Transport']
export const CASH_BOOK_TRANSACTION_TYPES = ['All Types', 'Receipt', 'Payment', 'Contra']

export const CASH_BOOK_REGISTER = [
    {
        id: 'CB-001',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucher: 'JV-2026-0883',
        description: 'Fee receipt — Priya M. (9-B)',
        receipt: '₹11,600',
        payment: '—',
        balance: '₹2,95,600',
        cashAccount: 'Cash in Hand',
        transactionType: 'Receipt',
    },
    {
        id: 'CB-002',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucher: 'JV-2026-0881',
        description: 'Transport fee — Route 4 collection',
        receipt: '₹1,800',
        payment: '—',
        balance: '₹2,97,400',
        cashAccount: 'Cash in Hand',
        transactionType: 'Receipt',
    },
    {
        id: 'CB-003',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucher: 'JV-2026-0879',
        description: 'Stationery purchase — front office',
        receipt: '—',
        payment: '₹2,400',
        balance: '₹2,95,000',
        cashAccount: 'Petty Cash — Office',
        transactionType: 'Payment',
    },
    {
        id: 'CB-004',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        voucher: 'JV-2026-0878',
        description: 'Tea & snacks — staff meeting',
        receipt: '—',
        payment: '₹850',
        balance: '₹2,94,150',
        cashAccount: 'Petty Cash — Office',
        transactionType: 'Payment',
    },
    {
        id: 'CB-005',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucher: 'JV-2026-0876',
        description: 'Fee receipt — batch (8 students)',
        receipt: '₹55,200',
        payment: '—',
        balance: '₹2,94,950',
        cashAccount: 'Cash in Hand',
        transactionType: 'Receipt',
    },
    {
        id: 'CB-006',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucher: 'JV-2026-0874',
        description: 'Driver advance — Route 7',
        receipt: '—',
        payment: '₹10,000',
        balance: '₹2,39,750',
        cashAccount: 'Petty Cash — Transport',
        transactionType: 'Payment',
    },
    {
        id: 'CB-007',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        voucher: 'JV-2026-0873',
        description: 'Fuel reimbursement — Route 4',
        receipt: '—',
        payment: '₹3,150',
        balance: '₹2,36,600',
        cashAccount: 'Petty Cash — Transport',
        transactionType: 'Payment',
    },
    {
        id: 'CB-008',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        voucher: 'JV-2026-0875',
        description: 'Cash deposit to bank — daily collection',
        receipt: '—',
        payment: '₹1,20,000',
        balance: '₹3,40,200',
        cashAccount: 'Cash in Hand',
        transactionType: 'Contra',
    },
]

export const BANK_BOOK_OPENING_BALANCE = 5120000

export const BANK_BOOK_BANKS = ['All Banks', 'State Bank of India', 'ICICI Bank']
export const BANK_BOOK_ACCOUNTS = ['All Accounts', 'SBI Current A/c', 'ICICI Savings A/c']

export const BANK_BOOK_REGISTER = [
    {
        id: 'BB-001',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0884',
        deposit: '₹12,400',
        withdrawal: '—',
        balance: '₹51,32,400',
        referenceNumber: 'UPI/ARUNRAJ@okicici/8842102',
    },
    {
        id: 'BB-002',
        date: '26 Jun 2026',
        dateIso: '2026-06-26',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0882',
        deposit: '₹4,12,000',
        withdrawal: '—',
        balance: '₹52,44,400',
        referenceNumber: 'NEFT/BATCH-FEE-0626',
    },
    {
        id: 'BB-003',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0881',
        deposit: '—',
        withdrawal: '₹14,80,000',
        balance: '₹48,64,400',
        referenceNumber: 'NEFT/SALARY-JUN-2026',
    },
    {
        id: 'BB-004',
        date: '25 Jun 2026',
        dateIso: '2026-06-25',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0880',
        deposit: '₹1,86,400',
        withdrawal: '—',
        balance: '₹63,44,400',
        referenceNumber: 'RZP-SETTLEMENT-0625',
    },
    {
        id: 'BB-005',
        date: '24 Jun 2026',
        dateIso: '2026-06-24',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0878',
        deposit: '—',
        withdrawal: '₹6,200',
        balance: '₹63,38,200',
        referenceNumber: 'NEFT/SRI-BALAJI-MOTORS',
    },
    {
        id: 'BB-006',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0877',
        deposit: '—',
        withdrawal: '₹84,000',
        balance: '₹62,54,200',
        referenceNumber: 'TANGEDCO-BILL-JUN',
    },
    {
        id: 'BB-007',
        date: '23 Jun 2026',
        dateIso: '2026-06-23',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0875',
        deposit: '₹1,20,000',
        withdrawal: '—',
        balance: '₹52,80,000',
        referenceNumber: 'CASH-DEPOSIT-0623',
    },
    {
        id: 'BB-008',
        date: '22 Jun 2026',
        dateIso: '2026-06-22',
        bank: 'State Bank of India',
        accountNumber: '38472910482',
        account: 'SBI Current A/c',
        voucher: 'JV-2026-0874',
        deposit: '—',
        withdrawal: '₹22,000',
        balance: '₹51,60,000',
        referenceNumber: 'CHQ-004821',
    },
    {
        id: 'BB-009',
        date: '21 Jun 2026',
        dateIso: '2026-06-21',
        bank: 'ICICI Bank',
        accountNumber: '004812345678',
        account: 'ICICI Savings A/c',
        voucher: 'JV-2026-0872',
        deposit: '₹50,000',
        withdrawal: '—',
        balance: '₹2,50,000',
        referenceNumber: 'NEFT/ALUMNI-TRUST',
    },
    {
        id: 'BB-010',
        date: '20 Jun 2026',
        dateIso: '2026-06-20',
        bank: 'ICICI Bank',
        accountNumber: '004812345678',
        account: 'ICICI Savings A/c',
        voucher: 'JV-2026-0870',
        deposit: '—',
        withdrawal: '₹18,000',
        balance: '₹2,00,000',
        referenceNumber: 'NEFT/LAB-SUPPLIES',
    },
]

export const ledgerStatusBadgeColor = {
    Posted: 'bg-[#4CAF5033] text-[#4CAF50]',
    Draft: 'bg-[#FF980033] text-[#FF9800]',
}

export const voucherTypeBadgeColor = {
    Receipt: 'bg-[#515DEF33] text-[#515DEF]',
    Payment: 'bg-[#FF980033] text-[#FF9800]',
    Journal: 'bg-[#66708533] text-[#667085]',
    Contra: 'bg-[#66708533] text-[#667085]',
}

export const voucherStatusBadgeColor = {
    Posted: 'bg-[#4CAF5033] text-[#4CAF50]',
    Draft: 'bg-[#FF980033] text-[#FF9800]',
    'Pending Approval': 'bg-[#515DEF33] text-[#515DEF]',
}

export const reconciliationStatusBadgeColor = {
    Matched: 'bg-[#4CAF5033] text-[#4CAF50]',
    Unmatched: 'bg-[#FF980033] text-[#FF9800]',
    'Pending Reconciliation': 'bg-[#515DEF33] text-[#515DEF]',
}
