export const BUDGET_THRESHOLD = 75000

export const REQUEST_TYPES = ['Financial Request', 'General Request']

export const REQUESTS = [
    {
        requestId: 'JD-REQ-2026-001',
        requestType: 'Financial Request',
        requestDate: '08-06-2026',
        purpose: 'Canteen kitchen equipment upgrade',
        requestedAmount: 52000,
        requestedBy: 'Ravi Menon',
        department: 'Canteen',
        status: 'Pending',
        description: 'Replacement of two commercial food warmers and a stainless-steel prep counter for the main canteen.',
        exceedsBudget: false,
        items: '2 × Commercial food warmers, 1 × Prep counter, installation',
        remarks: 'Required before mid-term exam week service expansion.',
    },
    {
        requestId: 'JD-REQ-2026-002',
        requestType: 'General Request',
        requestDate: '09-06-2026',
        purpose: 'Extended canteen operating hours — exam week',
        requestedAmount: null,
        requestedBy: 'Ravi Menon',
        department: 'Canteen',
        status: 'Pending',
        description: 'Request to operate canteen from 6:30 AM to 6:00 PM during exam week for staff and late-session students.',
        exceedsBudget: false,
        items: null,
        remarks: 'Needs Joint Director approval for staff overtime coordination.',
        generalDetails: 'Duration: 12-06-2026 to 20-06-2026 · Affected staff: 8 canteen workers',
    },
    {
        requestId: 'JD-REQ-2026-003',
        requestType: 'Financial Request',
        requestDate: '07-06-2026',
        purpose: 'Exam stationery bulk procurement',
        requestedAmount: 38000,
        requestedBy: 'Lakshmi Devi',
        department: 'Stationery Store',
        status: 'Pending',
        description: 'Bulk order for exam answer sheets, graph papers, and supplementary notebooks.',
        exceedsBudget: false,
        items: 'Answer sheets (5,000), graph sheets (2,000), notebooks (500)',
        remarks: 'Standard pre-exam procurement cycle.',
    },
    {
        requestId: 'JD-REQ-2026-004',
        requestType: 'Financial Request',
        requestDate: '06-06-2026',
        purpose: 'Block C lab network switch replacement',
        requestedAmount: 95000,
        requestedBy: 'Karthik Rajan',
        department: 'IT Support',
        status: 'Pending',
        description: 'Replace aging network switches in Block C computer labs to prevent connectivity failures during assessments.',
        exceedsBudget: true,
        items: '4 × Managed network switches, cabling kit, configuration support',
        remarks: 'Amount exceeds departmental threshold — escalated to Joint Director.',
    },
    {
        requestId: 'JD-REQ-2026-005',
        requestType: 'General Request',
        requestDate: '05-06-2026',
        purpose: 'After-hours server maintenance window',
        requestedAmount: null,
        requestedBy: 'Karthik Rajan',
        department: 'IT Support',
        status: 'Approved',
        description: 'Scheduled maintenance window for core server patching and backup verification.',
        exceedsBudget: false,
        items: null,
        remarks: 'Approved for Saturday 14-06-2026, 10:00 PM – 2:00 AM.',
        generalDetails: 'Maintenance window: 14-06-2026 · Systems: ERP server, backup cluster',
    },
    {
        requestId: 'JD-REQ-2026-006',
        requestType: 'Financial Request',
        requestDate: '04-06-2026',
        purpose: 'Route 5 bus tyre replacement',
        requestedAmount: 68000,
        requestedBy: 'Suresh Iyer',
        department: 'Transport',
        status: 'Rejected',
        description: 'Full tyre set replacement for Route 5 school bus after safety inspection findings.',
        exceedsBudget: false,
        items: '6 × Bus tyres, wheel alignment, safety inspection',
        remarks: 'Rejected — deferred to quarterly fleet maintenance budget.',
    },
    {
        requestId: 'JD-REQ-2026-007',
        requestType: 'General Request',
        requestDate: '10-06-2026',
        purpose: 'Temporary transport route diversion — road closure',
        requestedAmount: null,
        requestedBy: 'Suresh Iyer',
        department: 'Transport',
        status: 'Pending',
        description: 'Municipal road closure on Velachery Main Road requires temporary route diversion for Route 3 and Route 7.',
        exceedsBudget: false,
        items: null,
        remarks: 'Expected closure period: 15-06-2026 to 22-06-2026.',
        generalDetails: 'Routes affected: Route 3, Route 7 · Alternate pickup points to be notified to parents',
    },
    {
        requestId: 'JD-REQ-2026-008',
        requestType: 'Financial Request',
        requestDate: '03-06-2026',
        purpose: 'Housekeeping deep-cleaning supplies',
        requestedAmount: 24000,
        requestedBy: 'Anitha Nair',
        department: 'Housekeeping',
        status: 'Approved',
        description: 'Industrial cleaning agents, disinfectants, and floor-care supplies for exam-week deep cleaning.',
        exceedsBudget: false,
        items: 'Disinfectant (50 L), floor cleaner (30 L), microfiber mops (20)',
        remarks: 'Approved for zone-wise deep cleaning schedule.',
    },
    {
        requestId: 'JD-REQ-2026-009',
        requestType: 'General Request',
        requestDate: '02-06-2026',
        purpose: 'Cross-department escalation review meeting',
        requestedAmount: null,
        requestedBy: 'Meera Sharma',
        department: 'Joint Director Office',
        status: 'Pending',
        description: 'Schedule a joint review meeting with all department managers to discuss open escalations and pending requests.',
        exceedsBudget: false,
        items: null,
        remarks: 'Proposed date: 18-06-2026, 11:00 AM — Conference Hall B.',
        generalDetails: 'Attendees: All JD-managed department heads · Duration: 2 hours',
    },
]

export const statusBadgeColor = {
    Pending: 'bg-[#FF980033] text-[#FF9800]',
    Approved: 'bg-[#4CAF5033] text-[#4CAF50]',
    Rejected: 'bg-[#FF000033] text-[#FF0000]',
}

export const requestTypeBadgeColor = {
    'Financial Request': 'bg-[#515DEF33] text-[#515DEF]',
    'General Request': 'bg-[#2196F333] text-[#2196F3]',
}

export const formatAmount = (amount) => (amount != null ? `₹${amount.toLocaleString('en-IN')}` : '—')
