const BASE_ATTENDANCE = [
    { date: '02-06-2025', day: 'Monday', checkIn: '08:00 AM', checkOut: '04:30 PM', status: 'Present', remarks: 'On time' },
    { date: '03-06-2025', day: 'Tuesday', checkIn: '08:05 AM', checkOut: '04:25 PM', status: 'Present', remarks: 'Department meeting' },
    { date: '04-06-2025', day: 'Wednesday', checkIn: '—', checkOut: '—', status: 'Leave', remarks: 'Personal leave' },
    { date: '05-06-2025', day: 'Thursday', checkIn: '08:15 AM', checkOut: '04:35 PM', status: 'Present', remarks: 'Late by 15 minutes' },
    { date: '06-06-2025', day: 'Friday', checkIn: '08:00 AM', checkOut: '01:00 PM', status: 'Half Day', remarks: 'Official duty' },
    { date: '09-06-2025', day: 'Monday', checkIn: '08:02 AM', checkOut: '04:28 PM', status: 'Present', remarks: 'On time' },
    { date: '10-06-2025', day: 'Tuesday', checkIn: '—', checkOut: '—', status: 'Absent', remarks: 'Uninformed absence' },
]

export const attendanceBadgeColor = {
    Present: 'bg-[#4CAF5033] text-[#4CAF50]',
    Absent: 'bg-[#FF000033] text-[#FF0000]',
    Leave: 'bg-[#FF980033] text-[#FF9800]',
    'Half Day': 'bg-[#2196F333] text-[#2196F3]',
}

export const taskStatusBadgeColor = {
    Pending: 'bg-[#66708533] text-[#667085]',
    Completed: 'bg-[#4CAF5033] text-[#4CAF50]',
    'In Progress': 'bg-[#FF980033] text-[#FF9800]',
    'In Complete': 'bg-[#FF000033] text-[#FF0000]',
}

export const EMPLOYEE_PROFILES = {
    'canteen-manager': {
        roleTitle: 'Canteen Manager',
        profileLabel: 'Canteen Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'CM-1001',
            userId: 'USR-400002',
            firstName: 'Ravi',
            middleName: 'S.',
            lastName: 'Menon',
            gender: 'Male',
            dateOfBirth: '05-11-1982',
            bloodGroup: 'O+',
            height: '172 cm',
            weight: '75 kg',
            medicalHistory: 'Mild diabetes — diet controlled.',
            address: {
                address: '34, Food Street, T Nagar',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600017',
            },
            contact: {
                mobileNumber: '+91 98765 22233',
                alternativeNumber: '+91 91234 22233',
                email: 'ravi.menon@school.edu',
            },
            professionalInfo: {
                qualification: 'B.Sc. in Food Science & Nutrition',
                designation: 'Canteen Manager',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '14 Years',
                previousOrganization: 'Fresh Meals Catering Co.',
                joiningDate: '2012-03-01',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹42,000 / month',
                workShift: 'Morning (6:30 AM – 3:00 PM)',
                assignedCampus: 'Main Campus – Canteen Block',
                managedStaff: 'Canteen staff (12 members)',
                reportingTo: 'Joint Director',
            },
            account: {
                username: 'ravi.menon',
                password: 'Canteen@2025',
            },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'B.Sc. Food Science Certificate',
                experienceCertificate: 'Experience Letter – Fresh Meals',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'JD-T-001', title: 'Quarterly department review — Canteen', assignedDate: '10-06-2026', dueDate: '15-06-2026', status: 'In Progress' },
            { taskId: 'JD-T-009', title: 'Menu audit for exam week nutrition plan', assignedDate: '08-06-2026', dueDate: '12-06-2026', status: 'Pending' },
            { taskId: 'JD-T-010', title: 'Vendor payment reconciliation — May', assignedDate: '05-06-2026', dueDate: '08-06-2026', status: 'Completed' },
        ],
    },
    'store-manager': {
        roleTitle: 'Store Manager',
        profileLabel: 'Store Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'SM-1001',
            userId: 'USR-400003',
            firstName: 'Lakshmi',
            middleName: 'P.',
            lastName: 'Devi',
            gender: 'Female',
            dateOfBirth: '18-04-1988',
            bloodGroup: 'A+',
            height: '160 cm',
            weight: '62 kg',
            medicalHistory: 'None.',
            address: {
                address: '56, Stationery Lane, Velachery',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600042',
            },
            contact: {
                mobileNumber: '+91 98765 33344',
                alternativeNumber: '+91 91234 33344',
                email: 'lakshmi.devi@school.edu',
            },
            professionalInfo: {
                qualification: 'B.Com., Diploma in Inventory Management',
                designation: 'Stationery Store Manager',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '10 Years',
                previousOrganization: 'Scholar Supplies Pvt. Ltd.',
                joiningDate: '2016-08-20',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹38,000 / month',
                workShift: 'Morning (8:00 AM – 4:00 PM)',
                assignedCampus: 'Main Campus – Stationery Store',
                managedStaff: 'Store assistants (4 members)',
                reportingTo: 'Joint Director',
            },
            account: {
                username: 'lakshmi.devi',
                password: 'Store@2025',
            },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'B.Com. & Inventory Diploma',
                experienceCertificate: 'Experience Letter – Scholar Supplies',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'JD-T-002', title: 'Stationery stock audit before exam week', assignedDate: '09-06-2026', dueDate: '12-06-2026', status: 'Pending' },
            { taskId: 'JD-T-011', title: 'Reorder low-stock exam stationery items', assignedDate: '07-06-2026', dueDate: '10-06-2026', status: 'In Progress' },
            { taskId: 'JD-T-012', title: 'Monthly inventory valuation report', assignedDate: '01-06-2026', dueDate: '05-06-2026', status: 'Completed' },
        ],
    },
    'it-team-manager': {
        roleTitle: 'IT Team Manager',
        profileLabel: 'IT Team Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'ITM-1001',
            userId: 'USR-400004',
            firstName: 'Karthik',
            middleName: 'V.',
            lastName: 'Rajan',
            gender: 'Male',
            dateOfBirth: '30-09-1985',
            bloodGroup: 'B+',
            height: '175 cm',
            weight: '70 kg',
            medicalHistory: 'None.',
            address: {
                address: '89, Tech Park Road, OMR',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600096',
            },
            contact: {
                mobileNumber: '+91 98765 44455',
                alternativeNumber: '+91 91234 44455',
                email: 'karthik.rajan@school.edu',
            },
            professionalInfo: {
                qualification: 'B.Tech. in Computer Science, CCNA',
                designation: 'IT Support Team Manager',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '12 Years',
                previousOrganization: 'NetSecure Solutions',
                joiningDate: '2014-01-06',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹65,000 / month',
                workShift: 'Morning (8:00 AM – 5:00 PM)',
                assignedCampus: 'All campuses – IT infrastructure',
                managedStaff: 'IT support technicians (6 members)',
                reportingTo: 'Joint Director',
            },
            account: {
                username: 'karthik.rajan',
                password: 'ITMgr@2025',
            },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'B.Tech. & CCNA Certificates',
                experienceCertificate: 'Experience Letter – NetSecure',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'JD-T-003', title: 'Network readiness check — Block C labs', assignedDate: '09-06-2026', dueDate: '13-06-2026', status: 'In Progress' },
            { taskId: 'JD-T-013', title: 'Server backup verification — June cycle', assignedDate: '06-06-2026', dueDate: '09-06-2026', status: 'Pending' },
            { taskId: 'JD-T-014', title: 'Smart classroom device firmware update', assignedDate: '03-06-2026', dueDate: '07-06-2026', status: 'Completed' },
        ],
    },
    'transport-manager': {
        roleTitle: 'Transport Manager',
        profileLabel: 'Transport Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'TM-1001',
            userId: 'USR-400005',
            firstName: 'Suresh',
            middleName: 'B.',
            lastName: 'Iyer',
            gender: 'Male',
            dateOfBirth: '14-02-1978',
            bloodGroup: 'O+',
            height: '170 cm',
            weight: '72 kg',
            medicalHistory: 'Mild back pain — physiotherapy ongoing.',
            address: {
                address: '21, Bus Depot Road, Pallavaram',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600043',
            },
            contact: {
                mobileNumber: '+91 98765 55566',
                alternativeNumber: '+91 91234 55566',
                email: 'suresh.iyer@school.edu',
            },
            professionalInfo: {
                qualification: 'Diploma in Automobile Engineering',
                designation: 'Transport Manager',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '18 Years',
                previousOrganization: 'City Fleet Logistics',
                joiningDate: '2010-07-12',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹50,000 / month',
                workShift: 'Early (5:30 AM – 2:30 PM)',
                assignedCampus: 'Transport depot & all routes',
                managedStaff: 'Drivers & transport coordinators (18 members)',
                reportingTo: 'Joint Director',
            },
            account: {
                username: 'suresh.iyer',
                password: 'Transport@2025',
            },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'Automobile Engineering Diploma',
                experienceCertificate: 'Experience Letter – City Fleet',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'JD-T-005', title: 'Bus fleet maintenance compliance', assignedDate: '07-06-2026', dueDate: '14-06-2026', status: 'In Complete' },
            { taskId: 'JD-T-015', title: 'Route optimization review — new academic year', assignedDate: '05-06-2026', dueDate: '12-06-2026', status: 'In Progress' },
            { taskId: 'JD-T-016', title: 'Driver safety training attendance report', assignedDate: '02-06-2026', dueDate: '06-06-2026', status: 'Completed' },
        ],
    },
    'housekeeping-manager': {
        roleTitle: 'House Keeping Manager',
        profileLabel: 'House Keeping Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'HKM-1001',
            userId: 'USR-400006',
            firstName: 'Anitha',
            middleName: 'R.',
            lastName: 'Nair',
            gender: 'Female',
            dateOfBirth: '08-12-1983',
            bloodGroup: 'A+',
            height: '163 cm',
            weight: '60 kg',
            medicalHistory: 'None.',
            address: {
                address: '67, Green Campus Lane, Adyar',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600020',
            },
            contact: {
                mobileNumber: '+91 98765 66677',
                alternativeNumber: '+91 91234 66677',
                email: 'anitha.nair@school.edu',
            },
            professionalInfo: {
                qualification: 'Diploma in Hospitality Management',
                designation: 'Housekeeping Manager',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '15 Years',
                previousOrganization: 'CleanCare Facility Services',
                joiningDate: '2011-04-18',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹40,000 / month',
                workShift: 'Morning (7:00 AM – 3:30 PM)',
                assignedCampus: 'All campus zones & blocks',
                managedStaff: 'Housekeeping staff (25 members)',
                reportingTo: 'Joint Director',
            },
            account: {
                username: 'anitha.nair',
                password: 'HouseKeep@2025',
            },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'Hospitality Management Diploma',
                experienceCertificate: 'Experience Letter – CleanCare',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'JD-T-004', title: 'Deep cleaning schedule — exam week', assignedDate: '08-06-2026', dueDate: '10-06-2026', status: 'Completed' },
            { taskId: 'JD-T-017', title: 'Zone-wise sanitation inspection — Block A', assignedDate: '09-06-2026', dueDate: '11-06-2026', status: 'In Progress' },
            { taskId: 'JD-T-018', title: 'Cleaning supplies reorder — Q2 stock', assignedDate: '06-06-2026', dueDate: '09-06-2026', status: 'Pending' },
        ],
    },
}

export const EMPLOYEE_ROLE_SLUGS = Object.keys(EMPLOYEE_PROFILES)
