export const VIEW_FILTERS = [
    { key: 'all', label: 'All Views' },
    { key: 'canteen', label: 'Canteen Inventory', sub: 'Low stock food items' },
    { key: 'stationery', label: 'Stationery Inventory', sub: 'Low stock stationery' },
    { key: 'housekeeping', label: 'Housekeeping Inventory', sub: 'Cleaning supplies' },
    { key: 'it', label: 'IT Assets', sub: 'Devices, software licenses, warranty status' },
    { key: 'transport', label: 'Transport Assets', sub: 'Vehicles, maintenance schedules' },
]

export const DEPARTMENTS = ['Canteen', 'Stationery Store', 'Housekeeping', 'IT Support', 'Transport']

export const ALERT_TYPES = ['Low Stock', 'Expiring Warranty']

export const STATUS_OPTIONS = ['Normal', 'Critical']

export const ASSETS_INVENTORY = [
    {
        id: 'AI-CM-001',
        viewType: 'canteen',
        department: 'Canteen',
        assetCategory: 'Food Item',
        assetProduct: 'Cooking Oil (5L)',
        currentQuantity: 4,
        reorderLevel: 15,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '10-06-2026',
        description: 'Refined sunflower cooking oil for daily meal preparation.',
    },
    {
        id: 'AI-CM-002',
        viewType: 'canteen',
        department: 'Canteen',
        assetCategory: 'Food Item',
        assetProduct: 'Basmati Rice (25 kg bag)',
        currentQuantity: 6,
        reorderLevel: 20,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '09-06-2026',
        description: 'Premium basmati rice for student lunch service.',
    },
    {
        id: 'AI-CM-003',
        viewType: 'canteen',
        department: 'Canteen',
        assetCategory: 'Food Item',
        assetProduct: 'Fresh Milk (1L packs)',
        currentQuantity: 48,
        reorderLevel: 30,
        alertType: 'Low Stock',
        status: 'Normal',
        lastUpdated: '10-06-2026',
        description: 'Daily milk supply for beverages and cooking.',
    },
    {
        id: 'AI-SS-001',
        viewType: 'stationery',
        department: 'Stationery Store',
        assetCategory: 'Paper',
        assetProduct: 'A4 Paper Ream (500 sheets)',
        currentQuantity: 8,
        reorderLevel: 20,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '10-06-2026',
        description: '80 GSM A4 copier paper for admin and classroom use.',
    },
    {
        id: 'AI-SS-002',
        viewType: 'stationery',
        department: 'Stationery Store',
        assetCategory: 'Pen',
        assetProduct: 'Blue Ballpoint Pen',
        currentQuantity: 45,
        reorderLevel: 100,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '08-06-2026',
        description: 'Standard blue ballpoint pens for office and classroom.',
    },
    {
        id: 'AI-SS-003',
        viewType: 'stationery',
        department: 'Stationery Store',
        assetCategory: 'Notebook',
        assetProduct: 'Spiral Notebook — 200 pages',
        currentQuantity: 0,
        reorderLevel: 50,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '07-06-2026',
        description: 'Single-subject ruled notebooks for student distribution.',
    },
    {
        id: 'AI-HK-001',
        viewType: 'housekeeping',
        department: 'Housekeeping',
        assetCategory: 'Cleaning Chemical',
        assetProduct: 'Floor Cleaner — Lemon (5L)',
        currentQuantity: 6,
        reorderLevel: 15,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '10-06-2026',
        description: 'Multi-surface floor cleaner concentrate.',
    },
    {
        id: 'AI-HK-002',
        viewType: 'housekeeping',
        department: 'Housekeeping',
        assetCategory: 'Consumable',
        assetProduct: 'Garbage Bags — Large (Roll of 50)',
        currentQuantity: 8,
        reorderLevel: 20,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '09-06-2026',
        description: 'Heavy-duty garbage bags for campus waste collection.',
    },
    {
        id: 'AI-HK-003',
        viewType: 'housekeeping',
        department: 'Housekeeping',
        assetCategory: 'Equipment',
        assetProduct: 'Mop Head — Cotton (Standard)',
        currentQuantity: 0,
        reorderLevel: 10,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '10-01-2026',
        description: 'Replaceable cotton mop heads for corridor cleaning.',
    },
    {
        id: 'AI-IT-001',
        viewType: 'it',
        department: 'IT Support',
        assetCategory: 'Device',
        assetProduct: 'Dell Latitude 5540 Laptop',
        currentQuantity: 42,
        reorderLevel: null,
        alertType: 'Expiring Warranty',
        status: 'Critical',
        lastUpdated: '05-06-2026',
        warrantyExpiry: '30-06-2026',
        description: 'Staff laptops assigned across admin and teaching blocks.',
    },
    {
        id: 'AI-IT-002',
        viewType: 'it',
        department: 'IT Support',
        assetCategory: 'Software License',
        assetProduct: 'Microsoft 365 Education',
        currentQuantity: 250,
        reorderLevel: null,
        alertType: 'Expiring Warranty',
        status: 'Critical',
        lastUpdated: '01-06-2026',
        warrantyExpiry: '15-07-2026',
        description: 'Annual subscription for staff and student accounts.',
    },
    {
        id: 'AI-IT-003',
        viewType: 'it',
        department: 'IT Support',
        assetCategory: 'Device',
        assetProduct: 'HP LaserJet Pro M404dn',
        currentQuantity: 18,
        reorderLevel: null,
        alertType: 'Low Stock',
        status: 'Normal',
        lastUpdated: '10-06-2026',
        description: 'Network printers deployed in admin and department offices.',
    },
    {
        id: 'AI-IT-004',
        viewType: 'it',
        department: 'IT Support',
        assetCategory: 'Software License',
        assetProduct: 'Antivirus Enterprise Suite',
        currentQuantity: 300,
        reorderLevel: null,
        alertType: 'Expiring Warranty',
        status: 'Normal',
        lastUpdated: '08-06-2026',
        warrantyExpiry: '31-12-2026',
        description: 'Endpoint protection license for all campus devices.',
    },
    {
        id: 'AI-TR-001',
        viewType: 'transport',
        department: 'Transport',
        assetCategory: 'Vehicle',
        assetProduct: 'School Bus — TN-09-AB-4521',
        currentQuantity: 1,
        reorderLevel: null,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '10-06-2026',
        maintenanceDue: '12-06-2026',
        description: 'Route 3 morning bus — brake inspection overdue.',
    },
    {
        id: 'AI-TR-002',
        viewType: 'transport',
        department: 'Transport',
        assetCategory: 'Vehicle',
        assetProduct: 'School Bus — TN-09-CD-8834',
        currentQuantity: 1,
        reorderLevel: null,
        alertType: 'Low Stock',
        status: 'Critical',
        lastUpdated: '09-06-2026',
        maintenanceDue: '14-06-2026',
        description: 'Route 5 afternoon bus — scheduled tyre replacement.',
    },
    {
        id: 'AI-TR-003',
        viewType: 'transport',
        department: 'Transport',
        assetCategory: 'Vehicle',
        assetProduct: 'Van — TN-09-EF-2210',
        currentQuantity: 1,
        reorderLevel: null,
        alertType: 'Low Stock',
        status: 'Normal',
        lastUpdated: '10-06-2026',
        maintenanceDue: '28-06-2026',
        description: 'Staff transport van — last service completed.',
    },
    {
        id: 'AI-TR-004',
        viewType: 'transport',
        department: 'Transport',
        assetCategory: 'Maintenance Schedule',
        assetProduct: 'Fleet Quarterly Service — All Buses',
        currentQuantity: 22,
        reorderLevel: null,
        alertType: 'Low Stock',
        status: 'Normal',
        lastUpdated: '01-06-2026',
        maintenanceDue: '30-06-2026',
        description: 'Quarterly maintenance schedule for entire bus fleet.',
    },
]

export const statusBadgeColor = {
    Normal: 'bg-[#4CAF5033] text-[#4CAF50]',
    Critical: 'bg-[#FF000033] text-[#FF0000]',
}

export const alertBadgeColor = {
    'Low Stock': 'bg-[#FF980033] text-[#FF9800]',
    'Expiring Warranty': 'bg-[#2196F333] text-[#2196F3]',
}

export const getAssetById = (id) =>
    ASSETS_INVENTORY.find((item) => item.id === id) ?? null

export const getViewFilter = (key) =>
    VIEW_FILTERS.find((view) => view.key === key)
