export const ROLES = {
    SUPER_ADMIN: 'superadmin',
    ADMIN: 'admin',
    STUDENT: 'student',
    PARENT: 'parent',
    LIBRARIAN: 'librarian',
    PRM: 'prm',
    GATEKEEPER: 'gatekeeper',
    GATEKEEPER_MANAGER: 'gatekeepermanager',
    DIRECTOR: 'director',
    PRINCIPAL: 'principal',
    CANTEEN_MANAGER: 'canteenmanager',
    IT_SUPPORT_MANAGER: 'itsupportmanager',
    STATIONERY_STORE_MANAGER: 'stationerystoremanager',
    HOUSEKEEPING_MANAGER: 'housekeepingmanager',
    TRANSPORT_MANAGER: 'transportmanager',
    TEACHER: 'teacher',
    COORDINATOR: 'coordinator',
    JOINT_DIRECTOR: 'jointdirector',
    JOINT_DIRECTOR_ASSISTANT: 'jointdirectorassistant',
    JOINT_DIRECTOR_AUDIT: 'jointdirectoraudit',
    PROCESS_AUDITOR: 'processauditor',
    QUALITY_AUDITOR: 'qualityauditor',
    HR: 'hr',
    ACCOUNT_HEAD: 'accounthead',
    DRIVER: 'driver',
}
