export const CATEGORIES = ['Pen', 'Paper', 'Notebook', 'Printer Supplies', 'Files & Folders', 'Art Supplies', 'Adhesive & Tape']

export const UNITS = ['Pieces', 'Box', 'Pack']

export const STATUS_OPTIONS = ['Available', 'Low Stock', 'Out of Stock']

export const INVENTORY_ITEMS = [
    {
        itemId: 'STN-2026-0142',
        itemName: 'Blue Ballpoint Pen',
        itemCode: 'PEN-BLU-001',
        category: 'Pen',
        supplier: 'Office Mart India',
        supplierContact: '+91 98765 43210',
        unit: 'Pieces',
        availableQuantity: 450,
        reorderLevel: 100,
        unitCost: '₹12',
        stockValue: '₹5,400',
        status: 'Available',
        description: 'Smooth-writing blue ballpoint pens for daily office and classroom use.',
        purchaseDate: '15-03-2026',
        invoiceNumber: 'INV-OM-8821',
    },
    {
        itemId: 'STN-2026-0138',
        itemName: 'A4 Paper Ream (500 sheets)',
        itemCode: 'PAP-A4-500',
        category: 'Paper',
        supplier: 'PaperPro Supplies',
        supplierContact: '+91 91234 56789',
        unit: 'Pack',
        availableQuantity: 8,
        reorderLevel: 20,
        unitCost: '₹280',
        stockValue: '₹2,240',
        status: 'Low Stock',
        description: '80 GSM A4 copier paper, 500 sheets per ream.',
        purchaseDate: '02-05-2026',
        invoiceNumber: 'INV-PP-4412',
    },
    {
        itemId: 'STN-2026-0125',
        itemName: 'Spiral Notebook — 200 pages',
        itemCode: 'NB-SPR-200',
        category: 'Notebook',
        supplier: 'Classmate Wholesale',
        supplierContact: '+91 99887 76655',
        unit: 'Pieces',
        availableQuantity: 0,
        reorderLevel: 50,
        unitCost: '₹65',
        stockValue: '₹0',
        status: 'Out of Stock',
        description: 'Single-subject spiral notebook, ruled, 200 pages.',
        purchaseDate: '20-04-2026',
        invoiceNumber: 'INV-CW-3301',
    },
    {
        itemId: 'STN-2026-0098',
        itemName: 'HP 803 Black Ink Cartridge',
        itemCode: 'PRT-HP803-BK',
        category: 'Printer Supplies',
        supplier: 'PrintTech Solutions',
        supplierContact: '+91 97654 32109',
        unit: 'Pieces',
        availableQuantity: 24,
        reorderLevel: 10,
        unitCost: '₹850',
        stockValue: '₹20,400',
        status: 'Available',
        description: 'Original HP 803 black ink cartridge for admin printers.',
        purchaseDate: '10-01-2026',
        invoiceNumber: 'INV-PT-1109',
    },
    {
        itemId: 'STN-2026-0071',
        itemName: 'Stapler Pins (Box of 1000)',
        itemCode: 'STP-PIN-1K',
        category: 'Printer Supplies',
        supplier: 'Office Mart India',
        supplierContact: '+91 98765 43210',
        unit: 'Box',
        availableQuantity: 5,
        reorderLevel: 15,
        unitCost: '₹45',
        stockValue: '₹225',
        status: 'Low Stock',
        description: 'Standard 24/6 stapler pins, box of 1000.',
        purchaseDate: '28-05-2026',
        invoiceNumber: 'INV-OM-2290',
    },
    {
        itemId: 'STN-2026-0044',
        itemName: 'Whiteboard Marker — Black',
        itemCode: 'ART-WBM-BLK',
        category: 'Art Supplies',
        supplier: 'Creative Stationers',
        supplierContact: '+91 90123 45678',
        unit: 'Pieces',
        availableQuantity: 36,
        reorderLevel: 30,
        unitCost: '₹35',
        stockValue: '₹1,260',
        status: 'Available',
        description: 'Dry-erase whiteboard marker, black, chisel tip.',
        purchaseDate: '01-06-2026',
        invoiceNumber: 'INV-CS-7701',
    },
]

export const statusBadgeColor = {
    Available: 'bg-[#4CAF5033] text-[#4CAF50]',
    'Low Stock': 'bg-[#FF980033] text-[#FF9800]',
    'Out of Stock': 'bg-[#FF000033] text-[#FF0000]',
}

export const getInventoryItemById = (id) =>
    INVENTORY_ITEMS.find((entry) => entry.itemId === id)
