import { ROUTES } from '../RouteManagement/routeManagementData'

export const CLASS_SECTIONS = [
    'Grade 6 - A',
    'Grade 7 - B',
    'Grade 8 - A',
    'Grade 9 - C',
    'Grade 10 - A',
    'Grade 11 - B',
    'Grade 12 - A',
]

export const FEES_STRUCTURES = ['Yearly', 'Half Yearly', 'Quarterly', 'Monthly']

export const ROUTE_OPTIONS = ROUTES.map((route) => ({
    id: route.id,
    label: route.routeName,
    startLocation: route.startLocation,
    endLocation: route.endLocation,
    vehicleNumber: route.vehicleNumber,
    supportStaff: route.supportStaff,
    driverName: route.driverName,
    driverContact: route.driverContact,
    pickUpTime: route.pickUpTime,
    dropTime: route.dropTime,
    feesStructure: 'Yearly',
}))

export const STUDENT_TRANSPORTS = [
    {
        id: 'ST-1001',
        studentId: 'STD-2024-1042',
        studentName: 'Arjun Krishnan',
        classSection: 'Grade 9 - C',
        parentName: 'Krishnan Nair',
        parentContact: '9840011042',
        admissionNumber: 'ADM-2024-0891',
        routeId: 'RT-1001',
        routeName: 'Route 5 — North Campus',
        startLocation: 'Anna Nagar',
        endLocation: 'Queen Mira International School',
        vehicleNumber: 'TN-09-AB-4521',
        supportStaff: 'Mrs. Lakshmi (Attendant)',
        driverName: 'Sandy Selva',
        driverContact: '9944076993',
        pickUpTime: '06:45 AM',
        dropTime: '07:30 AM',
        feesStructure: 'Yearly — ₹45,000',
        createdDate: '15-04-2025',
    },
    {
        id: 'ST-1002',
        studentId: 'STD-2024-1108',
        studentName: 'Meera Vijay',
        classSection: 'Grade 7 - B',
        parentName: 'Vijay Menon',
        parentContact: '9840011108',
        admissionNumber: 'ADM-2024-0956',
        routeId: 'RT-1002',
        routeName: 'Route 2 — East Campus',
        startLocation: 'Velachery',
        endLocation: 'Queen Mira International School',
        vehicleNumber: 'TN-09-CD-8834',
        supportStaff: 'Mr. Karthik (Attendant)',
        driverName: 'Rajesh K. Kumar',
        driverContact: '9845012345',
        pickUpTime: '06:30 AM',
        dropTime: '07:25 AM',
        feesStructure: 'Half Yearly — ₹25,500',
        createdDate: '22-04-2025',
    },
    {
        id: 'ST-1003',
        studentId: 'STD-2024-1175',
        studentName: 'Rahul Sharma',
        classSection: 'Grade 10 - A',
        parentName: 'Suresh Sharma',
        parentContact: '9840011175',
        admissionNumber: 'ADM-2023-0442',
        routeId: 'RT-1003',
        routeName: 'Route 8 — West Campus',
        startLocation: 'Porur',
        endLocation: 'Queen Mira International School',
        vehicleNumber: 'TN-09-EF-2210',
        supportStaff: 'Mrs. Anitha (Attendant)',
        driverName: 'Priya M. Venkatesh',
        driverContact: '9789012345',
        pickUpTime: '06:50 AM',
        dropTime: '07:35 AM',
        feesStructure: 'Quarterly — ₹11,000',
        createdDate: '05-05-2025',
    },
    {
        id: 'ST-1004',
        studentId: 'STD-2024-1203',
        studentName: 'Divya Nair',
        classSection: 'Grade 8 - A',
        parentName: 'Suresh Nair',
        parentContact: '9840011203',
        admissionNumber: 'ADM-2024-1023',
        routeId: 'RT-1004',
        routeName: 'Route 3 — South Campus',
        startLocation: 'Pallavaram',
        endLocation: 'Queen Mira International School',
        vehicleNumber: 'TN-09-GH-5567',
        supportStaff: 'Mr. Suresh (Attendant)',
        driverName: 'Mohan R. Das',
        driverContact: '9654321098',
        pickUpTime: '06:20 AM',
        dropTime: '07:20 AM',
        feesStructure: 'Monthly — ₹4,800',
        createdDate: '18-05-2025',
    },
    {
        id: 'ST-1005',
        studentId: 'STD-2024-1289',
        studentName: 'Kavin Raj',
        classSection: 'Grade 6 - A',
        parentName: 'Rajendran K.',
        parentContact: '9840011289',
        admissionNumber: 'ADM-2024-1102',
        routeId: 'RT-1001',
        routeName: 'Route 5 — North Campus',
        startLocation: 'Anna Nagar',
        endLocation: 'Queen Mira International School',
        vehicleNumber: 'TN-09-AB-4521',
        supportStaff: 'Mrs. Lakshmi (Attendant)',
        driverName: 'Sandy Selva',
        driverContact: '9944076993',
        pickUpTime: '06:45 AM',
        dropTime: '07:30 AM',
        feesStructure: 'Yearly — ₹45,000',
        createdDate: '02-06-2025',
    },
]

export const getStudentTransportById = (id) =>
    STUDENT_TRANSPORTS.find((record) => record.id === id) ?? null
