export const MENU_ITEMS = [
    {
        menuId: 'MENU001',
        itemName: 'Veg Biryani',
        category: 'Lunch',
        itemCode: 'VC-BIR-001',
        price: '₹60',
        availability: 'Available',
        isCombo: 'No',
        status: 'Active',
        createdBy: 'Rajesh Kumar',
        createdDate: '01-05-2026',
        lastUpdated: '08-06-2026',
        description: 'Hyderabadi-style vegetable biryani served with raita. Popular lunch item among senior students.',
    },
    {
        menuId: 'MENU002',
        itemName: 'Chicken Sandwich',
        category: 'Snacks',
        itemCode: 'CK-SND-002',
        price: '₹45',
        availability: 'Available',
        isCombo: 'No',
        status: 'Active',
        createdBy: 'Priya Sharma',
        createdDate: '10-05-2026',
        lastUpdated: '05-06-2026',
        description: 'Grilled chicken sandwich with fresh vegetables and mint chutney.',
    },
    {
        menuId: 'MENU003',
        itemName: 'Fresh Fruit Juice',
        category: 'Beverages',
        itemCode: 'BV-JUC-003',
        price: '₹30',
        availability: 'Available',
        isCombo: 'No',
        status: 'Active',
        createdBy: 'Rajesh Kumar',
        createdDate: '15-05-2026',
        lastUpdated: '09-06-2026',
        description: 'Seasonal mixed fruit juice — orange, apple, and pomegranate blend.',
    },
    {
        menuId: 'MENU004',
        itemName: 'Masala Dosa',
        category: 'Breakfast',
        itemCode: 'BF-DOS-004',
        price: '₹40',
        availability: 'Out of Stock',
        isCombo: 'No',
        status: 'Active',
        createdBy: 'Priya Sharma',
        createdDate: '20-04-2026',
        lastUpdated: '10-06-2026',
        description: 'Crispy dosa with spiced potato filling, served with sambar and chutney.',
    },
    {
        menuId: 'MENU005',
        itemName: 'Student Meal Combo',
        category: 'Lunch',
        itemCode: 'CB-LNC-005',
        price: '₹85',
        availability: 'Available',
        isCombo: 'Yes',
        status: 'Active',
        createdBy: 'Rajesh Kumar',
        createdDate: '01-06-2026',
        lastUpdated: '10-06-2026',
        description: 'Combo includes rice, dal, vegetable curry, papad, and buttermilk.',
    },
    {
        menuId: 'MENU006',
        itemName: 'Cold Coffee',
        category: 'Beverages',
        itemCode: 'BV-COF-006',
        price: '₹35',
        availability: 'Available',
        isCombo: 'No',
        status: 'Inactive',
        createdBy: 'Priya Sharma',
        createdDate: '12-03-2026',
        lastUpdated: '01-05-2026',
        description: 'Iced coffee with milk — temporarily inactive pending equipment repair.',
    },
]

export const availabilityBadgeColor = {
    Available: 'bg-[#4CAF5033] text-[#4CAF50]',
    'Out of Stock': 'bg-[#FF000033] text-[#FF0000]',
}

export const statusBadgeColor = {
    Active: 'bg-[#4CAF5033] text-[#4CAF50]',
    Inactive: 'bg-[#66708533] text-[#667085]',
}

export const comboBadgeColor = {
    Yes: 'bg-[#2196F333] text-[#2196F3]',
    No: 'bg-[#66708533] text-[#667085]',
}
