export const STAFF_NOTIFICATION_TYPES = ['General', 'Exam', 'Event', 'Holiday', 'Announcement', 'Payment']

export const staffTypeBadgeColor = {
    General: 'bg-[#515DEF33] text-[#515DEF]',
    Exam: 'bg-[#9C27B033] text-[#9C27B0]',
    Event: 'bg-[#FF980033] text-[#FF9800]',
    Holiday: 'bg-[#4CAF5033] text-[#4CAF50]',
    Announcement: 'bg-[#2196F333] text-[#2196F3]',
    Payment: 'bg-[#FF572233] text-[#FF5722]',
}

export const STAFF_NOTIFICATIONS = [
    {
        id: 'STF-NTF-001',
        type: 'Exam',
        title: 'Board Exam Schedule Published',
        message: 'The final board examination timetable for Classes 10 and 12 has been published. All departments must verify subject allocations.',
        relatedDate: '20-03-2026',
        notificationDate: '10-03-2026',
        postedBy: 'Examination Cell',
        isRead: false,
        meta: 'Classes 10 & 12',
    },
    {
        id: 'STF-NTF-002',
        type: 'Event',
        title: 'Annual Day Rehearsal Schedule',
        message: 'Annual Day rehearsals are scheduled from 18–22 March. Teams must coordinate venue bookings and security.',
        relatedDate: '18-03-2026',
        notificationDate: '09-03-2026',
        postedBy: 'Principal Office',
        isRead: true,
        meta: 'School Auditorium',
    },
    {
        id: 'STF-NTF-003',
        type: 'General',
        title: 'Staff Attendance Policy Update',
        message: 'Updated staff attendance policy effective 01 April 2026. HR circular is available in the documents section.',
        relatedDate: '01-04-2026',
        notificationDate: '08-03-2026',
        postedBy: 'HR Department',
        isRead: false,
    },
    {
        id: 'STF-NTF-004',
        type: 'Payment',
        title: 'Term Fee Collection Reminder',
        message: 'Term 2 fee collection deadline is 25 March 2026. Front office to follow up on pending accounts.',
        relatedDate: '25-03-2026',
        notificationDate: '07-03-2026',
        postedBy: 'Accounts Office',
        isRead: true,
        meta: 'Term 2 · Pending Accounts',
    },
    {
        id: 'STF-NTF-005',
        type: 'Holiday',
        title: 'Holi Holiday Notification',
        message: 'School will remain closed on 14 March 2026 for Holi. Emergency contact roster to be shared with security.',
        relatedDate: '14-03-2026',
        notificationDate: '05-03-2026',
        postedBy: 'Administration',
        isRead: true,
        meta: 'Public Holiday',
    },
    {
        id: 'STF-NTF-006',
        type: 'Announcement',
        title: 'Gate Pass Policy Reminder',
        message: 'All visitor and material gate passes must be verified at the main gate before entry. Updated checklist is attached.',
        relatedDate: '12-03-2026',
        notificationDate: '04-03-2026',
        postedBy: 'Security Office',
        isRead: false,
        meta: 'Security · Main Gate',
    },
    {
        id: 'STF-NTF-007',
        type: 'General',
        title: 'Parent-Teacher Meeting',
        message: 'PTM scheduled for Class 10 sections. Staff must be available in assigned classrooms from 02:00 PM.',
        relatedDate: '18-03-2026',
        notificationDate: '06-03-2026',
        postedBy: 'Principal Office',
        isRead: true,
    },
    {
        id: 'STF-NTF-008',
        type: 'Announcement',
        title: 'Online Portal Maintenance',
        message: 'School ERP portal will be under maintenance on Sunday 09:00 PM to Monday 06:00 AM. Plan submissions accordingly.',
        relatedDate: '08-03-2026',
        notificationDate: '07-03-2026',
        postedBy: 'IT Department',
        isRead: false,
    },
]
