import { CHEQUE_STATUSES, DEFAULT_ACADEMIC_YEAR, DEFAULT_BANK_ACCOUNT_ID, FEE_INSTALLMENT_STATUSES, FINE_TYPES } from './financeConstants'

export const FINANCE_ACADEMIC_YEARS = ['2026-2027', '2025-2026', '2024-2025']

export const FEE_CATEGORIES = [
    { id: 'CAT-TUITION', name: 'Tuition Fee', code: 'TUITION', active: true },
    { id: 'CAT-ADMISSION', name: 'Admission Fee', code: 'ADMISSION', active: true },
    { id: 'CAT-TRANSPORT', name: 'Transport Fee', code: 'TRANSPORT', active: true },
    { id: 'CAT-BOOKS', name: 'Books Fee', code: 'BOOKS', active: true },
    { id: 'CAT-ACTIVITY', name: 'Activity Fee', code: 'ACTIVITY', active: true },
    { id: 'CAT-HOSTEL', name: 'Hostel Fee', code: 'HOSTEL', active: true },
    { id: 'CAT-EXAM', name: 'Exam Fee', code: 'EXAM', active: true },
    { id: 'CAT-CUSTOM', name: 'Custom Fee', code: 'CUSTOM', active: true },
]

export const BANK_ACCOUNTS = [
    {
        id: DEFAULT_BANK_ACCOUNT_ID,
        name: 'SBI Current A/c',
        bankName: 'State Bank of India',
        accountNumber: '38472910482',
        ifsc: 'SBIN0001234',
        enabled: true,
    },
    {
        id: 'BANK-HDFC-001',
        name: 'HDFC Savings A/c',
        bankName: 'HDFC Bank',
        accountNumber: '501000884219',
        ifsc: 'HDFC0002211',
        enabled: true,
    },
]

export const POS_TERMINALS = [
    {
        id: 'POS-001',
        name: 'Front Office POS',
        terminalId: 'TERM001',
        provider: 'Bank / Gateway',
        enabled: true,
    },
    {
        id: 'POS-002',
        name: 'Accounts Counter POS',
        terminalId: 'TERM002',
        provider: 'Bank / Gateway',
        enabled: true,
    },
]

export const FINE_RULES = [
    {
        id: 'FINE-TUITION-DAILY',
        name: 'Tuition Late Fee',
        feeCategoryId: 'CAT-TUITION',
        gracePeriod: 5,
        fineType: FINE_TYPES.DAILY,
        fineValue: 10,
        maximumFine: 500,
        effectiveFrom: '2026-04-01',
        effectiveTo: '2027-03-31',
        active: true,
    },
    {
        id: 'FINE-TRANSPORT-FLAT',
        name: 'Transport Late Fee',
        feeCategoryId: 'CAT-TRANSPORT',
        gracePeriod: 3,
        fineType: FINE_TYPES.FLAT,
        fineValue: 50,
        maximumFine: 50,
        effectiveFrom: '2026-04-01',
        effectiveTo: '2027-03-31',
        active: true,
    },
]

export const FEE_STRUCTURES = [
    {
        id: 'FS-G2-TUITION-2627',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        className: 'Grade 2',
        feeCategoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        frequency: 'MONTHLY',
        amount: 2500,
        dueDayOfMonth: 10,
        fineRuleId: 'FINE-TUITION-DAILY',
        concessionApplicable: true,
        mandatory: true,
        status: 'ACTIVE',
    },
    {
        id: 'FS-G2-TRANSPORT-2627',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        className: 'Grade 2',
        feeCategoryId: 'CAT-TRANSPORT',
        feeHead: 'Transport Fee',
        frequency: 'MONTHLY',
        amount: 1000,
        dueDayOfMonth: 10,
        fineRuleId: 'FINE-TRANSPORT-FLAT',
        concessionApplicable: true,
        mandatory: false,
        status: 'ACTIVE',
    },
    {
        id: 'FS-G10-TUITION-2627',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        className: 'Grade 10',
        feeCategoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        frequency: 'MONTHLY',
        amount: 4200,
        dueDayOfMonth: 10,
        fineRuleId: 'FINE-TUITION-DAILY',
        concessionApplicable: true,
        mandatory: true,
        status: 'ACTIVE',
    },
    {
        id: 'FS-G10-EXAM-2627',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        className: 'Grade 10',
        feeCategoryId: 'CAT-EXAM',
        feeHead: 'Exam Fee',
        frequency: 'TERM_WISE',
        amount: 800,
        dueDayOfMonth: 15,
        fineRuleId: null,
        concessionApplicable: false,
        mandatory: true,
        status: 'ACTIVE',
    },
]

export const FINANCE_STUDENTS = [
    {
        id: 'STU-AB-001',
        name: 'Abd Ar Rahman',
        shortName: 'Abd Ar',
        initials: 'AB',
        admissionNo: 'ADM-2026-0001',
        rollNo: '2A-01',
        applicationNo: 'APP-2026-0011',
        registerNo: 'REG-2026-0001',
        className: 'Grade 2',
        section: 'A',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        dateOfBirth: '2018-04-12',
        bloodGroup: 'O+',
        fatherName: 'Abdullah Rahman',
        motherName: 'Ayesha Rahman',
        phone: '9876543210',
        email: 'abd.ar@student.school.com',
        familyId: 'FAM-RAHMAN',
        status: 'Active',
    },
    {
        id: 'STU-AB-002',
        name: 'Amina Rahman',
        shortName: 'Amina',
        initials: 'AR',
        admissionNo: 'ADM-2026-0002',
        rollNo: '2A-02',
        applicationNo: 'APP-2026-0012',
        registerNo: 'REG-2026-0002',
        className: 'Grade 2',
        section: 'A',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        dateOfBirth: '2019-01-08',
        bloodGroup: 'B+',
        fatherName: 'Abdullah Rahman',
        motherName: 'Ayesha Rahman',
        phone: '9876543210',
        email: 'amina.r@student.school.com',
        familyId: 'FAM-RAHMAN',
        status: 'Active',
    },
    {
        id: 'STU-ARUN-001',
        name: 'Arun Raj',
        shortName: 'Arun Raj',
        initials: 'AR',
        admissionNo: 'ADM-2024-1042',
        rollNo: '10A-18',
        applicationNo: 'APP-2024-0884',
        registerNo: 'REG-2024-1042',
        className: 'Grade 10',
        section: 'A',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        dateOfBirth: '2011-08-22',
        bloodGroup: 'A+',
        fatherName: 'S. Rajan',
        motherName: 'Meena Rajan',
        phone: '9841012345',
        email: 'arun.raj@student.school.com',
        familyId: 'FAM-RAJAN',
        status: 'Active',
    },
    {
        id: 'STU-PRIYA-001',
        name: 'Priya M.',
        shortName: 'Priya M.',
        initials: 'PM',
        admissionNo: 'ADM-2024-1031',
        rollNo: '9B-07',
        applicationNo: 'APP-2024-0771',
        registerNo: 'REG-2024-1031',
        className: 'Grade 9',
        section: 'B',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        dateOfBirth: '2012-03-19',
        bloodGroup: 'O-',
        fatherName: 'Mohan K.',
        motherName: 'Lakshmi M.',
        phone: '9841099887',
        email: 'priya.m@student.school.com',
        familyId: 'FAM-PRIYA',
        status: 'Active',
    },
]

const installment = ({
    id,
    studentId,
    structureId,
    categoryId,
    feeHead,
    label,
    month,
    dueDate,
    feeAmount,
    concessionAmount = 0,
    paidAmount = 0,
    forcedStatus,
    fineWaived = false,
}) => ({
    id,
    studentId,
    academicYear: DEFAULT_ACADEMIC_YEAR,
    feeStructureId: structureId,
    feeCategoryId: categoryId,
    feeHead,
    installmentLabel: label,
    month,
    dueDate,
    feeAmount,
    concessionAmount,
    fineAmount: 0,
    netAmount: feeAmount - concessionAmount,
    paidAmount,
    balanceAmount: Math.max(0, feeAmount - concessionAmount - paidAmount),
    status: forcedStatus || (paidAmount >= feeAmount - concessionAmount
        ? FEE_INSTALLMENT_STATUSES.PAID
        : FEE_INSTALLMENT_STATUSES.UNPAID),
    forcedStatus: paidAmount >= feeAmount - concessionAmount ? FEE_INSTALLMENT_STATUSES.PAID : forcedStatus,
    fineWaived,
})

export const FEE_INSTALLMENTS = [
    installment({
        id: 'INS-AB1-JUL',
        studentId: 'STU-AB-001',
        structureId: 'FS-G2-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'July, 2026',
        month: '2026-07',
        dueDate: '2026-07-10',
        feeAmount: 2500,
        paidAmount: 2500,
        forcedStatus: FEE_INSTALLMENT_STATUSES.PAID,
    }),
    installment({
        id: 'INS-AB1-AUG',
        studentId: 'STU-AB-001',
        structureId: 'FS-G2-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'August, 2026',
        month: '2026-08',
        dueDate: '2026-08-10',
        feeAmount: 2500,
    }),
    installment({
        id: 'INS-AB1-SEP',
        studentId: 'STU-AB-001',
        structureId: 'FS-G2-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'September, 2026',
        month: '2026-09',
        dueDate: '2026-09-10',
        feeAmount: 2500,
    }),
    installment({
        id: 'INS-AB2-AUG',
        studentId: 'STU-AB-002',
        structureId: 'FS-G2-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'August, 2026',
        month: '2026-08',
        dueDate: '2026-08-10',
        feeAmount: 2500,
    }),
    installment({
        id: 'INS-AB2-TRN-AUG',
        studentId: 'STU-AB-002',
        structureId: 'FS-G2-TRANSPORT-2627',
        categoryId: 'CAT-TRANSPORT',
        feeHead: 'Transport Fee',
        label: 'August, 2026',
        month: '2026-08',
        dueDate: '2026-08-10',
        feeAmount: 1000,
    }),
    installment({
        id: 'INS-ARUN-AUG',
        studentId: 'STU-ARUN-001',
        structureId: 'FS-G10-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'August, 2026',
        month: '2026-08',
        dueDate: '2026-08-10',
        feeAmount: 4200,
        concessionAmount: 200,
        paidAmount: 1000,
        forcedStatus: FEE_INSTALLMENT_STATUSES.PARTIALLY_PAID,
    }),
    installment({
        id: 'INS-ARUN-SEP',
        studentId: 'STU-ARUN-001',
        structureId: 'FS-G10-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'September, 2026',
        month: '2026-09',
        dueDate: '2026-09-10',
        feeAmount: 4200,
        concessionAmount: 200,
    }),
    installment({
        id: 'INS-PRIYA-AUG',
        studentId: 'STU-PRIYA-001',
        structureId: 'FS-G10-TUITION-2627',
        categoryId: 'CAT-TUITION',
        feeHead: 'Tuition Fee',
        label: 'August, 2026',
        month: '2026-08',
        dueDate: '2026-08-10',
        feeAmount: 3800,
        concessionAmount: 500,
        paidAmount: 3300,
        forcedStatus: FEE_INSTALLMENT_STATUSES.PAID,
    }),
]

export const FEE_CONCESSIONS = [
    {
        id: 'CN-ARUN-SIB',
        studentId: 'STU-ARUN-001',
        type: 'Sibling Discount',
        feeCategoryId: 'CAT-TUITION',
        amount: 200,
        status: 'Approved',
        academicYear: DEFAULT_ACADEMIC_YEAR,
    },
    {
        id: 'CN-PRIYA-MERIT',
        studentId: 'STU-PRIYA-001',
        type: 'Merit Scholarship',
        feeCategoryId: 'CAT-TUITION',
        amount: 500,
        status: 'Approved',
        academicYear: DEFAULT_ACADEMIC_YEAR,
    },
]

export const SEED_RECEIPTS = [
    {
        id: 'REC-JUL-AB1',
        receiptNo: 'REC-2026-000101',
        studentId: 'STU-AB-001',
        academicYear: DEFAULT_ACADEMIC_YEAR,
        paymentDate: '2026-07-08',
        feeHeads: ['Tuition Fee'],
        grossFee: 2500,
        concession: 0,
        fine: 0,
        amountPaid: 2500,
        paymentMode: 'UPI',
        transactionReference: 'UPI/ABDAR@okicici/771001',
        balance: 0,
        collectedBy: 'Front Desk',
        installmentIds: ['INS-AB1-JUL'],
        reprintCount: 0,
        lastReprintedAt: null,
        lastReprintedBy: null,
        reprintReason: null,
        status: 'Issued',
        communication: { email: false, whatsapp: false },
    },
]

export const SEED_CHEQUES = [
    {
        id: 'CHQ-001',
        transactionId: null,
        studentId: 'STU-ARUN-001',
        chequeNo: '884210',
        bank: 'ICICI Bank',
        branch: 'Anna Nagar',
        chequeDate: '2026-10-05',
        receivedDate: '2026-09-12',
        amount: 10000,
        status: CHEQUE_STATUSES.PDC,
        narration: 'Term fee PDC — Arun Raj',
    },
]

export const PREVIOUS_YEAR_FEE_STATS = {
    academicYear: '2025-2026',
    totalDemand: 22800000,
    totalConcession: 980000,
    netDemand: 21820000,
    collected: 19120000,
    outstanding: 2700000,
    fineCollected: 84000,
    defaulters: 196,
}

export const CURRENT_YEAR_FEE_STATS = {
    academicYear: '2026-2027',
    totalDemand: 25000000,
    totalConcession: 1100000,
    netDemand: 23900000,
    collected: 18600000,
    outstanding: 5300000,
    fineCollected: 92000,
    defaulters: 218,
}

export const getCategoryName = (categoryId) =>
    FEE_CATEGORIES.find((item) => item.id === categoryId)?.name ?? categoryId

export const getFineRuleForCategory = (fineRules, categoryId) =>
    fineRules.find((rule) => rule.active && rule.feeCategoryId === categoryId) ?? null
