export const singleTitleMapping = {
    "/dashboard": "Dashboard",
    "/admin/dashboard": "Dashboard",
    "/super-admin/dashboard": "Super Admin Dashboard",

    "/super-admin/attendance/students/list": "Student Attendance",
    "/super-admin/attendance/employees": "Employee Attendance",

    "/super-admin/user-database/students": "Students List",
    "/super-admin/user-database/employees": "Employee List",

    "/super-admin/user-creation": "User Creation",
    "/super-admin/user-creation/add": "Create Admin User",

    "/super-admin/gate-pass": "Gate Pass List",

    "/super-admin/transport-overview": "Transport Overview",

    "/super-admin/finance/overview": "Finance Overview",
    "/super-admin/finance/fees": "Fees Management",
    "/super-admin/finance/collections": "Collections",
    "/super-admin/finance/wallets": "Wallet Management",
    "/super-admin/finance/transport": "Transport Finance",
    "/super-admin/finance/accounting": "Accounting",
    "/super-admin/finance/reports": "Reports & Analytics",

    "/super-admin/audit-reports/overview": "Audit Reports Overview",
    "/super-admin/audit-reports/compliance": "Compliance Score",
    "/super-admin/audit-reports/department-ranking": "Department Ranking",
    "/super-admin/audit-reports/pending-findings": "Pending Findings",
    "/super-admin/audit-reports/critical-findings": "Critical Findings",
    "/super-admin/audit-reports/risk-dashboard": "Risk Dashboard",

    "/super-admin/star-ratings/star-of-month": "Star of the Month",
    "/super-admin/star-ratings/star-of-year": "Star of the Year",

    "/super-admin/task-management/assign-tasks": "Assign Tasks List",
    "/super-admin/task-management/assign-tasks/add": "Assign Task",
    "/super-admin/leave-request/received": "Received Leave Requests",

    "/super-admin/approvals": "Approvals",

    "/super-admin/announcement": "Announcement List",
    "/super-admin/announcement/add": "Add Announcement",
    "/super-admin/communication/inbox": "Communication Inbox",
    "/super-admin/academic-calendar": "Calendar",
    "/super-admin/notifications": "Notifications",
    "/super-admin/escalation-management": "Escalation List",
    "/super-admin/escalation-management/add-escalation": "Add Escalation",

    "/super-admin/activity-logs/login-history": "Login History",
    "/super-admin/activity-logs/data-changes": "Data Changes",
    "/super-admin/activity-logs/deleted-records": "Deleted Records",
    "/super-admin/activity-logs/approval-actions": "Approval Actions",
    "/super-admin/activity-logs/audit-logs": "Audit Logs",
    "/super-admin/activity-logs/failed-logins": "Failed Logins",

    // Front Office
    "/front-office/dashboard": "Front Office Dashboard",
    "/front-office/admission-enquiry": "Admission Enquiry",
    "/front-office/admission-enquiry/add": "Add Admission Enquiry",
    "/front-office/add-admission-enquiry": "Add Admission Enquiry",
    "/front-office/admission-enquiry/edit": "Edit Admission Enquiry",
    "/front-office/admission-list": "Admission List",
    "/front-office/admission-list/edit": "Edit Admission",
    "/front-office/add-admission": "Add Admission",
    "/admin/front-office/admission-list": "Admissions",
    "/admin/front-office/add-admission": "Add Admission",
    "/admin/front-office/admission-enquiry": "Admission Enquiry",
    "/admin/front-office/admission-enquiry/add": "Add Admission Enquiry",
    "/admin/front-office/add-admission-enquiry": "Add Admission Enquiry",
    "/admin/front-office/admission-enquiry/edit": "Edit Admission Enquiry",
    "/admin/front-office/teachers-list": "Teachers List",
    "/admin/front-office/add-teacher": "Add Teacher",
    "/admin/front-office/librarian-list": "Librarian List",
    "/admin/front-office/add-librarian": "Add Librarian",
    "/admin/front-office/driver-list": "Driver List",
    "/admin/front-office/add-driver": "Add Driver",


    // Attendance
    "/admin/attendance/students-list": "Student Attendance List",
    "/admin/attendance/employees-list": "Employee Attendance List",
    "/admin/attendance/leave-request-list": "My Leave Requests",
    "/admin/attendance/leave-request": "My Leave Requests",


    // Class
    "/admin/class/class-details": "Class Details List",
    "/admin/class/add-class-details": "Add Class Details",
    "/admin/class/online-class": "Online Class List",
    "/admin/class/add-online-class": "Add Online Class",
    "/admin/class/extended-class": "Extended Class List",
    "/admin/class/add-extended-class": "Add Extended Class",
    "/admin/class/timetable-list": "Time Table List",
    "/admin/class/add-timetable": "Add Time Table",
    "/admin/class/subjects": "Subjects List",
    "/admin/class/add-subjects": "Add New Subject",


    // Library Details (Admin)
    "/admin/library-details/book-list": "Book List",
    "/admin/library-details/add-book": "Add Book",
    "/admin/library-details/issued-book": "Issued Book List",
    "/admin/library-details/add-issued-book": "Add Issued Book",


    // User Database
    "/admin/user-management/student-database": "Student Database",
    "/admin/user-management/employee-database": "Employee Database",

    // Student Details
    "/admin/student/student-details": "Student Database",
    "/admin/student/class-fee-details": "Class Fee Details List",
    "/admin/student/add-class-fee-details": "Add Class Fee Details",
    "/admin/student/parent-details": "Student Database",
    "/admin/student/student-transfer": "Student Transfer List",
    "/admin/student/add-student-transfer": "Add Student Transfer",
    "/admin/student/leave-request": "Student Leave Request List",
    "/admin/student/add-leave-request": "Add Student Leave Request",

    // Activities
    "/admin/activities/cultural-list": "Cultural List",
    "/admin/activities/add-cultural": "Add Cultural Information",
    "/admin/activities/sports-list": "Sports List",
    "/admin/activities/add-sports": "Add Sports Information",
    "/admin/activities/chess-result": "Chess Result",
    "/admin/activities/competitions-list": "Competitions List",
    "/admin/activities/add-competition": "Add Competition Information",

    // Documents
    "/admin/documents/student-documents": "Student Documents List",
    "/admin/documents/add-student-documents": "Add Student Documents",
    "/admin/documents/employee-documents": "Employee Documents List",
    "/admin/documents/add-employee-documents": "Add Employee Documents",

    // Transport
    "/admin/transport/vehicle-details": "Vehicle Details List",
    "/admin/transport/add-vehicle-details": "Add Vehicle Details",
    "/admin/transport/route-details": "Route Details List",
    "/admin/transport/add-route-details": "Add Route Details",
    "/admin/transport/route-data-list": "Route Data List",
    "/admin/transport/assigned-route-list": "Assigned Route List",
    "/admin/transport/assign-route": "Assign Route",

    // Exam Details
    "/admin/exam-details/exam-details-list": "Exam Details List",
    "/admin/exam-details/add-exam-details": "Add Exam Details",

    // Expenses
    "/admin/expenses/salaries-list": "Salaries Expenses List",
    "/admin/expenses/add-salaries-exp": "Add Salaries Expenses",
    "/admin/expenses/hostel-list": "Hostel Expenses List",
    "/admin/expenses/add-hostel-exp": "Add Hostel Expenses",
    "/admin/expenses/transport-list": "Transport Expenses List",
    "/admin/expenses/add-transport-exp": "Add Transport Expenses",
    "/admin/expenses/library-list": "Library Expenses List",
    "/admin/expenses/add-library-exp": "Add Library Expenses",
    "/admin/expenses/others-list": "Others Expenses List",
    "/admin/expenses/add-others-exp": "Add Others Expenses",

    // Notifications
    "/admin/notifications": "Notifications",
    "/admin/notification/exam-list": "Notifications",
    "/admin/notification/event-list": "Notifications",

    // Announcement
    "/admin/announcement": "Announcement List",
    "/admin/announcement/add": "Add Announcement",
    "/admin/tc-request-approval": "TC Request Approval",

    // Task Management
    "/admin/task-management/assign-tasks": "Assign Tasks List",
    "/admin/task-management/assign-tasks/add": "Assign Task",
    "/admin/task-management/assigned-tasks": "Assigned Tasks List",
    "/admin/task-management/my-tasks": "My Tasks",

    // Leave Request
    "/admin/leave-request/my-requests": "My Leave Requests",
    "/admin/leave-request/my-requests/add": "Apply Leave",
    "/admin/leave-request/received": "Received Leave Requests",

    "/admin/escalation-management": "Escalation List",
    "/admin/escalation-management/add-escalation": "Add Escalation",
    "/admin/rbac/user-creation": "User Creation",
    "/admin/rbac/user-creation/add": "Create User",
    "/admin/rbac/roles": "Roles",
    "/admin/academic-calendar": "Calendar",
    "/admin/communication/inbox": "Communication Inbox",

    // ── Student Role ──────────────────────────────────────────────────────────
    "/student/dashboard": "Dashboard",
    "/student/class/online-class": "Online Class List",
    "/student/class/extra-class": "Extended Class List",
    "/student/class/timetable-list": "Time Table List",
    "/student/class/attendance-list": "Attendance List",
    "/student/class/attendance-report": "Attendance Report",

    // Student Evaluation
    "/student/student-evaluation/exam-result": "Exam Result",
    "/student/student-evaluation/exam-schedule": "Exam Schedule",

    // Student Deliverables
    "/student/student-deliverables/home-fun": "Home Fun",
    "/student/student-deliverables/study-materials": "Study Materials",
    "/student/student-deliverables/sample-questions": "Sample Questions",

    // Library
    "/student/library/borrowed-books-list": "Borrowed Books List",

    // Transport
    "/student/transport/bus-route-details": "Bus Route Details",
    "/student/transport/track-bus": "Track Bus Location",

    // Hostel
    "/student/hostel/hostel-details": "Hostel Details",

    // Payemnt Details
    "/student/payment/fees-payment": "Fees Payment Details",
    "/student/payment/hostel-payment": "Hostel Payment Details",
    "/student/payment/transport-payment": "Transport Payment Details",

    // Notification
    "/student/notifications": "Notifications",
    "/student/notification/exam-notification": "Notifications",
    "/student/notification/event-notification": "Notifications",
    "/student/notification/holiday-notification": "Notifications",
    "/student/notification/payment-notification": "Notifications",

    "/student/announcement": "Announcement List",
    "/student/tc-request": "TC Request List",
    "/student/tc-request/add": "Request TC",

    // Star Ratings
    "/student/star-ratings/view-ratings": "View Star Rating",
    "/student/escalation-management": "Escalation List",
    "/student/escalation-management/add-escalation": "Add Escalation",
    "/student/academic-calendar": "Calendar",
    "/student/communication/inbox": "Communication Inbox",

    // ── Parent Role ───────────────────────────────────────────────────────────
    "/parent/select-child": "Select Child",
    "/parent/dashboard": "Dashboard",
    "/parent/class/online-class": "Online Class",
    "/parent/class/extra-class": "Extended Class",
    "/parent/class/timetable-list": "Timetable",
    "/parent/class/attendance-list": "Attendance List",
    "/parent/class/attendance-report": "Attendance Report",
    "/parent/student-evaluation/exam-result": "Exam Result",
    "/parent/student-evaluation/exam-schedule": "Exam Schedule",
    "/parent/student-evaluation/analytics": "Performance Analytics",
    "/student/student-evaluation/analytics": "Performance Analytics",
    "/parent/student-deliverables/home-fun": "Home Fun",
    "/parent/student-deliverables/study-materials": "Study Materials",
    "/parent/student-deliverables/sample-questions": "Sample Questions",
    "/parent/library/borrowed-books-list": "Borrowed Books List",
    "/parent/transport/track-bus": "Track Bus",
    "/parent/hostel/hostel-details": "Hostel Details",
    "/parent/payment/fees-payment": "Academic Payment",
    "/parent/payment/hostel-payment": "Hostel Payment Details",
    "/parent/payment/transport-payment": "Transport Payment Details",
    "/parent/notifications": "Notifications",
    "/parent/notification/exam-notification": "Notifications",
    "/parent/notification/event-notification": "Notifications",
    "/parent/notification/holiday-notification": "Notifications",
    "/parent/notification/payment-notification": "Notifications",
    "/parent/announcement": "Announcement List",
    "/parent/tc-request": "TC Request List",
    "/parent/tc-request/add": "Request TC",
    "/parent/academic-calendar": "Calendar",
    "/parent/communication/inbox": "Communication Inbox",
    "/parent/escalation-management": "Escalation List",
    "/parent/escalation-management/add-escalation": "Add Escalation",

    // ── Librarian Role ────────────────────────────────────────────────────────
    "/librarian/dashboard": "Dashboard",

    // Book Management
    "/librarian/book-management/book-list": "Book List",
    "/librarian/book-management/add-book": "Add Book",

    // Issued Books
    "/librarian/issued-books/issued-book-list": "Issued Book List",
    "/librarian/issued-books/add-issued-book": "Add Issued Book",

    // Members
    "/librarian/members/member-list": "Members List",

    // Notification
    "/librarian/notifications": "Notifications",
    "/librarian/notification/reminder-list": "Notifications",
    "/librarian/escalation-management": "Escalation List",
    "/librarian/escalation-management/add-escalation": "Add Escalation",
    "/librarian/task-management/my-tasks": "My Tasks",
    "/librarian/academic-calendar": "Academic Calendar",
    "/librarian/announcement": "Announcement List",
    "/librarian/attendance/my-attendance": "My Attendance",
    "/librarian/communication/inbox": "Communication Inbox",

    "/front-office/student-management": "Student Database",
    "/front-office/teacher-management": "Teacher Database",
    "/front-office/parent-management": "Parent Database",
    "/front-office/view-student": "View Student",
    "/front-office/view-teacher": "View Teacher",
    "/front-office/view-parent": "View Parent",
    "/front-office/student-transfer": "Student Transfer List",
    "/front-office/student-transfer/add": "Add Student Transfer",
    "/front-office/student-re-enrollment": "Student Re-Enrollment List",
    "/front-office/student-re-enrollment/add": "Student Re-Enrollment",
    "/front-office/tc-request": "TC Request List",
    "/front-office/gate-pass-list": "Student Gate Pass List",
    "/front-office/add-gate-pass": "Add Student Gate Pass",
    "/front-office/hostel-gate-pass-list": "Hostel Gate Pass List",
    "/front-office/add-hostel-gate-pass": "Add Hostel Gate Pass",
    "/front-office/material-gate-pass-list": "Material Gate Pass List",
    "/front-office/add-material-gate-pass": "Add Material Gate Pass",
    "/front-office/goods-received-pass-list": "Goods Received Pass List",
    "/front-office/add-goods-received-pass": "Add Goods Received Pass",
    "/front-office/escalation-management": "Escalation List",
    "/front-office/escalation-management/add-escalation": "Add Escalation",
    "/front-office/task-management/assign-tasks": "Assign Tasks List",
    "/front-office/task-management/assign-tasks/add": "Assign Task",
    "/front-office/task-management/my-tasks": "My Tasks",
    "/front-office/academic-calendar": "Calendar",
    "/front-office/announcement": "Announcement List",
    "/front-office/notifications": "Notifications",
    "/front-office/leave-request/my-requests": "My Leave Requests",
    "/front-office/leave-request/my-requests/add": "Apply Leave",
    "/front-office/leave-request/received": "Received Leave Requests",
    "/front-office/attendance/my-attendance": "My Attendance",
    "/front-office/communication/inbox": "Communication Inbox",

    // ── Gate Keeper Role ──────────────────────────────────────────────────────
    "/gate-keeper/dashboard": "Dashboard",
    "/gate-keeper/task-management/my-tasks": "My Tasks",
    "/gate-keeper/hostel-gate-pass": "Hostel Gate Pass List",
    "/gate-keeper/my-duty": "My Duty List",
    "/gate-keeper/incidents": "CSO / Gate Keeper",
    "/gate-keeper/add-incident": "CSO / Gate Keeper",
    "/gate-keeper/gate-pass-list": "Gate Pass List",
    "/gate-keeper/add-gate-pass": "Add Gate Pass",
    "/gate-keeper/broadcast-list": "Announcement List",
    "/gate-keeper/attendance/my-attendance": "My Attendance",
    "/gate-keeper/leave-request/my-requests": "My Leave Requests",
    "/gate-keeper/leave-request/my-requests/add": "Apply Leave",
    "/gate-keeper/escalation-management": "Escalation List",
    "/gate-keeper/escalation-management/add-escalation": "Add Escalation",
    "/gate-keeper/academic-calendar": "Academic Calendar",
    "/gate-keeper/notifications": "Notifications",
    "/gate-keeper/communication/inbox": "Communication Inbox",

    // ── Gate Keeper Manager Role ──────────────────────────────────────────────
    "/gatekeeper-manager/dashboard": "Dashboard",
    "/gatekeeper-manager/task-management/assign-tasks": "Assign Tasks List",
    "/gatekeeper-manager/task-management/assign-tasks/add": "Assign Task",
    "/gatekeeper-manager/task-management/my-tasks": "My Tasks",
    "/gatekeeper-manager/assign-duty-list": "Assign Duty List",
    "/gatekeeper-manager/assign-duty": "Assign New Duty",
    "/gatekeeper-manager/leave-request/my-requests": "My Leave Requests",
    "/gatekeeper-manager/leave-request/my-requests/add": "Apply Leave",
    "/gatekeeper-manager/leave-request/received": "Received Leave Requests",
    "/gatekeeper-manager/incidents-list": "Incidents Management List",
    "/gatekeeper-manager/gatekeeper-broadcast-list": "Announcement List",
    "/gatekeeper-manager/add-gatekeeper-broadcast": "Add Announcement",
    "/gatekeeper-manager/attendance/my-attendance": "My Attendance",
    "/gatekeeper-manager/attendance/gatekeepers-attendance": "Gatekeepers Attendance",
    "/gatekeeper-manager/escalation-management": "Escalation List",
    "/gatekeeper-manager/escalation-management/add-escalation": "Add Escalation",
    "/gatekeeper-manager/academic-calendar": "Calendar",
    "/gatekeeper-manager/notifications": "Notifications",
    "/gatekeeper-manager/communication/inbox": "Communication Inbox",

    // ── Canteen Manager Role ──────────────────────────────────────────────────
    "/canteen-manager/dashboard": "Dashboard",
    "/canteen-manager/menu-management": "Menu Management",
    "/canteen-manager/menu-management/add-menu-item": "Add Menu Item",
    "/canteen-manager/inventory": "Inventory Management",
    "/canteen-manager/orders": "Orders",
    "/canteen-manager/orders/add-order": "Add Order",
    "/canteen-manager/requests-approvals": "Requests & Approvals",
    "/canteen-manager/requests-approvals/add-request": "Add Request",
    "/canteen-manager/reports": "Reports",
    "/canteen-manager/broadcast": "Announcement",
    "/canteen-manager/broadcast/add-broadcast": "Add Announcement",

    // ── IT Support Team Manager Role ──────────────────────────────────────────
    "/it-support-manager/dashboard": "Dashboard",
    "/it-support-manager/maintenance-inventory": "Maintenance Inventory",
    "/it-support-manager/asset-management": "Asset Management",
    "/it-support-manager/asset-management/add-asset": "Add Asset",
    "/it-support-manager/support-tickets": "Support Tickets",
    "/it-support-manager/requests-approvals": "Requests & Approvals",
    "/it-support-manager/requests-approvals/add-request": "Add Request",
    "/it-support-manager/reports": "Reports",
    "/it-support-manager/broadcast": "Announcement",

    // ── Stationery Store Manager Role ─────────────────────────────────────────
    "/stationery-store-manager/dashboard": "Dashboard",
    "/stationery-store-manager/inventory": "Inventory",
    "/stationery-store-manager/inventory/add-item": "Add Inventory",
    "/stationery-store-manager/issue-returns": "Issue & Returns",
    "/stationery-store-manager/issue-returns/add": "Record Issue / Return",
    "/stationery-store-manager/requests-approvals": "Requests & Approvals",
    "/stationery-store-manager/requests-approvals/add-request": "Add Request",
    "/stationery-store-manager/reports": "Reports",
    "/stationery-store-manager/broadcast": "Announcement",

    // ── Housekeeping Manager Role ─────────────────────────────────────────────
    "/housekeeping-manager/dashboard": "Dashboard",
    "/housekeeping-manager/task-management/my-tasks": "My Tasks",
    "/housekeeping-manager/task-management/assign-tasks": "Assign Tasks List",
    "/housekeeping-manager/task-management/assign-tasks/add": "Assign Task",
    "/housekeeping-manager/inventory": "Inventory",
    "/housekeeping-manager/inventory/add-item": "Add Inventory",
    "/housekeeping-manager/requests-approvals": "Requests & Approvals",
    "/housekeeping-manager/requests-approvals/add-request": "Add Request",
    "/housekeeping-manager/reports": "Reports",
    "/housekeeping-manager/broadcast": "Announcement",

    // ── Teacher Role ──────────────────────────────────────────────────────────
    "/teacher/dashboard": "Dashboard",
    "/teacher/task-management/my-tasks": "My Tasks",
    "/teacher/attendance/my-attendance": "My Attendance",
    "/teacher/attendance/class-attendance": "Class Attendance",
    "/teacher/class/class-routine": "Class Timetable",
    "/teacher/class/extra-class": "Extended Class",
    "/teacher/class/extra-class/add": "Add Extended Class",
    "/teacher/class/online-class": "Online Class",
    "/teacher/class/online-class/add": "Add Online Class",
    "/teacher/class/leave-request": "Received Leave Requests",
    "/teacher/leave-request/my-requests": "My Leave Requests",
    "/teacher/leave-request/my-requests/add": "Apply Leave",
    "/teacher/leave-request/received": "Received Leave Requests",
    "/teacher/lesson-plan-approval": "Lesson Plan Approval",
    "/teacher/lesson-plan-approval/add": "Add Lesson Plan",
    "/teacher/lesson-plan/my-lesson-plan": "My Lesson Plan",
    "/teacher/student-allocation": "Student Allocation",
    "/teacher/student-deliverables/home-fun": "Home Fun",
    "/teacher/student-deliverables/home-fun/add": "Add Assignment / Homework",
    "/teacher/student-deliverables/study-materials": "Study Materials",
    "/teacher/student-deliverables/study-materials/add": "Add Study Material",
    "/teacher/student-deliverables/sample-questions": "Sample Questions",
    "/teacher/student-deliverables/sample-questions/add": "Add Sample Questions",
    "/teacher/unit-tests": "Unit Test",
    "/teacher/unit-tests/add": "Create Unit Test",
    "/teacher/student-evaluation/mark-entry": "Mark Entry",
    "/teacher/star-ratings/star-of-month": "Star of the Month",
    "/teacher/star-ratings/som-matrix": "Star of the Month",
    "/teacher/star-ratings/star-of-year": "Star of the Year",
    "/teacher/star-ratings/add-ratings": "Add SOM Rating",
    "/teacher/user-management/students-list": "Students List",
    "/teacher/user-management/parents-list": "Parents List",
    "/teacher/library/books-borrowed": "Books Borrowed",
    "/teacher/notifications": "Notifications",
    "/teacher/announcement": "Announcement List",
    "/teacher/escalation-management": "Escalation List",
    "/teacher/escalation-management/add-escalation": "Add Escalation",
    "/teacher/academic-calendar": "Calendar",
    "/teacher/communication/inbox": "Communication Inbox",

    // ── Coordinator Role ──────────────────────────────────────────────────────
    "/coordinator/dashboard": "Dashboard",
    "/coordinator/task-management/assign-tasks": "Assign Tasks List",
    "/coordinator/task-management/assign-tasks/add": "Assign Task",
    "/coordinator/task-management/my-tasks": "My Tasks",
    "/coordinator/attendance/my-attendance": "My Attendance",
    "/coordinator/attendance/class-attendance": "Class Attendance",
    "/coordinator/class/class-routine": "Class Timetable",
    "/coordinator/class/extra-class": "Extended Class",
    "/coordinator/class/extra-class/add": "Add Extended Class",
    "/coordinator/class/online-class": "Online Class",
    "/coordinator/class/online-class/add": "Add Online Class",
    "/coordinator/class/leave-request": "Received Leave Requests",
    "/coordinator/leave-request/my-requests": "My Leave Requests",
    "/coordinator/leave-request/my-requests/add": "Apply Leave",
    "/coordinator/leave-request/received": "Received Leave Requests",
    "/coordinator/lesson-plan-approval": "Lesson Plan Approval",
    "/coordinator/lesson-plan-approval/add": "Add Lesson Plan",
    "/coordinator/lesson-plan/my-lesson-plan": "My Lesson Plan",
    "/coordinator/student-allocation": "Student Allocation",
    "/coordinator/student-deliverables/home-fun": "Home Fun",
    "/coordinator/student-deliverables/home-fun/add": "Add Assignment / Homework",
    "/coordinator/student-deliverables/study-materials": "Study Materials",
    "/coordinator/student-deliverables/study-materials/add": "Add Study Material",
    "/coordinator/student-deliverables/sample-questions": "Sample Questions",
    "/coordinator/student-deliverables/sample-questions/add": "Add Sample Questions",
    "/coordinator/unit-tests": "Unit Test",
    "/coordinator/unit-tests/add": "Create Unit Test",
    "/coordinator/student-evaluation/mark-entry": "Mark Entry",
    "/coordinator/star-ratings/star-of-month": "Star of the Month",
    "/coordinator/star-ratings/som-matrix": "Star of the Month",
    "/coordinator/star-ratings/star-of-year": "Star of the Year",
    "/coordinator/star-ratings/add-ratings": "Add SOM Rating",
    "/coordinator/user-management/students-list": "Students List",
    "/coordinator/user-management/parents-list": "Parents List",
    "/coordinator/library/books-borrowed": "Books Borrowed",
    "/coordinator/notifications": "Notifications",
    "/coordinator/announcement": "Announcement List",
    "/coordinator/escalation-management": "Escalation List",
    "/coordinator/escalation-management/add-escalation": "Add Escalation",
    "/coordinator/academic-calendar": "Calendar",
    "/coordinator/communication/inbox": "Communication Inbox",

    // ── Transport Manager Role ────────────────────────────────────────────────
    "/transport-manager/dashboard": "Dashboard",
    "/transport-manager/driver-management": "Driver Management",
    "/transport-manager/vehicle-management": "Vehicle Management",
    "/transport-manager/vehicle-management/add-vehicle": "Add Vehicle",
    "/transport-manager/route-management": "Route Management",
    "/transport-manager/route-management/add-route": "Add Route",
    "/transport-manager/route-data": "Route Data",
    "/transport-manager/student-transport": "Student Transport",
    "/transport-manager/student-transport/add": "Add Student Transport",
    "/transport-manager/assign-duty": "Assign Duty",
    "/transport-manager/assign-duty/add": "Assign Duty",
    "/transport-manager/vehicle-maintenance": "Vehicle Maintenance",
    "/transport-manager/vehicle-maintenance/add": "Vehicle Maintenance",
    "/transport-manager/request-approvals": "Request & Approvals",
    "/transport-manager/transport-expenses": "Transport Expenses",
    "/transport-manager/leave-request": "Leave Request",

    // ── Joint Director Role ───────────────────────────────────────────────────
    "/joint-director/dashboard": "Dashboard",
    "/joint-director/task-management/my-tasks": "My Tasks",
    "/joint-director/task-management/assign-tasks": "Assign Tasks List",
    "/joint-director/task-management/assign-tasks/add": "Assign Task",
    "/joint-director/employee-management": "Employee Management",
    "/joint-director/employee-management/jd-assistant": "JD Assistant Profile",
    "/joint-director/employee-management/canteen-manager": "Canteen Manager Profile",
    "/joint-director/employee-management/store-manager": "Store Manager Profile",
    "/joint-director/employee-management/it-team-manager": "IT Team Manager Profile",
    "/joint-director/employee-management/transport-manager": "Transport Manager Profile",
    "/joint-director/employee-management/housekeeping-manager": "House Keeping Manager Profile",
    "/joint-director/employee-management/drivers": "Drivers List",
    "/joint-director/request-approvals": "Request Approvals",
    "/joint-director/request-approvals/view-request": "View Request Details",
    "/joint-director/escalations": "Escalations",
    "/joint-director/meetings-calendar": "Meetings & Calendar",
    "/joint-director/assets-inventory": "Assets & Inventory Overview",
    "/joint-director/broadcast": "Announcement",
    "/joint-director/broadcast/add-broadcast": "Add Announcement",

    // ── Joint Director Assistant Role ─────────────────────────────────────────
    "/joint-director-assistant/dashboard": "Dashboard",
    "/joint-director-assistant/task-management/my-tasks": "My Tasks",
    "/joint-director-assistant/task-management/assign-tasks": "Assign Tasks List",
    "/joint-director-assistant/task-management/assign-tasks/add": "Assign Task",
    "/joint-director-assistant/employee-management": "Employee Management",
    "/joint-director-assistant/employee-management/canteen-manager": "Canteen Manager Profile",
    "/joint-director-assistant/employee-management/store-manager": "Store Manager Profile",
    "/joint-director-assistant/employee-management/it-team-manager": "IT Team Manager Profile",
    "/joint-director-assistant/employee-management/transport-manager": "Transport Manager Profile",
    "/joint-director-assistant/employee-management/housekeeping-manager": "House Keeping Manager Profile",
    "/joint-director-assistant/employee-management/drivers": "Drivers List",
    "/joint-director-assistant/request-approvals": "Request Approvals",
    "/joint-director-assistant/request-approvals/view-request": "View Request Details",
    "/joint-director-assistant/escalations": "Escalations",
    "/joint-director-assistant/meetings-calendar": "Meetings & Calendar",
    "/joint-director-assistant/assets-inventory": "Assets & Inventory Overview",
    "/joint-director-assistant/broadcast": "Announcement",
    "/joint-director-assistant/broadcast/add-broadcast": "Add Announcement",

    // ── Joint Director Audit Role ───────────────────────────────────────────────
    "/joint-director-audit/dashboard": "Dashboard",
    "/joint-director-audit/audit-configuration": "Audit Configuration",
    "/joint-director-audit/audit-configuration/audit-templates": "Audit Templates",
    "/joint-director-audit/audit-configuration/checklist-sections": "Checklist Sections",
    "/joint-director-audit/audit-configuration/question-bank": "Question Bank",
    "/joint-director-audit/audit-configuration/response-types": "Response Types",
    "/joint-director-audit/audit-configuration/scoring-rules": "Scoring Rules",
    "/joint-director-audit/audit-configuration/workflow-rules": "Workflow Rules",
    "/joint-director-audit/audit-configuration/visibility-rules": "Visibility Rules",
    "/joint-director-audit/audit-configuration/template-versioning": "Template Versioning",
    "/joint-director-audit/audit-configuration/publish-templates": "Publish Templates",
    "/joint-director-audit/audit-assignment": "Audit Assignment",
    "/joint-director-audit/audit-assignment/assign-audits": "Assign Audits",
    "/joint-director-audit/audit-assignment/assignment-history": "Assignment History",
    "/joint-director-audit/audit-assignment/workload-overview": "Workload Overview",
    "/joint-director-audit/audit-assignment/reassign-audit": "Reassign Audit",
    "/joint-director-audit/audit-planning": "Audit Planning",
    "/joint-director-audit/audit-planning/add-audit-plan": "Add Audit Plan",
    "/joint-director-audit/audit-monitoring": "Audit Monitoring",
    "/joint-director-audit/findings-compliance": "Findings & Compliance",
    "/joint-director-audit/reports-analytics": "Reports & Analytics",
    "/joint-director-audit/task-management/my-tasks": "My Tasks",
    "/joint-director-audit/task-management/assign-tasks": "Assign Tasks List",
    "/joint-director-audit/task-management/assign-tasks/add": "Assign Task",
    "/joint-director-audit/employee-management": "Employee Management",
    "/joint-director-audit/employee-management/hr-manager": "HR Manager Profile",
    "/joint-director-audit/employee-management/hr-executive": "HR Executive Profile",
    "/joint-director-audit/employee-management/process-audit-manager": "Process Audit Manager Profile",
    "/joint-director-audit/employee-management/process-audit-executive": "Process Audit Executive Profile",
    "/joint-director-audit/employee-management/quality-audit-principal": "Quality Audit Principal Profile",
    "/joint-director-audit/employee-management/quality-audit-executive": "Quality Audit Executive Profile",
    "/joint-director-audit/request-approvals": "Request Approvals",
    "/joint-director-audit/request-approvals/view-request": "View Request Details",
    "/joint-director-audit/escalations": "Escalations",
    "/joint-director-audit/meetings-calendar": "Meetings & Calendar",
    "/joint-director-audit/broadcast": "Announcement",
    "/joint-director-audit/broadcast/add-broadcast": "Add Announcement",

    // ── Process Auditor Role ────────────────────────────────────────────────────
    "/process-auditor/dashboard": "Dashboard",
    "/process-auditor/audit-management/my-audits": "My Audits",
    "/process-auditor/audit-management/audit-schedule": "Audit Schedule",
    "/process-auditor/audit-management/execute-audit": "Execute Audit",
    "/process-auditor/audit-management/audit-history": "Audit History",
    "/process-auditor/observations/open": "Open Observations",
    "/process-auditor/observations/closed": "Closed Observations",
    "/process-auditor/observations/create": "Create Observation",
    "/process-auditor/corrective-actions/escalations": "Escalations",
    "/process-auditor/corrective-actions/escalations/create": "Escalate Observation",
    "/process-auditor/corrective-actions/root-cause-analysis": "Root Cause Analysis",
    "/process-auditor/corrective-actions/action-taken-reports": "Action Taken Reports",
    "/process-auditor/reports": "Reports",
    "/process-auditor/reports/audit-reports": "Audit Reports",
    "/process-auditor/reports/observation-reports": "Observation Reports",
    "/process-auditor/reports/compliance-reports": "Compliance Reports",
    "/process-auditor/reports/pending-actions": "Pending Actions",
    "/process-auditor/reports/closed-actions": "Closed Actions",
    "/process-auditor/communication": "Communication",

    // ── Quality Auditor Role ────────────────────────────────────────────────────
    "/quality-auditor/dashboard": "Dashboard",
    "/quality-auditor/audit-management/my-audits": "My Audits",
    "/quality-auditor/audit-management/audit-schedule": "Audit Schedule",
    "/quality-auditor/audit-management/execute-audit": "Execute Audit",
    "/quality-auditor/audit-management/audit-history": "Audit History",
    "/quality-auditor/observations/open": "Open Observations",
    "/quality-auditor/observations/closed": "Closed Observations",
    "/quality-auditor/observations/create": "Create Observation",
    "/quality-auditor/corrective-actions/escalations": "Escalations",
    "/quality-auditor/corrective-actions/escalations/create": "Escalate Observation",
    "/quality-auditor/corrective-actions/root-cause-analysis": "Root Cause Analysis",
    "/quality-auditor/corrective-actions/action-taken-reports": "Action Taken Reports",
    "/quality-auditor/reports": "Reports",
    "/quality-auditor/reports/audit-reports": "Audit Reports",
    "/quality-auditor/reports/observation-reports": "Observation Reports",
    "/quality-auditor/reports/compliance-reports": "Compliance Reports",
    "/quality-auditor/reports/pending-actions": "Pending Actions",
    "/quality-auditor/reports/closed-actions": "Closed Actions",
    "/quality-auditor/communication": "Communication",

    // ── HR Role ─────────────────────────────────────────────────────────────────
    "/hr/dashboard": "Dashboard",
    "/hr/employee-management": "Employee Management",
    "/hr/employee-management/employees": "Employees",
    "/hr/employee-management/employee-profile": "Employee Profile",
    "/hr/employee-management/documents": "Documents",
    "/hr/recruitment": "Recruitment",
    "/hr/recruitment/job-openings": "Job Openings",
    "/hr/recruitment/candidates": "Candidates",
    "/hr/recruitment/interviews": "Interviews",
    "/hr/onboarding-checklist": "Onboarding Checklist",
    "/hr/attendance": "Attendance",
    "/hr/leave-management": "Leave Management",
    "/hr/training": "Training",
    "/hr/performance-review": "Performance Review",
    "/hr/reports": "Reports",
    "/hr/recruitment/interview-feedback": "Interview Feedback",
    "/hr/onboarding/offers": "Offer Letters",
    "/hr/onboarding/appointment": "Appointment Letters",
    "/hr/onboarding/joiners": "New Joiner Details",
    "/hr/onboarding/observations": "New Joinee Observation",
    "/hr/onboarding/shadow-mentor": "Shadow Mentor",
    "/hr/leave-management/policies": "Leave Policies",
    "/hr/training-records": "Training Records",
    "/hr/training-feedback": "Training Feedback",
    "/hr/performance-comparison": "Performance Comparison",
    "/hr/performance-bsc": "BSC / Audit Score",
    "/hr/performance-increment": "Increment / Promotion",
    "/hr/payroll/salary-statement": "Salary Statement",
    "/hr/payroll/payslip": "Payslip",
    "/hr/payroll/salary-advance": "Salary Advance / Loan",
    "/hr/payroll/ctc": "CTC",
    "/hr/payroll/referral-bonus": "Referral Bonus",
    "/hr/payroll/child-concession": "Employee Child Concession",
    "/hr/payroll/claim-compensation": "Claim Compensation",
    "/hr/disciplinary": "Disciplinary Action",
    "/hr/exit": "Exit Formalities",
    "/hr/notifications": "Notifications",
    "/hr/announcements": "Announcements",
    "/hr/announcements/add": "Add Announcement",
    "/hr/announcements/view": "View Announcement",

    // ── Account Head Role ───────────────────────────────────────────────────────
    "/account-head/dashboard": "Finance Dashboard",
    "/account-head/task-management/my-tasks": "My Tasks",
    "/account-head/fees-management": "Fees Management",
    "/account-head/payment-vouchers": "Payment Vouchers",
    "/account-head/book-fee": "Book Fee",
    "/account-head/annual-budget": "Annual Budget",
    "/account-head/mfp": "MFP Report",
    "/account-head/transport-finance": "Transport Finance",
    "/account-head/collections": "Collections",
    "/account-head/wallet-management": "Wallet Management",
    "/account-head/accounting": "Accounting",
    "/account-head/accounting/day-book": "Day Book",
    "/account-head/accounting/online-book": "Online Book",
    "/account-head/accounting/general-ledger": "General Ledger",
    "/account-head/accounting/cash-book": "Cash Book",
    "/account-head/accounting/bank-book": "Bank Book",
    "/account-head/accounting/chart-of-accounts": "Chart of Accounts",
    "/account-head/accounting/journal-vouchers": "Journal Vouchers",
    "/account-head/accounting/bank-reconciliation": "Bank Reconciliation",
    "/account-head/accounting/financial-statements": "Financial Statements",
    "/account-head/approvals": "Approvals",
    "/account-head/reports-analytics": "Reports & Analytics",
    "/account-head/settings": "Settings",

    // Driver
    "/driver/dashboard": "Dashboard",
    "/driver/vehicle-management/vehicle-details": "Vehicle Details List",
    "/driver/vehicle-management/vehicle-documents": "Vehicle Documents List",
    "/driver/vehicle-management/vehicle-health-status": "Vehicle Health Status List",
    "/driver/vehicle-management/vehicle-health-status/add": "Add Vehicle Health Status",
    "/driver/my-duty": "My Duty List",
    "/driver/my-route/route-details": "Route Details",
    "/driver/my-route/route-stops": "Route Stops List",
    "/driver/attendance-management/student-attendance": "Student Attendance",
    "/driver/attendance-management/attendance-history": "Attendance History",
    "/driver/fuel-request": "Fuel Request List",
    "/driver/fuel-request/add": "Add Fuel Request",
    "/driver/maintenance-request": "Maintenance Request List",
    "/driver/maintenance-request/add": "Add Maintenance Request",
    "/driver/leave-request": "Leave Request List",
    "/driver/leave-request/add": "Add Leave Request",

    // ── Principal Role ──────────────────────────────────────────────────────────
    "/principal/dashboard": "Dashboard",
    "/principal/task-management/assign-tasks": "Assign Tasks List",
    "/principal/task-management/assign-tasks/add": "Assign Task",
    "/principal/task-management/my-tasks": "My Tasks",
    "/principal/star-ratings/star-of-month": "Star of the Month",
    "/principal/star-ratings/star-of-year": "Star of the Year",
    "/principal/star-ratings/add-ratings": "Add SOM Rating",
    "/principal/examination-timetable": "Examination Timetable List",
    "/principal/create-examination-timetable": "Create Examination Timetable",
    "/principal/class-timetable": "Class Timetable List",
    "/principal/create-class-timetable": "Create Class Timetable",
    "/principal/user-management/student-database": "Student Database",
    "/principal/user-management/employee-database": "Employee Database",
    "/principal/lms/student-lms": "Student Home Fun",
    "/principal/lms/view-student-lms": "View Student Home Fun Details",
    "/principal/lms/teacher-lms": "Teacher Home Fun",
    "/principal/lms/view-teacher-lms": "View Teacher Home Fun Details",
    "/principal/escalation-management": "Escalation List",
    "/principal/escalation-management/add-escalation": "Add Escalation",
    "/principal/academic-calendar": "Calendar",
    "/principal/notifications": "Notifications",
    "/principal/announcement": "Announcement List",
    "/principal/announcement/add": "Add Announcement",
    "/principal/academic/teacher-allocation": "Teacher Allocation",
    "/principal/academic/teacher-allocation/allocate": "Allocate Teacher",
    "/principal/academic/teacher-allocation/view": "View Teacher Allocation",
    "/principal/academic/teacher-allocation/edit": "Edit Teacher Allocation",
    "/principal/student-allocation-approval": "Student Allocation Approval",
    "/principal/communication/inbox": "Communication Inbox",
    "/principal/leave-request/my-requests": "My Leave Requests",
    "/principal/leave-request/my-requests/add": "Apply Leave",
    "/principal/leave-request/received": "Received Leave Requests",
    "/principal/attendance/my-attendance": "My Attendance",

    // ── Director Role ─────────────────────────────────────────────────────────
    "/director/dashboard": "Dashboard",
    "/director/broadcast": "Announcement",
    "/director/broadcast/add-broadcast": "Add Announcement",
    "/director/task-management/assign-tasks": "Assign Tasks List",
    "/director/task-management/assign-tasks/add": "Assign Task",
    "/director/task-management/my-tasks": "My Tasks",
    "/director/star-ratings/star-of-month": "Star of the Month",
    "/director/star-ratings/star-of-year": "Star of the Year",
    "/director/star-ratings/add-ratings": "Add SOM Rating",
    "/director/examination-approvals": "Exam Timetable Approvals",
    "/director/class-timetable-approvals": "Class Timetable Approvals",
    "/director/user-management/student-database": "Student Database",
    "/director/student-allocation-approval": "Student Allocation Approval",
    "/director/student-allocation": "Student Allocation Approval",
    "/director/user-management/employee-database": "Employee Database",
    "/director/student-transfer": "Student Transfer List",
    "/director/student-transfer/add": "Add Student Transfer",
    "/director/activities/cultural-list": "Cultural List",
    "/director/activities/add-cultural": "Add Cultural Information",
    "/director/activities/sports-list": "Sports List",
    "/director/activities/add-sports": "Add Sports Information",
    "/director/activities/chess-result": "Chess Result",
    "/director/activities/competitions-list": "Competitions List",
    "/director/activities/add-competition": "Add Competition Information",
    "/director/lms/student-lms": "Student Home Fun",
    "/director/lms/view-student-lms": "View Student Home Fun Details",
    "/director/lms/teacher-lms": "Teacher Home Fun",
    "/director/lms/view-teacher-lms": "View Teacher Home Fun Details",
    "/director/request-approvals": "Request Approvals",
    "/director/request-approvals/view-request": "View Request Details",
    "/director/escalation-management": "Escalation List",
    "/director/escalation-management/add-escalation": "Add Escalation",
    "/director/leave-request/my-requests": "My Leave Requests",
    "/director/leave-request/my-requests/add": "Apply Leave",
    "/director/leave-request/received": "Received Leave Requests",
    "/director/attendance/my-attendance": "My Attendance",
    "/director/lesson-plan-approval": "Lesson Plan Approval",
    "/director/mark-entry-approval": "Mark Entry Approval",
    "/director/mark-entry-approval/review/:contextKey": "Review Mark Entry",
    "/director/academic-calendar": "Calendar",
    "/director/notifications": "Notifications",
    "/director/communication/inbox": "Communication Inbox",
}

/** Paths with params never equal `location.pathname`; match with prefixes / patterns here */
const dynamicTitleMatchers = [
    { test: (p) => /^\/teacher\/lesson-plan-approval\/group\/[^/]+\/[^/]+$/.test(p), title: 'Lesson Plan Group' },
    { test: (p) => /^\/teacher\/lesson-plan\/my-lesson-plan\/group\/[^/]+\/[^/]+$/.test(p), title: 'My Lesson Plan Group' },
    { test: (p) => /^\/coordinator\/lesson-plan-approval\/group\/[^/]+\/[^/]+$/.test(p), title: 'Lesson Plan Group' },
    { test: (p) => /^\/coordinator\/lesson-plan\/my-lesson-plan\/group\/[^/]+\/[^/]+$/.test(p), title: 'My Lesson Plan Group' },
    { test: (p) => /^\/director\/lesson-plan-approval\/group\/[^/]+\/[^/]+$/.test(p), title: 'Lesson Plan Review' },
    { test: (p) => /^\/admin\/front-office\/view-librarian\/[^/]+$/.test(p), title: 'Librarian Details' },
    { test: (p) => /^\/admin\/front-office\/view-driver\/[^/]+$/.test(p), title: 'Driver Details' },
    { test: (p) => /^\/admin\/front-office\/admission-list\/view\/[^/]+$/.test(p), title: 'Admission Details' },
    { test: (p) => /^\/admin\/front-office\/view-admission\/[^/]+$/.test(p), title: 'Admission Details' },
    { test: (p) => /^\/admin\/front-office\/view-admission-enquiry\/[^/]+$/.test(p), title: 'Admission Enquiry Details' },
    { test: (p) => /^\/admin\/front-office\/admission-enquiry\/view\/[^/]+$/.test(p), title: 'Admission Enquiry Details' },
    { test: (p) => /^\/admin\/front-office\/admission-enquiry\/edit\/[^/]+$/.test(p), title: 'Edit Admission Enquiry' },
    { test: (p) => /^\/front-office\/admission-enquiry\/view\/[^/]+$/.test(p), title: 'Admission Enquiry Details' },
    { test: (p) => /^\/front-office\/admission-enquiry\/edit\/[^/]+$/.test(p), title: 'Edit Admission Enquiry' },
    { test: (p) => /^\/front-office\/admission-list\/view\/[^/]+$/.test(p), title: 'Admission Details' },
    { test: (p) => /^\/front-office\/admission-list\/edit\/[^/]+$/.test(p), title: 'Edit Admission' },
    { test: (p) => /^\/admin\/student\/view-student-details\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/admin\/class\/view-online-class\/[^/]+$/.test(p), title: 'Online Class Details' },
    { test: (p) => /^\/admin\/class\/view-extended-class\/[^/]+$/.test(p), title: 'Extended Class Details' },
    { test: (p) => /^\/admin\/class\/view-timetable\/[^/]+$/.test(p), title: 'Time Table Details' },
    { test: (p) => /^\/admin\/class\/view-subject\/[^/]+$/.test(p), title: 'Subject Details' },
    { test: (p) => /^\/admin\/activities\/view-cultural\/[^/]+$/.test(p), title: 'Cultural Activity Details' },
    { test: (p) => /^\/admin\/activities\/edit-cultural\/[^/]+$/.test(p), title: 'Edit Cultural Activity' },
    { test: (p) => /^\/admin\/activities\/view-sports\/[^/]+$/.test(p), title: 'Sports Activity Details' },
    { test: (p) => /^\/admin\/activities\/edit-sports\/[^/]+$/.test(p), title: 'Edit Sports Activity' },
    { test: (p) => /^\/admin\/activities\/view-competition\/[^/]+$/.test(p), title: 'Competition Activity Details' },
    { test: (p) => /^\/admin\/activities\/edit-competition\/[^/]+$/.test(p), title: 'Edit Competition Activity' },
    { test: (p) => /^\/front-office\/student-re-enrollment\/view\/[^/]+$/.test(p), title: 'View Student Re-Enrollment' },
    { test: (p) => /^\/front-office\/student-re-enrollment\/edit\/[^/]+$/.test(p), title: 'Edit Student Re-Enrollment' },
    { test: (p) => /^\/front-office\/student-management\/view\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/front-office\/student-gate-pass\/view\/[^/]+$/.test(p), title: 'View Student Gate Pass' },
    { test: (p) => /^\/front-office\/student-gate-pass\/edit\/[^/]+$/.test(p), title: 'Edit Student Gate Pass' },
    { test: (p) => /^\/front-office\/hostel-gate-pass\/view\/[^/]+$/.test(p), title: 'View Hostel Gate Pass' },
    { test: (p) => /^\/front-office\/hostel-gate-pass\/edit\/[^/]+$/.test(p), title: 'Edit Hostel Gate Pass' },
    { test: (p) => /^\/front-office\/admission-list\/view\/[^/]+$/.test(p), title: 'View Admission Details' },
    { test: (p) => /^\/admin\/front-office\/admission-list\/view\/[^/]+$/.test(p), title: 'View Admission Details' },
    { test: (p) => /^\/director\/user-management\/student-database\/view\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/director\/user-management\/employee-database\/view\/[^/]+$/.test(p), title: 'View Employee Details' },
    { test: (p) => /^\/director\/student-allocation-approval\/review\/[^/]+$/.test(p), title: 'Review Student Allocation' },
    { test: (p) => /^\/director\/student-allocation\/allocate\/[^/]+$/.test(p), title: 'Review Student Allocation' },
    { test: (p) => /^\/director\/student-allocation\/review\/[^/]+$/.test(p), title: 'Review Student Allocation' },
    { test: (p) => /^\/principal\/student-allocation-approval\/review\/[^/]+$/.test(p), title: 'Review Student Allocation' },
    { test: (p) => /^\/teacher\/student-allocation\/allocate\/[^/]+$/.test(p), title: 'Allocate Student Section' },
    { test: (p) => /^\/coordinator\/student-allocation\/allocate\/[^/]+$/.test(p), title: 'Allocate Student Section' },
    { test: (p) => /^\/director\/activities\/view-cultural\/[^/]+$/.test(p), title: 'Cultural Activity Details' },
    { test: (p) => /^\/director\/activities\/edit-cultural\/[^/]+$/.test(p), title: 'Edit Cultural Activity' },
    { test: (p) => /^\/director\/activities\/view-sports\/[^/]+$/.test(p), title: 'Sports Activity Details' },
    { test: (p) => /^\/director\/activities\/edit-sports\/[^/]+$/.test(p), title: 'Edit Sports Activity' },
    { test: (p) => /^\/director\/activities\/view-competition\/[^/]+$/.test(p), title: 'Competition Activity Details' },
    { test: (p) => /^\/director\/activities\/edit-competition\/[^/]+$/.test(p), title: 'Edit Competition Activity' },
    { test: (p) => /^\/admin\/documents\/view-student-documents\/[^/]+$/.test(p), title: 'Student Document Details' },
    { test: (p) => /^\/admin\/documents\/edit-student-documents\/[^/]+$/.test(p), title: 'Edit Student Documents' },
    { test: (p) => /^\/admin\/documents\/edit-employee-documents\/[^/]+$/.test(p), title: 'Edit Employee Documents' },
    { test: (p) => /^\/front-office\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/front-office\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/front-office\/material-gate-pass\/view\/[^/]+$/.test(p), title: 'View Material Gate Pass' },
    { test: (p) => /^\/front-office\/material-gate-pass\/edit\/[^/]+$/.test(p), title: 'Edit Material Gate Pass' },
    { test: (p) => /^\/front-office\/goods-received-pass\/view\/[^/]+$/.test(p), title: 'View Goods Received Pass' },
    { test: (p) => /^\/front-office\/goods-received-pass\/edit\/[^/]+$/.test(p), title: 'Edit Goods Received Pass' },
    { test: (p) => /^\/admin\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/front-office\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/gatekeeper-manager\/gatekeeper-broadcast-list\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/principal\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/teacher\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/coordinator\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/admin\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/admin\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/director\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/director\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/principal\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/principal\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/teacher\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/teacher\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/coordinator\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/coordinator\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/joint-director\/employee-management\/drivers\/view\/[^/]+$/.test(p), title: 'View Driver Details' },
    { test: (p) => /^\/joint-director-audit\/findings-compliance\/view\/[^/]+$/.test(p), title: 'Finding Details' },
    { test: (p) => /^\/joint-director-audit\/audit-monitoring\/view\/[^/]+$/.test(p), title: 'Audit Monitoring Details' },
    { test: (p) => /^\/joint-director-audit\/audit-planning\/view\/[^/]+$/.test(p), title: 'View Audit Plan' },
    { test: (p) => /^\/joint-director-audit\/audit-planning\/edit\/[^/]+$/.test(p), title: 'Edit Audit Plan' },
    { test: (p) => /^\/joint-director-audit\/escalations\/view-escalation\/[^/]+$/.test(p), title: 'View Escalation Details' },
    { test: (p) => /^\/joint-director-audit\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/joint-director-assistant\/escalations\/view-escalation\/[^/]+$/.test(p), title: 'View Escalation Details' },
    { test: (p) => /^\/joint-director-assistant\/assets-inventory\/view\/[^/]+$/.test(p), title: 'View Asset / Inventory Details' },
    { test: (p) => /^\/joint-director\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/director\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/gate-keeper\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/gate-keeper\/incidents\/[^/]+$/.test(p), title: 'CSO / Gate Keeper' },
    { test: (p) => /^\/joint-director\/escalations\/view-escalation\/[^/]+$/.test(p), title: 'View Escalation Details' },
    { test: (p) => /^\/joint-director\/assets-inventory\/view\/[^/]+$/.test(p), title: 'View Asset / Inventory Details' },
    {
        test: (p) =>
            /^\/(admin|director|front-office|gate-keeper|gatekeeper-manager|librarian|principal|student|teacher|coordinator)\/escalation-management\/view\/[^/]+$/.test(
                p,
            ),
        title: 'View Escalation Details',
    },
    {
        test: (p) =>
            /^\/(admin|director|front-office|gate-keeper|gatekeeper-manager|librarian|principal|student|teacher|coordinator)\/communication\/inbox\/[^/]+$/.test(
                p,
            ),
        title: 'Communication Inbox',
    },
    { test: (p) => /^\/principal\/academic\/teacher-allocation\/allocate\/[^/]+$/.test(p), title: 'Allocate Teacher' },
    { test: (p) => /^\/principal\/academic\/teacher-allocation\/view\/[^/]+$/.test(p), title: 'View Teacher Allocation' },
    { test: (p) => /^\/principal\/academic\/teacher-allocation\/edit\/[^/]+$/.test(p), title: 'Edit Teacher Allocation' },
    { test: (p) => /^\/principal\/user-management\/student-database\/view\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/principal\/user-management\/employee-database\/view\/[^/]+$/.test(p), title: 'View Employee Details' },
    { test: (p) => /^\/admin\/user-management\/student-database\/view\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/admin\/user-management\/employee-database\/view\/[^/]+$/.test(p), title: 'View Employee Details' },
    { test: (p) => /^\/super-admin\/user-database\/students\/view\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/super-admin\/user-database\/employees\/view\/[^/]+$/.test(p), title: 'View Employee Details' },
    { test: (p) => /^\/super-admin\/gate-pass\/view\/[^/]+$/.test(p), title: 'View Gate Pass' },
    { test: (p) => /^\/super-admin\/activity-logs\/view\/[^/]+$/.test(p), title: 'View Activity Log' },
    { test: (p) => /^\/super-admin\/approvals\/view\/[^/]+$/.test(p), title: 'View Approval Request' },
    { test: (p) => /^\/super-admin\/user-creation\/view\/[^/]+$/.test(p), title: 'View Admin User' },
    { test: (p) => /^\/parent\/student-deliverables\/home-fun\/view\/[^/]+$/.test(p), title: 'View Assignment / Homework Details' },
    { test: (p) => /^\/parent\/student-deliverables\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/parent\/student-deliverables\/sample-questions\/view\/[^/]+$/.test(p), title: 'View Sample Questions' },
    { test: (p) => /^\/student\/student-deliverables\/home-fun\/view\/[^/]+$/.test(p), title: 'View Assignment / Homework Details' },
    { test: (p) => /^\/student\/student-deliverables\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/student\/student-deliverables\/sample-questions\/view\/[^/]+$/.test(p), title: 'View Sample Questions' },
    { test: (p) => /^\/teacher\/student-deliverables\/home-fun\/view\/[^/]+$/.test(p), title: 'View Assignment / Homework Details' },
    { test: (p) => /^\/hr\/employee-management\/employee-profile\/[^/]+$/.test(p), title: 'Employee Profile' },
    { test: (p) => /^\/process-auditor\/audit-management\/my-audits\/view\/[^/]+$/.test(p), title: 'View Audit Details' },
    { test: (p) => /^\/process-auditor\/observations\/view\/[^/]+$/.test(p), title: 'View Observation' },
    { test: (p) => /^\/process-auditor\/corrective-actions\/escalations\/view\/[^/]+$/.test(p), title: 'View Escalation' },
    { test: (p) => /^\/process-auditor\/corrective-actions\/root-cause-analysis\/view\/[^/]+$/.test(p), title: 'View Root Cause Analysis' },
    { test: (p) => /^\/process-auditor\/corrective-actions\/action-taken-reports\/view\/[^/]+$/.test(p), title: 'View Action Taken Report' },
    { test: (p) => /^\/process-auditor\/reports\/audit-reports\/view\/[^/]+$/.test(p), title: 'Audit Report View' },
    { test: (p) => /^\/process-auditor\/reports\/observation-reports\/view\/[^/]+$/.test(p), title: 'Observation Report View' },
    { test: (p) => /^\/quality-auditor\/audit-management\/my-audits\/view\/[^/]+$/.test(p), title: 'View Audit Details' },
    { test: (p) => /^\/quality-auditor\/observations\/view\/[^/]+$/.test(p), title: 'View Observation' },
    { test: (p) => /^\/quality-auditor\/corrective-actions\/escalations\/view\/[^/]+$/.test(p), title: 'View Escalation' },
    { test: (p) => /^\/quality-auditor\/corrective-actions\/root-cause-analysis\/view\/[^/]+$/.test(p), title: 'View Root Cause Analysis' },
    { test: (p) => /^\/quality-auditor\/corrective-actions\/action-taken-reports\/view\/[^/]+$/.test(p), title: 'View Action Taken Report' },
    { test: (p) => /^\/quality-auditor\/reports\/audit-reports\/view\/[^/]+$/.test(p), title: 'Audit Report View' },
    { test: (p) => /^\/quality-auditor\/reports\/observation-reports\/view\/[^/]+$/.test(p), title: 'Observation Report View' },
    { test: (p) => /^\/canteen-manager\/menu-management\/view-menu\/[^/]+$/.test(p), title: 'View Menu Item Details' },
    { test: (p) => /^\/canteen-manager\/orders\/view-order\/[^/]+$/.test(p), title: 'View Order Details' },
    { test: (p) => /^\/canteen-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/canteen-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/it-support-manager\/asset-management\/view-asset\/[^/]+$/.test(p), title: 'View Asset Details' },
    { test: (p) => /^\/it-support-manager\/support-tickets\/view-ticket\/[^/]+$/.test(p), title: 'View Support Ticket' },
    { test: (p) => /^\/it-support-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/it-support-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/stationery-store-manager\/inventory\/view-item\/[^/]+$/.test(p), title: 'View Inventory Item' },
    { test: (p) => /^\/stationery-store-manager\/issue-returns\/view\/[^/]+$/.test(p), title: 'View Issue / Return' },
    { test: (p) => /^\/stationery-store-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/stationery-store-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/transport-manager\/driver-management\/view\/[^/]+$/.test(p), title: 'View Driver Details' },
    { test: (p) => /^\/transport-manager\/vehicle-management\/view\/[^/]+$/.test(p), title: 'View Vehicle Details' },
    { test: (p) => /^\/transport-manager\/vehicle-management\/edit\/[^/]+$/.test(p), title: 'Edit Vehicle' },
    { test: (p) => /^\/transport-manager\/route-management\/view\/[^/]+$/.test(p), title: 'View Route Details' },
    { test: (p) => /^\/transport-manager\/route-management\/edit\/[^/]+$/.test(p), title: 'Edit Route' },
    { test: (p) => /^\/transport-manager\/route-data\/track\/[^/]+$/.test(p), title: 'Track Bus Location' },
    { test: (p) => /^\/transport-manager\/student-transport\/view\/[^/]+$/.test(p), title: 'View Student Transport' },
    { test: (p) => /^\/transport-manager\/assign-duty\/view\/[^/]+$/.test(p), title: 'View Assign Duty' },
    { test: (p) => /^\/transport-manager\/vehicle-maintenance\/view\/[^/]+$/.test(p), title: 'View Vehicle Maintenance' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/add\/fuel$/.test(p), title: 'Add Fuel Expense' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/add\/service$/.test(p), title: 'Add Service Expense' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/add\/other$/.test(p), title: 'Add Other Expense' },
    { test: (p) => /^\/transport-manager\/leave-request\/view\/[^/]+$/.test(p), title: 'View Leave Request' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/view\/[^/]+\/[^/]+$/.test(p), title: 'View Transport Expense' },
    { test: (p) => /^\/teacher\/class\/extra-class\/view\/[^/]+$/.test(p), title: 'View Extended Class' },
    { test: (p) => /^\/teacher\/class\/online-class\/view\/[^/]+$/.test(p), title: 'View Online Class' },
    { test: (p) => /^\/teacher\/academics\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/teacher\/student-deliverables\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/teacher\/student-deliverables\/sample-questions\/view\/[^/]+$/.test(p), title: 'View Sample Questions' },
    { test: (p) => /^\/teacher\/unit-tests\/view\/[^/]+$/.test(p), title: 'View Unit Test' },
    { test: (p) => /^\/teacher\/user-management\/students-list\/view\/[^/]+$/.test(p), title: 'View Student Profile' },
    { test: (p) => /^\/teacher\/user-management\/students-list\/view\/[^/]+\/full$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/coordinator\/class\/extra-class\/view\/[^/]+$/.test(p), title: 'View Extended Class' },
    { test: (p) => /^\/coordinator\/class\/online-class\/view\/[^/]+$/.test(p), title: 'View Online Class' },
    { test: (p) => /^\/coordinator\/student-deliverables\/home-fun\/view\/[^/]+$/.test(p), title: 'View Assignment / Homework Details' },
    { test: (p) => /^\/coordinator\/student-deliverables\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/coordinator\/student-deliverables\/sample-questions\/view\/[^/]+$/.test(p), title: 'View Sample Questions' },
    { test: (p) => /^\/coordinator\/unit-tests\/view\/[^/]+$/.test(p), title: 'View Unit Test' },
    { test: (p) => /^\/coordinator\/user-management\/students-list\/view\/[^/]+$/.test(p), title: 'View Student Profile' },
    { test: (p) => /^\/coordinator\/user-management\/students-list\/view\/[^/]+\/full$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/gatekeeper-manager\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/gatekeeper-manager\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'Review Leave Request' },
    { test: (p) => /^\/gate-keeper\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/driver\/leave-request\/view\/[^/]+$/.test(p), title: 'View Leave Request' },
    { test: (p) => /^\/driver\/leave-request\/edit\/[^/]+$/.test(p), title: 'Edit Leave Request' },
    { test: (p) => /^\/driver\/maintenance-request\/view\/[^/]+$/.test(p), title: 'View Maintenance Request' },
    { test: (p) => /^\/driver\/maintenance-request\/edit\/[^/]+$/.test(p), title: 'Edit Maintenance Request' },
    { test: (p) => /^\/driver\/fuel-request\/view\/[^/]+$/.test(p), title: 'View Fuel Request' },
    { test: (p) => /^\/driver\/fuel-request\/edit\/[^/]+$/.test(p), title: 'Edit Fuel Request' },
    { test: (p) => /^\/driver\/vehicle-management\/vehicle-health-status\/view\/[^/]+$/.test(p), title: 'View Vehicle Health Status' },
    { test: (p) => /^\/driver\/vehicle-management\/vehicle-health-status\/edit\/[^/]+$/.test(p), title: 'Edit Vehicle Health Status' },
    { test: (p) => /^\/housekeeping-manager\/inventory\/view-item\/[^/]+$/.test(p), title: 'View Inventory Item' },
    { test: (p) => /^\/housekeeping-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/housekeeping-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
]

export function getPageTitle(pathname) {
    const path = (pathname || '').replace(/\/+$/, '') || '/'
    const exact = singleTitleMapping[path]
    if (exact != null) return exact
    const hit = dynamicTitleMatchers.find((m) => m.test(path))
    return hit?.title || 'School ERP'
}
