export const ROUTE_BASE = '/super-admin/activity-logs'

export const LOG_TYPES = {
    'login-history': {
        key: 'login-history',
        label: 'Login History',
        route: `${ROUTE_BASE}/login-history`,
        listTitle: 'Login History',
        searchPlaceholder: 'User, email, role, IP...',
    },
    'data-changes': {
        key: 'data-changes',
        label: 'Data Changes',
        route: `${ROUTE_BASE}/data-changes`,
        listTitle: 'Data Changes',
        searchPlaceholder: 'User, module, record, field...',
    },
    'deleted-records': {
        key: 'deleted-records',
        label: 'Deleted Records',
        route: `${ROUTE_BASE}/deleted-records`,
        listTitle: 'Deleted Records',
        searchPlaceholder: 'User, module, record ID, name...',
    },
    'approval-actions': {
        key: 'approval-actions',
        label: 'Approval Actions',
        route: `${ROUTE_BASE}/approval-actions`,
        listTitle: 'Approval Actions',
        searchPlaceholder: 'Approver, module, reference...',
    },
    'audit-logs': {
        key: 'audit-logs',
        label: 'Audit Logs',
        route: `${ROUTE_BASE}/audit-logs`,
        listTitle: 'Audit Logs',
        searchPlaceholder: 'Auditor, audit type, scope...',
    },
    'failed-logins': {
        key: 'failed-logins',
        label: 'Failed Logins',
        route: `${ROUTE_BASE}/failed-logins`,
        listTitle: 'Failed Logins',
        searchPlaceholder: 'Email, username, IP, reason...',
    },
}

export const statusBadgeColor = {
    Success: 'bg-[#4CAF5033] text-[#4CAF50]',
    Failed: 'bg-[#FF000033] text-[#FF0000]',
    Approved: 'bg-[#4CAF5033] text-[#4CAF50]',
    Rejected: 'bg-[#FF000033] text-[#FF0000]',
    Pending: 'bg-[#FF980033] text-[#FF9800]',
    Completed: 'bg-[#4CAF5033] text-[#4CAF50]',
    'In Progress': 'bg-[#2196F333] text-[#2196F3]',
    Restored: 'bg-[#2196F333] text-[#2196F3]',
    Blocked: 'bg-[#FF000033] text-[#FF0000]',
    Logout: 'bg-[#607D8B33] text-[#607D8B]',
}

export const LOGIN_HISTORY_LOGS = [
    {
        id: 'log-lh-001',
        logType: 'login-history',
        timestamp: '08-08-2026 08:45 AM',
        user: 'Super Admin',
        userEmail: 'superadmin@school.com',
        role: 'Super Admin',
        ipAddress: '192.168.10.12',
        device: 'Chrome 126 · Windows 11',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-SA-88421',
    },
    {
        id: 'log-lh-002',
        logType: 'login-history',
        timestamp: '08-08-2026 08:12 AM',
        user: 'School Admin',
        userEmail: 'admin@school.com',
        role: 'Administrator',
        ipAddress: '192.168.10.18',
        device: 'Edge 125 · Windows 11',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-AD-77210',
    },
    {
        id: 'log-lh-003',
        logType: 'login-history',
        timestamp: '08-08-2026 07:55 AM',
        user: 'Murugan P.',
        userEmail: 'gatekeeper@school.com',
        role: 'Gate Keeper',
        ipAddress: '192.168.10.60',
        device: 'Firefox 127 · Android 13',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-GK-88319',
    },
    {
        id: 'log-lh-004',
        logType: 'login-history',
        timestamp: '07-08-2026 04:30 PM',
        user: 'Dr. Priya Nair',
        userEmail: 'principal@school.com',
        role: 'Principal',
        ipAddress: '10.0.0.54',
        device: 'Safari 17 · macOS',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-PR-66109',
    },
    {
        id: 'log-lh-005',
        logType: 'login-history',
        timestamp: '07-08-2026 09:05 AM',
        user: 'Ravi Kumar',
        userEmail: 'teacher@school.com',
        role: 'Teacher',
        ipAddress: '192.168.20.44',
        device: 'Chrome 126 · Android 14',
        location: 'Madurai, IN',
        status: 'Success',
        sessionId: 'SES-TC-55008',
    },
    {
        id: 'log-lh-006',
        logType: 'login-history',
        timestamp: '07-08-2026 08:40 AM',
        user: 'Meena Lakshmi',
        userEmail: 'parent@school.com',
        role: 'Parent',
        ipAddress: '103.45.88.12',
        device: 'Chrome 126 · iOS 17',
        location: 'Coimbatore, IN',
        status: 'Success',
        sessionId: 'SES-PT-54907',
    },
    {
        id: 'log-lh-007',
        logType: 'login-history',
        timestamp: '06-08-2026 03:20 PM',
        user: 'Arjun Sharma',
        userEmail: 'student@school.com',
        role: 'Student',
        ipAddress: '103.45.88.45',
        device: 'Chrome 125 · Windows 11',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-ST-44806',
    },
    {
        id: 'log-lh-008',
        logType: 'login-history',
        timestamp: '06-08-2026 05:10 PM',
        user: 'School Admin',
        userEmail: 'admin@school.com',
        role: 'Administrator',
        ipAddress: '192.168.10.18',
        device: 'Edge 125 · Windows 11',
        location: 'Chennai, IN',
        status: 'Logout',
        sessionId: 'SES-AD-77210',
    },
    {
        id: 'log-lh-009',
        logType: 'login-history',
        timestamp: '05-08-2026 10:15 AM',
        user: 'Selvam R.',
        userEmail: 'store@school.com',
        role: 'Stationery Store Manager',
        ipAddress: '192.168.10.45',
        device: 'Chrome 126 · Windows 10',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-SS-33705',
    },
    {
        id: 'log-lh-010',
        logType: 'login-history',
        timestamp: '05-08-2026 09:00 AM',
        user: 'Kavitha S.',
        userEmail: 'coordinator@school.com',
        role: 'Coordinator',
        ipAddress: '192.168.10.22',
        device: 'Chrome 126 · Windows 11',
        location: 'Chennai, IN',
        status: 'Success',
        sessionId: 'SES-CR-33604',
    },
]

export const DATA_CHANGES_LOGS = [
    {
        id: 'log-dc-001',
        logType: 'data-changes',
        timestamp: '08-08-2026 10:22 AM',
        user: 'School Admin',
        userEmail: 'admin@school.com',
        role: 'Administrator',
        module: 'Student Database',
        recordId: 'STD-NO1845',
        recordName: 'Sandy Selva',
        fieldChanged: 'Mobile Number',
        oldValue: '9944076990',
        newValue: '9944076993',
        changeType: 'Update',
        ipAddress: '192.168.10.18',
    },
    {
        id: 'log-dc-002',
        logType: 'data-changes',
        timestamp: '08-08-2026 09:48 AM',
        user: 'Front Office',
        userEmail: 'frontoffice@school.com',
        role: 'Front Office',
        module: 'Admission List',
        recordId: 'ADM-2026-112',
        recordName: 'Priya Venkatesh — Grade 8',
        fieldChanged: 'Admission Status',
        oldValue: 'Pending',
        newValue: 'Confirmed',
        changeType: 'Update',
        ipAddress: '192.168.10.30',
    },
    {
        id: 'log-dc-003',
        logType: 'data-changes',
        timestamp: '07-08-2026 03:15 PM',
        user: 'HR Manager',
        userEmail: 'hr@school.com',
        role: 'HR',
        module: 'Employee Database',
        recordId: 'EMP-1042',
        recordName: 'Anand Mehta',
        fieldChanged: 'Department',
        oldValue: 'Accounts',
        newValue: 'Finance',
        changeType: 'Update',
        ipAddress: '192.168.10.25',
    },
    {
        id: 'log-dc-004',
        logType: 'data-changes',
        timestamp: '07-08-2026 11:40 AM',
        user: 'Front Office',
        userEmail: 'frontoffice@school.com',
        role: 'Front Office',
        module: 'Gate Pass',
        recordId: 'SGP-002',
        recordName: 'John Milton',
        fieldChanged: 'Out Time',
        oldValue: '11:00 AM',
        newValue: '12:00 PM',
        changeType: 'Update',
        ipAddress: '192.168.10.30',
    },
    {
        id: 'log-dc-005',
        logType: 'data-changes',
        timestamp: '07-08-2026 10:05 AM',
        user: 'Transport Manager',
        userEmail: 'transport@school.com',
        role: 'Transport Manager',
        module: 'Route Management',
        recordId: 'RT-14',
        recordName: 'Route 14 — Adyar Loop',
        fieldChanged: 'Pickup Time',
        oldValue: '07:15 AM',
        newValue: '07:10 AM',
        changeType: 'Update',
        ipAddress: '192.168.10.35',
    },
    {
        id: 'log-dc-006',
        logType: 'data-changes',
        timestamp: '06-08-2026 02:08 PM',
        user: 'Account Head',
        userEmail: 'accounts@school.com',
        role: 'Account Head',
        module: 'Fees Management',
        recordId: 'FEE-CL-10A',
        recordName: 'Class 10 A Fee Structure',
        fieldChanged: 'Tuition Fee',
        oldValue: '₹45,000',
        newValue: '₹47,500',
        changeType: 'Update',
        ipAddress: '192.168.10.40',
    },
    {
        id: 'log-dc-007',
        logType: 'data-changes',
        timestamp: '06-08-2026 11:30 AM',
        user: 'Librarian',
        userEmail: 'librarian@school.com',
        role: 'Librarian',
        module: 'Library — Book List',
        recordId: 'BK-3310',
        recordName: 'Organic Chemistry Essentials',
        fieldChanged: 'Available Copies',
        oldValue: '12',
        newValue: '11',
        changeType: 'Update',
        ipAddress: '192.168.10.55',
    },
    {
        id: 'log-dc-008',
        logType: 'data-changes',
        timestamp: '05-08-2026 04:45 PM',
        user: 'Principal',
        userEmail: 'principal@school.com',
        role: 'Principal',
        module: 'Class Timetable',
        recordId: 'TT-10A',
        recordName: 'Class 10 A — Wednesday',
        fieldChanged: 'Period 3 Subject',
        oldValue: 'Physics',
        newValue: 'Chemistry',
        changeType: 'Update',
        ipAddress: '10.0.0.54',
    },
    {
        id: 'log-dc-009',
        logType: 'data-changes',
        timestamp: '05-08-2026 02:20 PM',
        user: 'Canteen Manager',
        userEmail: 'canteen@school.com',
        role: 'Canteen Manager',
        module: 'Menu Management',
        recordId: 'MENU-082',
        recordName: 'Tuesday Lunch Menu',
        fieldChanged: 'Item Price',
        oldValue: '₹60',
        newValue: '₹65',
        changeType: 'Update',
        ipAddress: '192.168.10.48',
    },
    {
        id: 'log-dc-010',
        logType: 'data-changes',
        timestamp: '04-08-2026 09:15 AM',
        user: 'IT Support Manager',
        userEmail: 'itsupport@school.com',
        role: 'IT Support Manager',
        module: 'Asset Management',
        recordId: 'AST-LAB-018',
        recordName: 'Lab PC — Block B Room 204',
        fieldChanged: 'Assigned To',
        oldValue: 'Unassigned',
        newValue: 'Science Lab Block B',
        changeType: 'Update',
        ipAddress: '192.168.10.52',
    },
]

export const DELETED_RECORDS_LOGS = [
    {
        id: 'log-dr-001',
        logType: 'deleted-records',
        timestamp: '08-08-2026 09:50 AM',
        user: 'School Admin',
        userEmail: 'admin@school.com',
        role: 'Administrator',
        module: 'Announcement',
        recordId: 'ADM-AN-014',
        recordName: 'Sports Day Postponement Notice',
        deletedBy: 'School Admin',
        reason: 'Duplicate announcement replaced with updated notice',
        canRestore: true,
        ipAddress: '192.168.10.18',
    },
    {
        id: 'log-dr-002',
        logType: 'deleted-records',
        timestamp: '08-08-2026 08:35 AM',
        user: 'Teacher',
        userEmail: 'teacher@school.com',
        role: 'Teacher',
        module: 'Homework Assignment',
        recordId: 'HW-10A-MATH-042',
        recordName: 'Algebra Practice Sheet — Draft',
        deletedBy: 'Ravi Kumar',
        reason: 'Draft uploaded by mistake; replaced with final version',
        canRestore: true,
        ipAddress: '192.168.20.44',
    },
    {
        id: 'log-dr-003',
        logType: 'deleted-records',
        timestamp: '07-08-2026 05:20 PM',
        user: 'Front Office',
        userEmail: 'frontoffice@school.com',
        role: 'Front Office',
        module: 'Admission Enquiry',
        recordId: 'ENQ-2026-088',
        recordName: 'Karthik R — Grade 6 Enquiry',
        deletedBy: 'Front Office',
        reason: 'Parent withdrew enquiry after school visit',
        canRestore: false,
        ipAddress: '192.168.10.30',
    },
    {
        id: 'log-dr-004',
        logType: 'deleted-records',
        timestamp: '07-08-2026 01:10 PM',
        user: 'Account Head',
        userEmail: 'accounts@school.com',
        role: 'Account Head',
        module: 'Receipt Management',
        recordId: 'RCT-2026-9912',
        recordName: 'Duplicate Fee Receipt — STD-NO1845',
        deletedBy: 'Account Head',
        reason: 'Duplicate receipt generated in error during batch print',
        canRestore: false,
        ipAddress: '192.168.10.40',
    },
    {
        id: 'log-dr-005',
        logType: 'deleted-records',
        timestamp: '06-08-2026 01:35 PM',
        user: 'Librarian',
        userEmail: 'librarian@school.com',
        role: 'Librarian',
        module: 'Library — Book List',
        recordId: 'BK-4421',
        recordName: 'Advanced Physics Vol. II',
        deletedBy: 'Librarian',
        reason: 'Damaged copy removed from catalogue',
        canRestore: false,
        ipAddress: '192.168.10.55',
    },
    {
        id: 'log-dr-006',
        logType: 'deleted-records',
        timestamp: '06-08-2026 10:50 AM',
        user: 'Transport Manager',
        userEmail: 'transport@school.com',
        role: 'Transport Manager',
        module: 'Vehicle Maintenance',
        recordId: 'VM-2026-017',
        recordName: 'Bus TN-58-AB-4521 — Test Entry',
        deletedBy: 'Transport Manager',
        reason: 'Test record created during system training session',
        canRestore: true,
        ipAddress: '192.168.10.35',
    },
    {
        id: 'log-dr-007',
        logType: 'deleted-records',
        timestamp: '05-08-2026 03:40 PM',
        user: 'HR Manager',
        userEmail: 'hr@school.com',
        role: 'HR',
        module: 'Leave Policy',
        recordId: 'LP-OLD-2024',
        recordName: 'Legacy Leave Policy 2024',
        deletedBy: 'HR Manager',
        reason: 'Superseded by updated 2026 leave policy document',
        canRestore: true,
        ipAddress: '192.168.10.25',
    },
    {
        id: 'log-dr-008',
        logType: 'deleted-records',
        timestamp: '04-08-2026 11:05 AM',
        user: 'Canteen Manager',
        userEmail: 'canteen@school.com',
        role: 'Canteen Manager',
        module: 'Menu Management',
        recordId: 'MENU-071',
        recordName: 'Expired Summer Special Menu',
        deletedBy: 'Canteen Manager',
        reason: 'Seasonal menu archived after academic term ended',
        canRestore: false,
        ipAddress: '192.168.10.48',
    },
]

export const APPROVAL_ACTIONS_LOGS = [
    {
        id: 'log-aa-001',
        logType: 'approval-actions',
        timestamp: '08-08-2026 11:05 AM',
        user: 'Super Admin',
        userEmail: 'superadmin@school.com',
        role: 'Super Admin',
        action: 'Approved',
        module: 'Leave Request',
        referenceId: 'ADM-LR-001',
        referenceTitle: 'Admin Annual Leave — 12–14 Aug 2026',
        remarks: 'Coverage plan confirmed with Deputy Admin.',
        ipAddress: '192.168.10.12',
    },
    {
        id: 'log-aa-002',
        logType: 'approval-actions',
        timestamp: '08-08-2026 10:40 AM',
        user: 'Super Admin',
        userEmail: 'superadmin@school.com',
        role: 'Super Admin',
        action: 'Approved',
        module: 'Escalation Management',
        referenceId: 'ESC-2026-010',
        referenceTitle: 'Delayed fee reconciliation report from Accounts',
        remarks: 'Resolved after Accounts submitted revised reconciliation.',
        ipAddress: '192.168.10.12',
    },
    {
        id: 'log-aa-003',
        logType: 'approval-actions',
        timestamp: '07-08-2026 04:45 PM',
        user: 'Super Admin',
        userEmail: 'superadmin@school.com',
        role: 'Super Admin',
        action: 'Rejected',
        module: 'Escalation',
        referenceId: 'ESC-2026-009',
        referenceTitle: 'Transport route change without prior notice',
        remarks: 'Insufficient documentation attached; resubmit with route map.',
        ipAddress: '192.168.10.12',
    },
    {
        id: 'log-aa-004',
        logType: 'approval-actions',
        timestamp: '07-08-2026 10:30 AM',
        user: 'Director',
        userEmail: 'director@school.com',
        role: 'Director',
        action: 'Approved',
        module: 'Mark Entry Approval',
        referenceId: 'MEA-UT-10A-MATH',
        referenceTitle: 'Unit Test Marks — Class 10 A Mathematics',
        remarks: 'Marks verified against answer keys.',
        ipAddress: '10.0.0.22',
    },
    {
        id: 'log-aa-005',
        logType: 'approval-actions',
        timestamp: '07-08-2026 09:15 AM',
        user: 'Director',
        userEmail: 'director@school.com',
        role: 'Director',
        action: 'Rejected',
        module: 'Mark Entry Approval',
        referenceId: 'MEA-UT-9B-SCI',
        referenceTitle: 'Unit Test Marks — Class 9 B Science',
        remarks: 'Three answer sheets missing; resubmit after completion.',
        ipAddress: '10.0.0.22',
    },
    {
        id: 'log-aa-006',
        logType: 'approval-actions',
        timestamp: '06-08-2026 03:18 PM',
        user: 'Principal',
        userEmail: 'principal@school.com',
        role: 'Principal',
        action: 'Approved',
        module: 'Material Gate Pass',
        referenceId: 'MGP-1375',
        referenceTitle: 'Office Stationery — A4 Paper Reams',
        remarks: 'Monthly supply approved for admin office.',
        ipAddress: '10.0.0.54',
    },
    {
        id: 'log-aa-007',
        logType: 'approval-actions',
        timestamp: '06-08-2026 11:50 AM',
        user: 'Principal',
        userEmail: 'principal@school.com',
        role: 'Principal',
        action: 'Approved',
        module: 'Hostel Gate Pass',
        referenceId: 'HGP-001',
        referenceTitle: 'Arjun Sharma — Weekend Home Visit',
        remarks: 'Parent consent verified by warden.',
        ipAddress: '10.0.0.54',
    },
    {
        id: 'log-aa-008',
        logType: 'approval-actions',
        timestamp: '05-08-2026 02:30 PM',
        user: 'HR Manager',
        userEmail: 'hr@school.com',
        role: 'HR',
        action: 'Approved',
        module: 'Employee Leave',
        referenceId: 'EMP-LR-044',
        referenceTitle: 'Teacher Sick Leave — Ravi Kumar',
        remarks: 'Medical certificate attached and verified.',
        ipAddress: '192.168.10.25',
    },
    {
        id: 'log-aa-009',
        logType: 'approval-actions',
        timestamp: '05-08-2026 10:00 AM',
        user: 'Account Head',
        userEmail: 'accounts@school.com',
        role: 'Account Head',
        action: 'Approved',
        module: 'Fee Waiver Request',
        referenceId: 'FW-2026-008',
        referenceTitle: 'Partial Fee Waiver — STD-NO1902',
        remarks: 'Approved per scholarship committee recommendation.',
        ipAddress: '192.168.10.40',
    },
    {
        id: 'log-aa-010',
        logType: 'approval-actions',
        timestamp: '04-08-2026 04:15 PM',
        user: 'Joint Director',
        userEmail: 'jointdirector@school.com',
        role: 'Joint Director',
        action: 'Rejected',
        module: 'Budget Request',
        referenceId: 'BR-2026-003',
        referenceTitle: 'Additional Lab Equipment Budget — Q3',
        remarks: 'Deferred to next budget cycle; submit revised quote.',
        ipAddress: '10.0.0.15',
    },
]

export const AUDIT_LOGS = [
    {
        id: 'log-al-001',
        logType: 'audit-logs',
        timestamp: '08-08-2026 07:00 AM',
        user: 'Process Auditor',
        userEmail: 'processauditor@school.com',
        role: 'Process Auditor',
        auditType: 'Process Compliance',
        scope: 'Front Office — Admission Workflow',
        result: 'Completed',
        findings: '2 minor observations logged; no critical non-conformities.',
        auditId: 'AUD-2026-041',
        ipAddress: '192.168.10.70',
    },
    {
        id: 'log-al-002',
        logType: 'audit-logs',
        timestamp: '07-08-2026 06:00 PM',
        user: 'Quality Auditor',
        userEmail: 'qualityauditor@school.com',
        role: 'Quality Auditor',
        auditType: 'Quality Review',
        scope: 'Canteen — Food Safety & Hygiene',
        result: 'Completed',
        findings: 'Kitchen storage labels updated; temperature log verified.',
        auditId: 'AUD-2026-040',
        ipAddress: '192.168.10.71',
    },
    {
        id: 'log-al-003',
        logType: 'audit-logs',
        timestamp: '05-08-2026 06:30 PM',
        user: 'Quality Auditor',
        userEmail: 'qualityauditor@school.com',
        role: 'Quality Auditor',
        auditType: 'Quality Review',
        scope: 'Library — Issue & Return Process',
        result: 'In Progress',
        findings: 'Pending verification of overdue book follow-up records.',
        auditId: 'AUD-2026-038',
        ipAddress: '192.168.10.71',
    },
    {
        id: 'log-al-004',
        logType: 'audit-logs',
        timestamp: '05-08-2026 11:00 AM',
        user: 'Process Auditor',
        userEmail: 'processauditor@school.com',
        role: 'Process Auditor',
        auditType: 'Process Compliance',
        scope: 'Gate Pass — Student Exit Controls',
        result: 'Completed',
        findings: 'Exit verification workflow compliant; 1 signage update suggested.',
        auditId: 'AUD-2026-037',
        ipAddress: '192.168.10.70',
    },
    {
        id: 'log-al-005',
        logType: 'audit-logs',
        timestamp: '04-08-2026 02:15 PM',
        user: 'Joint Director Audit',
        userEmail: 'jdaudit@school.com',
        role: 'Joint Director Audit',
        auditType: 'Financial Controls',
        scope: 'Fees Collection & Receipt Management',
        result: 'Completed',
        findings: 'Receipt numbering sequence verified; 1 reconciliation item noted.',
        auditId: 'AUD-2026-035',
        ipAddress: '10.0.0.18',
    },
    {
        id: 'log-al-006',
        logType: 'audit-logs',
        timestamp: '03-08-2026 09:30 AM',
        user: 'Joint Director Audit',
        userEmail: 'jdaudit@school.com',
        role: 'Joint Director Audit',
        auditType: 'Financial Controls',
        scope: 'Transport Expenses & Fuel Logs',
        result: 'In Progress',
        findings: 'Awaiting supporting invoices for July fuel entries.',
        auditId: 'AUD-2026-033',
        ipAddress: '10.0.0.18',
    },
    {
        id: 'log-al-007',
        logType: 'audit-logs',
        timestamp: '02-08-2026 03:45 PM',
        user: 'Process Auditor',
        userEmail: 'processauditor@school.com',
        role: 'Process Auditor',
        auditType: 'Process Compliance',
        scope: 'HR — Employee Onboarding Checklist',
        result: 'Completed',
        findings: 'All mandatory documents captured for Q2 hires.',
        auditId: 'AUD-2026-031',
        ipAddress: '192.168.10.70',
    },
    {
        id: 'log-al-008',
        logType: 'audit-logs',
        timestamp: '01-08-2026 10:20 AM',
        user: 'Quality Auditor',
        userEmail: 'qualityauditor@school.com',
        role: 'Quality Auditor',
        auditType: 'Safety Inspection',
        scope: 'Science Lab — Chemical Storage',
        result: 'Completed',
        findings: 'MSDS sheets updated; fire extinguisher service due next month.',
        auditId: 'AUD-2026-029',
        ipAddress: '192.168.10.71',
    },
]

export const FAILED_LOGINS_LOGS = [
    {
        id: 'log-fl-001',
        logType: 'failed-logins',
        timestamp: '08-08-2026 07:58 AM',
        username: 'admin@school.com',
        role: 'Administrator',
        ipAddress: '203.45.112.88',
        device: 'Unknown browser · Linux',
        reason: 'Invalid OTP',
        attempts: 2,
        status: 'Blocked',
        location: 'Unknown',
    },
    {
        id: 'log-fl-002',
        logType: 'failed-logins',
        timestamp: '08-08-2026 06:42 AM',
        username: 'frontoffice@school.com',
        role: 'Front Office',
        ipAddress: '192.168.10.30',
        device: 'Chrome 126 · Windows 11',
        reason: 'Invalid OTP',
        attempts: 1,
        status: 'Failed',
        location: 'Chennai, IN',
    },
    {
        id: 'log-fl-003',
        logType: 'failed-logins',
        timestamp: '07-08-2026 11:22 PM',
        username: 'superadmin@school.com',
        role: 'Super Admin',
        ipAddress: '45.33.19.201',
        device: 'Chrome 118 · Windows 10',
        reason: 'Invalid credentials',
        attempts: 5,
        status: 'Blocked',
        location: 'Singapore, SG',
    },
    {
        id: 'log-fl-004',
        logType: 'failed-logins',
        timestamp: '07-08-2026 06:10 AM',
        username: 'teacher@school.com',
        role: 'Teacher',
        ipAddress: '192.168.20.44',
        device: 'Chrome 126 · Android 14',
        reason: 'Session expired',
        attempts: 1,
        status: 'Failed',
        location: 'Madurai, IN',
    },
    {
        id: 'log-fl-005',
        logType: 'failed-logins',
        timestamp: '07-08-2026 05:55 AM',
        username: 'parent@school.com',
        role: 'Parent',
        ipAddress: '103.45.88.12',
        device: 'Safari · iOS 17',
        reason: 'Invalid OTP',
        attempts: 3,
        status: 'Failed',
        location: 'Coimbatore, IN',
    },
    {
        id: 'log-fl-006',
        logType: 'failed-logins',
        timestamp: '06-08-2026 09:33 AM',
        username: 'unknown@external.com',
        role: '—',
        ipAddress: '198.51.100.14',
        device: 'Automated script',
        reason: 'Account not found',
        attempts: 12,
        status: 'Blocked',
        location: 'Unknown',
    },
    {
        id: 'log-fl-007',
        logType: 'failed-logins',
        timestamp: '06-08-2026 08:10 AM',
        username: 'student@school.com',
        role: 'Student',
        ipAddress: '103.45.88.45',
        device: 'Chrome 125 · Windows 11',
        reason: 'Account locked',
        attempts: 6,
        status: 'Blocked',
        location: 'Chennai, IN',
    },
    {
        id: 'log-fl-008',
        logType: 'failed-logins',
        timestamp: '05-08-2026 10:45 PM',
        username: 'hr@school.com',
        role: 'HR',
        ipAddress: '185.220.101.42',
        device: 'Tor Browser · Linux',
        reason: 'Invalid credentials',
        attempts: 4,
        status: 'Blocked',
        location: 'Unknown',
    },
    {
        id: 'log-fl-009',
        logType: 'failed-logins',
        timestamp: '05-08-2026 07:20 AM',
        username: 'librarian@school.com',
        role: 'Librarian',
        ipAddress: '192.168.10.55',
        device: 'Firefox 127 · Windows 10',
        reason: 'Invalid OTP',
        attempts: 2,
        status: 'Failed',
        location: 'Chennai, IN',
    },
    {
        id: 'log-fl-010',
        logType: 'failed-logins',
        timestamp: '04-08-2026 11:58 PM',
        username: 'accounts@school.com',
        role: 'Account Head',
        ipAddress: '91.203.5.112',
        device: 'Chrome 119 · macOS',
        reason: 'Suspicious location',
        attempts: 1,
        status: 'Blocked',
        location: 'Frankfurt, DE',
    },
]

const ACTIVITY_LOGS = [
    ...LOGIN_HISTORY_LOGS,
    ...DATA_CHANGES_LOGS,
    ...DELETED_RECORDS_LOGS,
    ...APPROVAL_ACTIONS_LOGS,
    ...AUDIT_LOGS,
    ...FAILED_LOGINS_LOGS,
]

export const getLogsByType = (logType) =>
    ACTIVITY_LOGS.filter((record) => record.logType === logType)

export const getActivityLogById = (id) =>
    ACTIVITY_LOGS.find((record) => record.id === id) ?? null

export const getLogSummary = (logType, records = null) => {
    const items = records ?? getLogsByType(logType)

    switch (logType) {
        case 'login-history': {
            const successful = items.filter((r) => r.status === 'Success').length
            const uniqueUsers = new Set(items.map((r) => r.userEmail)).size
            return [
                { label: 'Total Entries', value: items.length },
                { label: 'Successful Logins', value: successful },
                { label: 'Unique Users', value: uniqueUsers },
                { label: 'Logouts', value: items.filter((r) => r.status === 'Logout').length },
            ]
        }
        case 'data-changes':
            return [
                { label: 'Total Changes', value: items.length },
                { label: 'Updates', value: items.filter((r) => r.changeType === 'Update').length },
                { label: 'Modules', value: new Set(items.map((r) => r.module)).size },
                { label: 'Users', value: new Set(items.map((r) => r.user)).size },
            ]
        case 'deleted-records':
            return [
                { label: 'Total Deleted', value: items.length },
                { label: 'Restorable', value: items.filter((r) => r.canRestore).length },
                { label: 'Modules', value: new Set(items.map((r) => r.module)).size },
                { label: 'Permanent', value: items.filter((r) => !r.canRestore).length },
            ]
        case 'approval-actions':
            return [
                { label: 'Total Actions', value: items.length },
                { label: 'Approved', value: items.filter((r) => r.action === 'Approved').length },
                { label: 'Rejected', value: items.filter((r) => r.action === 'Rejected').length },
                { label: 'Modules', value: new Set(items.map((r) => r.module)).size },
            ]
        case 'audit-logs':
            return [
                { label: 'Total Audits', value: items.length },
                { label: 'Completed', value: items.filter((r) => r.result === 'Completed').length },
                { label: 'In Progress', value: items.filter((r) => r.result === 'In Progress').length },
                { label: 'Auditors', value: new Set(items.map((r) => r.user)).size },
            ]
        case 'failed-logins':
            return [
                { label: 'Total Attempts', value: items.length },
                { label: 'Blocked', value: items.filter((r) => r.status === 'Blocked').length },
                { label: 'Failed', value: items.filter((r) => r.status === 'Failed').length },
                { label: 'Unique IPs', value: new Set(items.map((r) => r.ipAddress)).size },
            ]
        default:
            return []
    }
}

export const getLogStatusOptions = (records) => {
    const statuses = records
        .map((record) => record.status ?? record.action ?? record.result)
        .filter(Boolean)
    return [...new Set(statuses)].sort()
}

export const filterActivityLogs = (
    records,
    { search = '', status = '' } = {},
) => {
    const query = search.trim().toLowerCase()

    return records.filter((record) => {
        const recordStatus = record.status ?? record.action ?? record.result ?? ''
        if (status && recordStatus !== status) return false
        if (!query) return true

        return Object.values(record)
            .join(' ')
            .toLowerCase()
            .includes(query)
    })
}

export const getListColumns = (logType) => {
    switch (logType) {
        case 'login-history':
            return [
                { key: 'timestamp', label: 'Date & Time' },
                { key: 'user', label: 'User' },
                { key: 'role', label: 'Role' },
                { key: 'ipAddress', label: 'IP Address' },
                { key: 'device', label: 'Device' },
                { key: 'status', label: 'Status', badge: true },
            ]
        case 'data-changes':
            return [
                { key: 'timestamp', label: 'Date & Time' },
                { key: 'user', label: 'User' },
                { key: 'module', label: 'Module' },
                { key: 'recordName', label: 'Record' },
                { key: 'fieldChanged', label: 'Field Changed' },
                { key: 'changeSummary', label: 'Change', computed: true },
            ]
        case 'deleted-records':
            return [
                { key: 'timestamp', label: 'Date & Time' },
                { key: 'module', label: 'Module' },
                { key: 'recordId', label: 'Record ID' },
                { key: 'recordName', label: 'Record Name' },
                { key: 'deletedBy', label: 'Deleted By' },
                { key: 'canRestore', label: 'Restorable', computed: true },
            ]
        case 'approval-actions':
            return [
                { key: 'timestamp', label: 'Date & Time' },
                { key: 'user', label: 'Approver' },
                { key: 'action', label: 'Action', badge: true },
                { key: 'module', label: 'Module' },
                { key: 'referenceId', label: 'Reference ID' },
                { key: 'referenceTitle', label: 'Reference' },
            ]
        case 'audit-logs':
            return [
                { key: 'timestamp', label: 'Date & Time' },
                { key: 'user', label: 'Auditor' },
                { key: 'auditType', label: 'Audit Type' },
                { key: 'scope', label: 'Scope' },
                { key: 'result', label: 'Result', badge: true },
                { key: 'auditId', label: 'Audit ID' },
            ]
        case 'failed-logins':
            return [
                { key: 'timestamp', label: 'Date & Time' },
                { key: 'username', label: 'Username / Email' },
                { key: 'ipAddress', label: 'IP Address' },
                { key: 'reason', label: 'Reason' },
                { key: 'attempts', label: 'Attempts' },
                { key: 'status', label: 'Status', badge: true },
            ]
        default:
            return []
    }
}

export const getCellValue = (record, column) => {
    if (column.computed) {
        if (column.key === 'changeSummary') {
            return `${record.oldValue} → ${record.newValue}`
        }
        if (column.key === 'canRestore') {
            return record.canRestore ? 'Yes' : 'No'
        }
    }

    const value = record[column.key]
    if (value === true) return 'Yes'
    if (value === false) return 'No'
    return value ?? '—'
}

export const getViewFields = (record) => {
    if (!record) return []

    const common = [
        { label: 'Log ID', value: record.id },
        { label: 'Log type', value: LOG_TYPES[record.logType]?.label },
        { label: 'Timestamp', value: record.timestamp },
    ]

    switch (record.logType) {
        case 'login-history':
            return [
                ...common,
                { label: 'User', value: record.user },
                { label: 'Email', value: record.userEmail },
                { label: 'Role', value: record.role },
                { label: 'IP address', value: record.ipAddress },
                { label: 'Device', value: record.device },
                { label: 'Location', value: record.location },
                { label: 'Session ID', value: record.sessionId },
                { label: 'Status', value: record.status, badge: true },
            ]
        case 'data-changes':
            return [
                ...common,
                { label: 'Changed by', value: record.user },
                { label: 'Email', value: record.userEmail },
                { label: 'Role', value: record.role },
                { label: 'Module', value: record.module },
                { label: 'Record ID', value: record.recordId },
                { label: 'Record name', value: record.recordName },
                { label: 'Change type', value: record.changeType },
                { label: 'Field changed', value: record.fieldChanged },
                { label: 'Old value', value: record.oldValue },
                { label: 'New value', value: record.newValue },
                { label: 'IP address', value: record.ipAddress },
            ]
        case 'deleted-records':
            return [
                ...common,
                { label: 'Module', value: record.module },
                { label: 'Record ID', value: record.recordId },
                { label: 'Record name', value: record.recordName },
                { label: 'Deleted by', value: record.deletedBy },
                { label: 'Reason', value: record.reason },
                { label: 'Can restore', value: record.canRestore ? 'Yes' : 'No' },
                { label: 'IP address', value: record.ipAddress },
            ]
        case 'approval-actions':
            return [
                ...common,
                { label: 'Approver', value: record.user },
                { label: 'Email', value: record.userEmail },
                { label: 'Role', value: record.role },
                { label: 'Action', value: record.action, badge: true },
                { label: 'Module', value: record.module },
                { label: 'Reference ID', value: record.referenceId },
                { label: 'Reference title', value: record.referenceTitle },
                { label: 'Remarks', value: record.remarks },
                { label: 'IP address', value: record.ipAddress },
            ]
        case 'audit-logs':
            return [
                ...common,
                { label: 'Auditor', value: record.user },
                { label: 'Email', value: record.userEmail },
                { label: 'Role', value: record.role },
                { label: 'Audit ID', value: record.auditId },
                { label: 'Audit type', value: record.auditType },
                { label: 'Scope', value: record.scope },
                { label: 'Result', value: record.result, badge: true },
                { label: 'Findings', value: record.findings },
                { label: 'IP address', value: record.ipAddress },
            ]
        case 'failed-logins':
            return [
                ...common,
                { label: 'Username / email', value: record.username },
                { label: 'Role', value: record.role },
                { label: 'IP address', value: record.ipAddress },
                { label: 'Device', value: record.device },
                { label: 'Location', value: record.location },
                { label: 'Reason', value: record.reason },
                { label: 'Attempts', value: String(record.attempts) },
                { label: 'Status', value: record.status, badge: true },
            ]
        default:
            return common
    }
}
