export const REQUEST_STATUSES = ['In-Process', 'Pending', 'Completed']

export const ISSUE_TYPES = [
    'Engine Issue',
    'Brake Failure',
    'AC Not Working',
    'Tyre Puncture',
    'Electrical Fault',
    'Oil Leak',
    'Battery Issue',
]

export const PRIORITIES = ['High', 'Medium', 'Low']

export const statusBadgeColor = {
    'In-Process': 'bg-[#2196F333] text-[#2196F3]',
    Pending: 'bg-[#FF980033] text-[#FF9800]',
    Completed: 'bg-[#4CAF5033] text-[#4CAF50]',
}

export const MAINTENANCE_REQUESTS = [
    {
        id: 'MR-1001',
        requestId: 'MR-1001',
        vehicleNumber: 'TN-09-AB-4521',
        reportedBy: 'Sandy Selva',
        requestDate: '08-06-2026',
        issueType: 'AC Not Working',
        description: 'AC cooling weak during morning route; needs inspection before summer peak.',
        priority: 'High',
        status: 'In-Process',
    },
    {
        id: 'MR-1002',
        requestId: 'MR-1002',
        vehicleNumber: 'TN-09-CD-8834',
        reportedBy: 'Rajesh K. Kumar',
        requestDate: '07-06-2026',
        issueType: 'Brake Failure',
        description: 'Rear brake pads worn out; squeaking noise reported on downhill stops.',
        priority: 'High',
        status: 'Pending',
    },
    {
        id: 'MR-1003',
        requestId: 'MR-1003',
        vehicleNumber: 'TN-09-EF-2210',
        reportedBy: 'Priya M. Venkatesh',
        requestDate: '05-06-2026',
        issueType: 'Tyre Puncture',
        description: 'Front-left tyre puncture near school gate; temporary fix applied.',
        priority: 'Medium',
        status: 'Completed',
    },
    {
        id: 'MR-1004',
        requestId: 'MR-1004',
        vehicleNumber: 'TN-09-GH-5567',
        reportedBy: 'Mohan R. Das',
        requestDate: '09-06-2026',
        issueType: 'Engine Issue',
        description: 'Engine overheating warning light during afternoon return trip.',
        priority: 'High',
        status: 'Pending',
    },
    {
        id: 'MR-1005',
        requestId: 'MR-1005',
        vehicleNumber: 'TN-09-IJ-3344',
        reportedBy: 'Transport Supervisor',
        requestDate: '06-06-2026',
        issueType: 'Oil Leak',
        description: 'Minor oil leak detected during weekly inspection at depot.',
        priority: 'Low',
        status: 'Completed',
    },
]

export const FUEL_REQUESTS = [
    {
        id: 'FR-1001',
        requestId: 'FR-1001',
        driverName: 'Sandy Selva',
        driverId: 'VAN-1001',
        vehicleNumber: 'TN-09-AB-4521',
        routeName: 'Route 5 — North Campus',
        currentOdometerReading: '48,320 km',
        requestedQuantity: '120 L',
        requestedDate: '09-06-2026',
        status: 'In-Process',
    },
    {
        id: 'FR-1002',
        requestId: 'FR-1002',
        driverName: 'Rajesh K. Kumar',
        driverId: 'VAN-1002',
        vehicleNumber: 'TN-09-CD-8834',
        routeName: 'Route 2 — East Campus',
        currentOdometerReading: '62,150 km',
        requestedQuantity: '150 L',
        requestedDate: '08-06-2026',
        status: 'Pending',
    },
    {
        id: 'FR-1003',
        requestId: 'FR-1003',
        driverName: 'Priya M. Venkatesh',
        driverId: 'VAN-1003',
        vehicleNumber: 'TN-09-EF-2210',
        routeName: 'Route 8 — West Campus',
        currentOdometerReading: '35,780 km',
        requestedQuantity: '100 L',
        requestedDate: '07-06-2026',
        status: 'Completed',
    },
    {
        id: 'FR-1004',
        requestId: 'FR-1004',
        driverName: 'Mohan R. Das',
        driverId: 'VAN-1004',
        vehicleNumber: 'TN-09-GH-5567',
        routeName: 'Route 3 — South Campus',
        currentOdometerReading: '71,420 km',
        requestedQuantity: '140 L',
        requestedDate: '10-06-2026',
        status: 'Pending',
    },
    {
        id: 'FR-1005',
        requestId: 'FR-1005',
        driverName: 'Sandy Selva',
        driverId: 'VAN-1001',
        vehicleNumber: 'TN-09-AB-4521',
        routeName: 'Route 5 — North Campus',
        currentOdometerReading: '48,650 km',
        requestedQuantity: '110 L',
        requestedDate: '04-06-2026',
        status: 'Completed',
    },
]
