import {
    LayoutDashboard,
    Users,
    BookOpen,
    Car,
    FileText,
    CalendarDays,
    BookCopy,
    CalendarCheck,
    GraduationCap,
    Briefcase,
    FileX,
    School,
    ClipboardList,
    MonitorPlay,
    UserPlus,
    Library,
    BookOpenCheck,
    BookMarked,
    UserRound,
    UserRoundSearch,
    BadgeDollarSign,
    UsersRound,
    ArrowRightLeft,
    Trophy,
    Palette,
    Dumbbell,
    Award,
    FolderOpen,
    Van,
    Bus,
    MapPin,
    Route,
    ListChecks,
    NotebookPen,
    Wallet,
    Bed,
    BellDot,
    CalendarOff,
    MessageCircle,
    ClipboardPen,
    DoorOpen,
    ShieldCheck,
    ShieldAlert,
    AlertTriangle,
    Star,
    UserRoundCog,
    Rss,
    UtensilsCrossed,
    Package,
    ShoppingCart,
    ClipboardCheck,
    BarChart3,
    Monitor,
    Ticket,
    Sparkles,
    History,
    CircleHelp,
    Send,
    Settings,
    Landmark,
    Receipt,
    HeartPulse,
} from "lucide-react";

export const superAdminSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/super-admin/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Attendance",
        to: "#0",
        icon: CalendarCheck,
        subLinks: [
            { icon: GraduationCap, title: "Student Attendance", to: "/super-admin/attendance/students/list" },
            { icon: Briefcase, title: "Employee Attendance", to: "/super-admin/attendance/employees" },
        ],
    },
    {
        id: 3,
        title: "User Database",
        to: "#0",
        icon: UserRound,
        subLinks: [
            { icon: GraduationCap, title: "Students List", to: "/super-admin/user-database/students" },
            { icon: UserRoundCog, title: "Employee List", to: "/super-admin/user-database/employees" },
        ],
    },
    {
        id: 4,
        title: "User Creation",
        to: "/super-admin/user-creation",
        icon: UserPlus,
    },
    {
        id: 5,
        title: "Gate Pass",
        to: "/super-admin/gate-pass",
        icon: DoorOpen,
    },
    {
        id: 6,
        title: "Transport Overview",
        to: "/super-admin/transport-overview",
        icon: Bus,
    },
    {
        id: 7,
        title: "Finance",
        to: "#0",
        icon: Landmark,
        subLinks: [
            { icon: LayoutDashboard, title: "Finance Overview", to: "/super-admin/finance/overview" },
            { icon: BadgeDollarSign, title: "Fees Management", to: "/super-admin/finance/fees" },
            { icon: BadgeDollarSign, title: "Collections", to: "/super-admin/finance/collections" },
            { icon: Wallet, title: "Wallet Management", to: "/super-admin/finance/wallets" },
            { icon: Bus, title: "Transport Finance", to: "/super-admin/finance/transport" },
            { icon: BookCopy, title: "Accounting", to: "/super-admin/finance/accounting" },
            { icon: BarChart3, title: "Reports & Analytics", to: "/super-admin/finance/reports" },
        ],
    },
    {
        id: 8,
        title: "Audit Reports",
        to: "#0",
        icon: ShieldCheck,
        subLinks: [
            { icon: LayoutDashboard, title: "Overview", to: "/super-admin/audit-reports/overview" },
            { icon: BarChart3, title: "Compliance Score", to: "/super-admin/audit-reports/compliance" },
            { icon: Trophy, title: "Department Ranking", to: "/super-admin/audit-reports/department-ranking" },
            { icon: AlertTriangle, title: "Pending Findings", to: "/super-admin/audit-reports/pending-findings" },
            { icon: ShieldAlert, title: "Critical Findings", to: "/super-admin/audit-reports/critical-findings" },
            { icon: CircleHelp, title: "Risk Dashboard", to: "/super-admin/audit-reports/risk-dashboard" },
        ],
    },
    {
        id: 9,
        title: "Star Ratings",
        to: "#0",
        icon: Star,
        subLinks: [
            { icon: Star, title: "Star of the Month", to: "/super-admin/star-ratings/star-of-month" },
            { icon: Trophy, title: "Star of the Year", to: "/super-admin/star-ratings/star-of-year" },
        ],
    },
    {
        id: 10,
        title: "Task Management",
        to: "/super-admin/task-management/assign-tasks",
        icon: ClipboardList,
    },
    {
        id: 11,
        title: "Leave Request",
        to: "/super-admin/leave-request/received",
        icon: FileX,
    },
    {
        id: 12,
        title: "Approvals",
        to: "/super-admin/approvals",
        icon: ClipboardCheck,
    },
    {
        id: 13,
        title: "Announcement",
        to: "/super-admin/announcement",
        icon: Rss,
    },
    {
        id: 14,
        title: "Communication",
        to: "/super-admin/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 15,
        title: "Calendar",
        to: "/super-admin/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 16,
        title: "Notifications",
        to: "/super-admin/notifications",
        icon: BellDot,
    },
    {
        id: 17,
        title: "Escalation Management",
        to: "/super-admin/escalation-management",
        icon: ShieldAlert,
    },
    {
        id: 18,
        title: "Activity Logs",
        to: "#0",
        icon: History,
        subLinks: [
            { icon: History, title: "Login History", to: "/super-admin/activity-logs/login-history" },
            { icon: FileText, title: "Data Changes", to: "/super-admin/activity-logs/data-changes" },
            { icon: FileX, title: "Deleted Records", to: "/super-admin/activity-logs/deleted-records" },
            { icon: ClipboardCheck, title: "Approval Actions", to: "/super-admin/activity-logs/approval-actions" },
            { icon: ShieldCheck, title: "Audit Logs", to: "/super-admin/activity-logs/audit-logs" },
            { icon: AlertTriangle, title: "Failed Logins", to: "/super-admin/activity-logs/failed-logins" },
            { icon: History, title: "Demo Activity", to: "/super-admin/activity-logs/demo-activity" },
        ],
    },
    {
        id: 19,
        title: "Re-entry Approvals",
        to: "/super-admin/reentry",
        icon: ClipboardCheck,
    },
    {
        id: 20,
        title: "Module Health",
        to: "/super-admin/module-health",
        icon: HeartPulse,
    },
];

export const adminSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Admissions",
        to: "#0",
        icon: FileText,
        subLinks: [
            { icon: FileText, title: "Admission Enquiry", to: "/admin/front-office/admission-enquiry" },
            { icon: FileText, title: "Admission List", to: "/admin/front-office/admission-list" },
        ],
    },
    {
        id: 3,
        title: "User Database",
        to: "#0",
        icon: UserRound,
        subLinks: [
            { icon: UserRound, title: "Student Database", to: "/admin/user-management/student-database" },
            { icon: UserRoundCog, title: "Employee Database", to: "/admin/user-management/employee-database" },
        ],
    },
    {
        id: 4,
        title: "Class Details",
        to: "/admin/class/class-details",
        icon: ClipboardList,
    },
    {
        id: 5,
        title: "Attendance",
        to: "#0",
        icon: CalendarCheck,
        subLinks: [
            { icon: GraduationCap, title: "Students", to: "/admin/attendance/students-list" },
            { icon: Briefcase, title: "Employees", to: "/admin/attendance/employees-list" },
        ],
    },
    {
        id: 6,
        title: "Activities",
        to: "#0",
        icon: Trophy,
        subLinks: [
            { icon: Palette, title: "Cultural", to: "/admin/activities/cultural-list" },
            { icon: Dumbbell, title: "Sports", to: "/admin/activities/sports-list" },
            { icon: Trophy, title: "Chess Result", to: "/admin/activities/chess-result" },
            { icon: Award, title: "Competitions", to: "/admin/activities/competitions-list" },
        ],
    },
    {
        id: 7,
        title: "Documents",
        to: "#0",
        icon: FolderOpen,
        subLinks: [
            { icon: FileText, title: "Student Documents", to: "/admin/documents/student-documents" },
            { icon: FileText, title: "Employee Documents", to: "/admin/documents/employee-documents" },
        ],
    },
    {
        id: 8,
        title: "Task Management",
        to: "#0",
        icon: ClipboardList,
        subLinks: [
            { icon: UserPlus, title: "Assign Tasks", to: "/admin/task-management/assign-tasks" },
            { icon: ListChecks, title: "Assigned Tasks", to: "/admin/task-management/assigned-tasks" },
        ],
    },
    {
        id: 9,
        title: "Leave Request",
        to: "#0",
        icon: FileX,
        subLinks: [
            { icon: FileText, title: "My Leave Requests", to: "/admin/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/admin/leave-request/received" },
        ],
    },
    {
        id: 10,
        title: "Announcement",
        to: "/admin/announcement",
        icon: Rss,
    },
    {
        id: 11,
        title: "TC Request Approval",
        to: "/admin/tc-request-approval",
        icon: FileText,
    },
    {
        id: 12,
        title: "Communication",
        to: "/admin/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 13,
        title: "Calendar",
        to: "/admin/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 14,
        title: "Notifications",
        to: "/admin/notifications",
        icon: BellDot,
    },
    {
        id: 15,
        title: "Escalation Management",
        to: "/admin/escalation-management",
        icon: ShieldAlert,
    },
    {
        id: 16,
        title: "RBAC",
        to: "#0",
        icon: ShieldCheck,
        subLinks: [
            { icon: UserPlus, title: "User Creation", to: "/admin/rbac/user-creation" },
            { icon: UsersRound, title: "Roles", to: "/admin/rbac/roles" },
        ],
    },
];

export const studentSidebarLinks = [
    {
        id: 1,
        title: "Class",
        to: "#0",
        icon: School,
        subLinks: [
            { icon: MonitorPlay, title: "Online Class", to: "/student/class/online-class" },
            { icon: UserPlus, title: "Extended Class", to: "/student/class/extra-class" },
            { icon: CalendarDays, title: "Timetable", to: "/student/class/timetable-list" },
            { icon: UsersRound, title: "Attendance List", to: "/student/class/attendance-list" },
        ],
    },
    {
        id: 2,
        title: "Student Evaluation",
        to: "#0",
        icon: Award,
        subLinks: [
            { icon: ClipboardCheck, title: "Exam Result", to: "/student/student-evaluation/exam-result" },
            { icon: CalendarDays, title: "Exam Schedule", to: "/student/student-evaluation/exam-schedule" },
        ],
    },
    {
        id: 3,
        title: "Student Deliverables",
        to: "#0",
        icon: Package,
        subLinks: [
            { icon: Sparkles, title: "Home Fun", to: "/student/student-deliverables/home-fun" },
            { icon: BookOpenCheck, title: "Study Materials", to: "/student/student-deliverables/study-materials" },
            { icon: CircleHelp, title: "Sample Questions", to: "/student/student-deliverables/sample-questions" },
        ],
    },
    {
        id: 4,
        title: "Star Ratings",
        to: "/student/star-ratings/view-ratings",
        icon: Star,
    },
    {
        id: 5,
        title: "Library",
        to: "#0",
        icon: Library,
        subLinks: [
            { icon: BookMarked, title: "Borrowed Books", to: "/student/library/borrowed-books-list" },
        ],
    },
    {
        id: 6,
        title: "Transport",
        to: "#0",
        icon: Van,
        subLinks: [
            { icon: Route, title: "Bus Route", to: "/student/transport/bus-route-details" },
            { icon: MapPin, title: "Track Bus", to: "/student/transport/track-bus" },
        ],
    },
    {
        id: 7,
        title: "Hostel Details",
        to: "/student/hostel/hostel-details",
        icon: Bed,
    },
    {
        id: 8,
        title: "Payment Details",
        to: "#0",
        icon: Wallet,
        subLinks: [
            { icon: BadgeDollarSign, title: "Fees Payment", to: "/student/payment/fees-payment" },
            { icon: Bed, title: "Hostel Payment", to: "/student/payment/hostel-payment" },
            { icon: Bus, title: "Transport Payment", to: "/student/payment/transport-payment" },
        ],
    },
    {
        id: 9,
        title: "Announcement",
        to: "/student/announcement",
        icon: Rss,
    },
    {
        id: 10,
        title: "TC Request",
        to: "/student/tc-request",
        icon: FileText,
    },
    {
        id: 11,
        title: "Communication",
        to: "/student/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 12,
        title: "Calendar",
        to: "/student/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 13,
        title: "Notifications",
        to: "/student/notifications",
        icon: BellDot,
    },
    {
        id: 14,
        title: "Escalation Management",
        to: "/student/escalation-management",
        icon: ShieldAlert,
    },
];

export const parentSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/parent/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Class",
        to: "#0",
        icon: School,
        subLinks: [
            { icon: MonitorPlay, title: "Online Class", to: "/parent/class/online-class" },
            { icon: UserPlus, title: "Extended Class", to: "/parent/class/extra-class" },
            { icon: CalendarDays, title: "Timetable", to: "/parent/class/timetable-list" },
            { icon: UsersRound, title: "Attendance List", to: "/parent/class/attendance-list" },
        ],
    },
    {
        id: 3,
        title: "Student Evaluation",
        to: "#0",
        icon: Award,
        subLinks: [
            { icon: ClipboardCheck, title: "Exam Result", to: "/parent/student-evaluation/exam-result" },
            { icon: CalendarDays, title: "Exam Schedule", to: "/parent/student-evaluation/exam-schedule" },
            { icon: BarChart3, title: "Performance Analytics", to: "/parent/student-evaluation/analytics" },
        ],
    },
    {
        id: 4,
        title: "Student Deliverables",
        to: "#0",
        icon: Package,
        subLinks: [
            { icon: Sparkles, title: "Home Fun", to: "/parent/student-deliverables/home-fun" },
            { icon: BookOpenCheck, title: "Study Materials", to: "/parent/student-deliverables/study-materials" },
            { icon: CircleHelp, title: "Sample Questions", to: "/parent/student-deliverables/sample-questions" },
        ],
    },
    {
        id: 5,
        title: "Library",
        to: "#0",
        icon: Library,
        subLinks: [
            { icon: BookMarked, title: "Borrowed Books", to: "/parent/library/borrowed-books-list" },
        ],
    },
    {
        id: 6,
        title: "Transport",
        to: "#0",
        icon: Van,
        subLinks: [
            { icon: MapPin, title: "Track Bus", to: "/parent/transport/track-bus" },
        ],
    },
    {
        id: 7,
        title: "Hostel Details",
        to: "/parent/hostel/hostel-details",
        icon: Bed,
    },
    {
        id: 8,
        title: "Fees Payment",
        to: "#0",
        icon: Wallet,
        subLinks: [
            { icon: BadgeDollarSign, title: "Academic Payment", to: "/parent/payment/fees-payment" },
            { icon: Bed, title: "Hostel Payment", to: "/parent/payment/hostel-payment" },
            { icon: Bus, title: "Transport Payment", to: "/parent/payment/transport-payment" },
        ],
    },
    {
        id: 9,
        title: "Announcement",
        to: "/parent/announcement",
        icon: Rss,
    },
    {
        id: 10,
        title: "TC Request",
        to: "/parent/tc-request",
        icon: FileText,
    },
    {
        id: 11,
        title: "Communication",
        to: "/parent/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 12,
        title: "Calendar",
        to: "/parent/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 13,
        title: "Notifications",
        to: "/parent/notifications",
        icon: BellDot,
    },
    {
        id: 14,
        title: "Escalation Management",
        to: "/parent/escalation-management",
        icon: ShieldAlert,
    },
];

export const prmSidebarLinks = [
    {
        id: 1,
        title: "Admission Enquiry",
        to: "/front-office/admission-enquiry",
        icon: FileText,
    },
    {
        id: 2,
        title: "Admission List",
        to: "/front-office/admission-list",
        icon: FileText,
    },
    {
        id: 3,
        title: "User Database",
        to: "#0",
        icon: Users,
        subLinks: [
            { icon: UserRound, title: "Student Database", to: "/front-office/student-management" },
            { icon: UserRoundCog, title: "Teacher Database", to: "/front-office/teacher-management" },
        ],
    },
    {
        id: 4,
        title: "Student Transfer",
        to: "/front-office/student-transfer",
        icon: UsersRound,
    },
    {
        id: 5,
        title: "Student Re-Enrollment",
        to: "/front-office/student-re-enrollment",
        icon: UserPlus,
    },
    {
        id: 6,
        title: "TC Request",
        to: "/front-office/tc-request",
        icon: FileText,
    },
    {
        id: 7,
        title: "Gate Pass",
        to: "#0",
        icon: ArrowRightLeft,
        subLinks: [
            { icon: ArrowRightLeft, title: "Student Gate Pass", to: "/front-office/gate-pass-list" },
            { icon: Bed, title: "Hostel Gate Pass", to: "/front-office/hostel-gate-pass-list" },
            { icon: ClipboardList, title: "Material Gate Pass", to: "/front-office/material-gate-pass-list" },
            { icon: Package, title: "Goods Received Pass", to: "/front-office/goods-received-pass-list" },
        ],
    },
    {
        id: 8,
        title: "Task Management",
        to: "#0",
        icon: ClipboardList,
        subLinks: [
            { icon: UserPlus, title: "Assign Tasks", to: "/front-office/task-management/assign-tasks" },
            { icon: ListChecks, title: "My Tasks", to: "/front-office/task-management/my-tasks" },
        ],
    },
    {
        id: 9,
        title: "Leave Request",
        to: "#0",
        icon: FileX,
        subLinks: [
            { icon: FileText, title: "My Leave Requests", to: "/front-office/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/front-office/leave-request/received" },
        ],
    },
    {
        id: 10,
        title: "My Attendance",
        to: "/front-office/attendance/my-attendance",
        icon: CalendarCheck,
    },
    {
        id: 11,
        title: "Announcement",
        to: "/front-office/announcement",
        icon: Rss,
    },
    {
        id: 12,
        title: "Communication",
        to: "/front-office/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 13,
        title: "Calendar",
        to: "/front-office/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 14,
        title: "Notifications",
        to: "/front-office/notifications",
        icon: BellDot,
    },
    {
        id: 15,
        title: "Escalation Management",
        to: "/front-office/escalation-management",
        icon: ShieldAlert,
    },
];

export const librarianSidebarLinks = [
    {
        id: 1,
        title: "Book Management",
        to: "#0",
        icon: Library,
        subLinks: [
            { icon: BookOpenCheck, title: "Book List", to: "/librarian/book-management/book-list" },
        ],
    },
    {
        id: 2,
        title: "Issued Books",
        to: "/librarian/issued-books/issued-book-list",
        icon: BookMarked,
    },
    {
        id: 3,
        title: "Members",
        to: "/librarian/members/member-list",
        icon: UsersRound,
    },
    {
        id: 4,
        title: "Task Management",
        to: "/librarian/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 5,
        title: "My Attendance",
        to: "/librarian/attendance/my-attendance",
        icon: CalendarCheck,
    },
    {
        id: 6,
        title: "Announcement",
        to: "/librarian/announcement",
        icon: Rss,
    },
    {
        id: 7,
        title: "Communication",
        to: "/librarian/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 8,
        title: "Calendar",
        to: "/librarian/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 9,
        title: "Notifications",
        to: "/librarian/notifications",
        icon: BellDot,
    },
    {
        id: 10,
        title: "Escalation Management",
        to: "/librarian/escalation-management",
        icon: ShieldAlert,
    },
];

export const gateKeeperSidebarLinks = [
    {
        id: 1,
        title: "Hostel Gate Pass",
        to: "/gate-keeper/hostel-gate-pass",
        icon: DoorOpen,
    },
    {
        id: 2,
        title: "My Duty",
        to: "/gate-keeper/my-duty",
        icon: ShieldCheck,
    },
    {
        id: 3,
        title: "CSO / Gate Keeper",
        to: "/gate-keeper/incidents",
        icon: ShieldAlert,
    },
    {
        id: 4,
        title: "Gate Pass",
        to: "/gate-keeper/gate-pass-list",
        icon: ArrowRightLeft,
    },
    {
        id: 5,
        title: "Task Management",
        to: "/gate-keeper/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 6,
        title: "Leave Request",
        to: "/gate-keeper/leave-request/my-requests",
        icon: FileX,
    },
    {
        id: 7,
        title: "My Attendance",
        to: "/gate-keeper/attendance/my-attendance",
        icon: CalendarCheck,
    },
    {
        id: 8,
        title: "Announcement",
        to: "/gate-keeper/broadcast-list",
        icon: Rss,
    },
    {
        id: 9,
        title: "Communication",
        to: "/gate-keeper/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 10,
        title: "Calendar",
        to: "/gate-keeper/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 11,
        title: "Notifications",
        to: "/gate-keeper/notifications",
        icon: BellDot,
    },
    {
        id: 12,
        title: "Escalation Management",
        to: "/gate-keeper/escalation-management",
        icon: ShieldAlert,
    },
    {
        id: 13,
        title: "Visitors",
        to: "/gate-keeper/visitors",
        icon: UserRound,
    },
    {
        id: 14,
        title: "Inward / Outward",
        to: "/gate-keeper/registers",
        icon: ArrowRightLeft,
    },
    {
        id: 15,
        title: "Handover",
        to: "/gate-keeper/handover",
        icon: ShieldCheck,
    },
    {
        id: 16,
        title: "Vendors",
        to: "/gate-keeper/vendors",
        icon: Briefcase,
    },
];

export const gateKeeperManagerSidebarLinks = [
    {
        id: 1,
        title: "Assign Duty List",
        to: "/gatekeeper-manager/assign-duty-list",
        icon: ShieldCheck,
    },
    {
        id: 2,
        title: "Incidents Management List",
        to: "/gatekeeper-manager/incidents-list",
        icon: ShieldAlert,
    },
    {
        id: 3,
        title: "Attendance",
        to: "#0",
        icon: CalendarCheck,
        subLinks: [
            { icon: UserRound, title: "My Attendance", to: "/gatekeeper-manager/attendance/my-attendance" },
            { icon: ClipboardList, title: "Gatekeepers Attendance", to: "/gatekeeper-manager/attendance/gatekeepers-attendance" },
        ],
    },
    {
        id: 4,
        title: "Task Management",
        to: "#0",
        icon: ClipboardList,
        subLinks: [
            { icon: UserPlus, title: "Assign Tasks", to: "/gatekeeper-manager/task-management/assign-tasks" },
            { icon: ListChecks, title: "My Tasks", to: "/gatekeeper-manager/task-management/my-tasks" },
        ],
    },
    {
        id: 5,
        title: "Leave Request",
        to: "#0",
        icon: FileX,
        subLinks: [
            { icon: FileText, title: "My Leave Requests", to: "/gatekeeper-manager/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/gatekeeper-manager/leave-request/received" },
        ],
    },
    {
        id: 6,
        title: "Announcement",
        to: "/gatekeeper-manager/gatekeeper-broadcast-list",
        icon: Rss,
    },
    {
        id: 7,
        title: "Communication",
        to: "/gatekeeper-manager/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 8,
        title: "Calendar",
        to: "/gatekeeper-manager/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 9,
        title: "Notifications",
        to: "/gatekeeper-manager/notifications",
        icon: BellDot,
    },
    {
        id: 10,
        title: "Escalation Management",
        to: "/gatekeeper-manager/escalation-management",
        icon: ShieldAlert,
    },
];

export const canteenManagerSidebarLinks = [
    {
        id: 1,
        title: "Café",
        to: "/canteen-manager/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Menu Management",
        to: "/canteen-manager/menu-management",
        icon: UtensilsCrossed,
    },
    {
        id: 3,
        title: "Inventory Management",
        to: "/canteen-manager/inventory",
        icon: Package,
    },
    {
        id: 4,
        title: "Orders",
        to: "/canteen-manager/orders",
        icon: ShoppingCart,
    },
    {
        id: 5,
        title: "Requests & Approvals",
        to: "/canteen-manager/requests-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 6,
        title: "Reports",
        to: "/canteen-manager/reports",
        icon: BarChart3,
    },
    {
        id: 7,
        title: "Announcement",
        to: "/canteen-manager/broadcast",
        icon: Rss,
    },
];

export const itSupportManagerSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/it-support-manager/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Asset Management",
        to: "/it-support-manager/asset-management",
        icon: Monitor,
    },
    {
        id: 21,
        title: "Maintenance Inventory",
        to: "/it-support-manager/maintenance-inventory",
        icon: ClipboardList,
    },
    {
        id: 3,
        title: "Tickets",
        to: "/it-support-manager/support-tickets",
        icon: Ticket,
    },
    {
        id: 4,
        title: "Requests & Approvals",
        to: "/it-support-manager/requests-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 5,
        title: "Reports",
        to: "/it-support-manager/reports",
        icon: BarChart3,
    },
    {
        id: 6,
        title: "Announcement",
        to: "/it-support-manager/broadcast",
        icon: Rss,
    },
    {
        id: 7,
        title: "Data Import",
        to: "/it-support-manager/data-import",
        icon: FileText,
    },
    {
        id: 8,
        title: "Purchase Workflow",
        to: "/it-support-manager/purchase-workflow",
        icon: ClipboardCheck,
    },
];

export const stationeryStoreManagerSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/stationery-store-manager/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Stores",
        to: "/stationery-store-manager/inventory",
        icon: Package,
    },
    {
        id: 3,
        title: "Issue & Returns",
        to: "/stationery-store-manager/issue-returns",
        icon: ArrowRightLeft,
    },
    {
        id: 4,
        title: "Requests & Approvals",
        to: "/stationery-store-manager/requests-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 5,
        title: "Reports",
        to: "/stationery-store-manager/reports",
        icon: BarChart3,
    },
    {
        id: 6,
        title: "Announcement",
        to: "/stationery-store-manager/broadcast",
        icon: Rss,
    },
    {
        id: 7,
        title: "Requirements",
        to: "/stationery-store-manager/requirements",
        icon: ClipboardList,
    },
    {
        id: 8,
        title: "Stock Issue",
        to: "/stationery-store-manager/stock-issue",
        icon: ArrowRightLeft,
    },
    {
        id: 9,
        title: "Critical Alerts",
        to: "/stationery-store-manager/critical-alerts",
        icon: AlertTriangle,
    },
    {
        id: 10,
        title: "Purchase Workflow",
        to: "/stationery-store-manager/purchase-workflow",
        icon: ClipboardCheck,
    },
];

export const housekeepingManagerSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/housekeeping-manager/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Task Management",
        to: "/housekeeping-manager/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 3,
        title: "Inventory",
        to: "/housekeeping-manager/inventory",
        icon: Package,
    },
    {
        id: 4,
        title: "Requests & Approvals",
        to: "/housekeeping-manager/requests-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 5,
        title: "Reports",
        to: "/housekeeping-manager/reports",
        icon: BarChart3,
    },
    {
        id: 6,
        title: "Announcement",
        to: "/housekeeping-manager/broadcast",
        icon: Rss,
    },
    {
        id: 7,
        title: "Duty Allotment",
        to: "/housekeeping-manager/duty-allotment",
        icon: ClipboardList,
    },
    {
        id: 8,
        title: "Schedules",
        to: "/housekeeping-manager/schedules",
        icon: CalendarDays,
    },
    {
        id: 9,
        title: "Star of the Month",
        to: "/housekeeping-manager/star-of-the-month",
        icon: Star,
    },
    {
        id: 10,
        title: "RO Testing",
        to: "/housekeeping-manager/ro-testing",
        icon: ClipboardCheck,
    },
    {
        id: 11,
        title: "Lost & Found",
        to: "/housekeeping-manager/lost-found",
        icon: Package,
    },
    {
        id: 12,
        title: "Inventory Requirement",
        to: "/housekeeping-manager/inventory-requirement",
        icon: ShoppingCart,
    },
    {
        id: 13,
        title: "Purchase Workflow",
        to: "/housekeeping-manager/purchase-workflow",
        icon: ClipboardCheck,
    },
];

export const teacherSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/teacher/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Attendance",
        to: "#0",
        icon: CalendarCheck,
        subLinks: [
            { icon: ClipboardList, title: "Class Attendance", to: "/teacher/attendance/class-attendance" },
            { icon: HeartPulse, title: "Biometric Attendance", to: "/teacher/attendance/biometric" },
        ],
    },
    {
        id: 3,
        title: "Class",
        to: "#0",
        icon: School,
        subLinks: [
            { icon: CalendarDays, title: "Class Timetable", to: "/teacher/class/class-routine" },
            { icon: NotebookPen, title: "Lesson Plan", to: "/teacher/lesson-plan/my-lesson-plan" },
            { icon: ClipboardCheck, title: "Lesson Plan Approval", to: "/teacher/lesson-plan-approval" },
            { icon: UserPlus, title: "Extended Class", to: "/teacher/class/extra-class" },
            { icon: MonitorPlay, title: "Online Class", to: "/teacher/class/online-class" },
        ],
    },
    {
        id: 5,
        title: "Task Management",
        to: "/teacher/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 7,
        title: "Student",
        to: "#0",
        icon: GraduationCap,
        subLinks: [
            { icon: GraduationCap, title: "Students List", to: "/teacher/user-management/students-list" },
            { icon: UsersRound, title: "Parents List", to: "/teacher/user-management/parents-list" },
            { icon: FileText, title: "CA / RCT", to: "/teacher/unit-tests" },
            { icon: CalendarCheck, title: "Exam", to: "/teacher/student-evaluation/exam" },
            { icon: CircleHelp, title: "Question Bank", to: "/teacher/student-deliverables/sample-questions" },
            { icon: ClipboardPen, title: "Mark Entry", to: "/teacher/student-evaluation/mark-entry" },
            { icon: BarChart3, title: "Performance Analytics", to: "/teacher/student-evaluation/analytics" },
            { icon: Sparkles, title: "Home Fun", to: "/teacher/student-deliverables/home-fun" },
            { icon: BookOpenCheck, title: "Study Materials", to: "/teacher/student-deliverables/study-materials" },
            { icon: Star, title: "Star of the Month", to: "/teacher/star-ratings/som-matrix" },
            { icon: Trophy, title: "Star of the Year", to: "/teacher/star-ratings/star-of-year" },
        ],
    },
    {
        id: 19,
        title: "My Profile",
        to: "#0",
        icon: UserRound,
        subLinks: [
            { icon: UserRound, title: "My Profile", to: "/teacher/my-profile" },
            { icon: CalendarCheck, title: "My Attendance", to: "/teacher/attendance/my-attendance" },
            { icon: FileText, title: "My Leave Requests", to: "/teacher/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/teacher/leave-request/received" },
            { icon: BookMarked, title: "Books Borrowed", to: "/teacher/library/books-borrowed" },
        ],
    },
    {
        id: 14,
        title: "Announcement",
        to: "/teacher/announcement",
        icon: Rss,
    },
    {
        id: 15,
        title: "Communication",
        to: "/teacher/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 16,
        title: "Calendar",
        to: "/teacher/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 17,
        title: "Notifications",
        to: "/teacher/notifications",
        icon: BellDot,
    },
    {
        id: 18,
        title: "Escalation Management",
        to: "/teacher/escalation-management",
        icon: ShieldAlert,
    },
];

export const coordinatorSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/coordinator/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Attendance",
        to: "#0",
        icon: CalendarCheck,
        subLinks: [
            { icon: ClipboardList, title: "Class Attendance", to: "/coordinator/attendance/class-attendance" },
        ],
    },
    {
        id: 3,
        title: "Class",
        to: "#0",
        icon: School,
        subLinks: [
            { icon: CalendarDays, title: "Class Timetable", to: "/coordinator/class/class-routine" },
            { icon: NotebookPen, title: "Lesson Plan", to: "/coordinator/lesson-plan/my-lesson-plan" },
            { icon: ClipboardCheck, title: "Lesson Plan Approval", to: "/coordinator/lesson-plan-approval" },
            { icon: UserPlus, title: "Extended Class", to: "/coordinator/class/extra-class" },
            { icon: MonitorPlay, title: "Online Class", to: "/coordinator/class/online-class" },
        ],
    },
    {
        id: 5,
        title: "Task Management",
        to: "/coordinator/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 7,
        title: "Student",
        to: "#0",
        icon: GraduationCap,
        subLinks: [
            { icon: GraduationCap, title: "Students List", to: "/coordinator/user-management/students-list" },
            { icon: UsersRound, title: "Parents List", to: "/coordinator/user-management/parents-list" },
            { icon: FileText, title: "CA / RCT", to: "/coordinator/unit-tests" },
            { icon: CalendarCheck, title: "Exam", to: "/coordinator/student-evaluation/exam" },
            { icon: CircleHelp, title: "Question Bank", to: "/coordinator/student-deliverables/sample-questions" },
            { icon: ClipboardPen, title: "Mark Entry", to: "/coordinator/student-evaluation/mark-entry" },
            { icon: BarChart3, title: "Performance Analytics", to: "/coordinator/student-evaluation/analytics" },
            { icon: HeartPulse, title: "Biometric Attendance", to: "/coordinator/attendance/biometric" },
            { icon: Sparkles, title: "Home Fun", to: "/coordinator/student-deliverables/home-fun" },
            { icon: BookOpenCheck, title: "Study Materials", to: "/coordinator/student-deliverables/study-materials" },
            { icon: Star, title: "Star of the Month", to: "/coordinator/star-ratings/som-matrix" },
            { icon: Trophy, title: "Star of the Year", to: "/coordinator/star-ratings/star-of-year" },
        ],
    },
    {
        id: 19,
        title: "My Profile",
        to: "#0",
        icon: UserRound,
        subLinks: [
            { icon: UserRound, title: "My Profile", to: "/coordinator/my-profile" },
            { icon: CalendarCheck, title: "My Attendance", to: "/coordinator/attendance/my-attendance" },
            { icon: FileText, title: "My Leave Requests", to: "/coordinator/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/coordinator/leave-request/received" },
            { icon: BookMarked, title: "Books Borrowed", to: "/coordinator/library/books-borrowed" },
        ],
    },
    {
        id: 14,
        title: "Announcement",
        to: "/coordinator/announcement",
        icon: Rss,
    },
    {
        id: 15,
        title: "Communication",
        to: "/coordinator/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 16,
        title: "Calendar",
        to: "/coordinator/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 17,
        title: "Notifications",
        to: "/coordinator/notifications",
        icon: BellDot,
    },
    {
        id: 18,
        title: "Escalation Management",
        to: "/coordinator/escalation-management",
        icon: ShieldAlert,
    },
];

export const transportManagerSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/transport-manager/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Driver Management",
        to: "/transport-manager/driver-management",
        icon: Car,
    },
    {
        id: 3,
        title: "Vehicle Management",
        to: "/transport-manager/vehicle-management",
        icon: Bus,
    },
    {
        id: 4,
        title: "Route Management",
        to: "/transport-manager/route-management",
        icon: Route,
    },
    {
        id: 5,
        title: "Route Data",
        to: "/transport-manager/route-data",
        icon: MapPin,
    },
    {
        id: 6,
        title: "Student Transport",
        to: "/transport-manager/student-transport",
        icon: GraduationCap,
    },
    {
        id: 7,
        title: "Assign Duty",
        to: "/transport-manager/assign-duty",
        icon: ListChecks,
    },
    {
        id: 8,
        title: "Vehicle Maintenance",
        to: "/transport-manager/vehicle-maintenance",
        icon: Monitor,
    },
    {
        id: 9,
        title: "Request Approvals",
        to: "/transport-manager/request-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 10,
        title: "Transport Expenses",
        to: "/transport-manager/transport-expenses",
        icon: Wallet,
    },
    {
        id: 11,
        title: "Leave Request",
        to: "/transport-manager/leave-request",
        icon: FileX,
    },
    {
        id: 13,
        title: "Building Maintenance",
        to: "/transport-manager/building-maintenance",
        icon: Landmark,
    },
];

export const jointDirectorSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/joint-director/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Task Management",
        to: "/joint-director/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 3,
        title: "Employee Management",
        to: "#0",
        icon: UsersRound,
        subLinks: [
            { icon: UserRoundCog, title: "JD Assistant", to: "/joint-director/employee-management/jd-assistant" },
            { icon: UtensilsCrossed, title: "Canteen Manager", to: "/joint-director/employee-management/canteen-manager" },
            { icon: ShoppingCart, title: "Store Manager", to: "/joint-director/employee-management/store-manager" },
            { icon: Monitor, title: "IT Team Manager", to: "/joint-director/employee-management/it-team-manager" },
            { icon: Bus, title: "Transport Manager", to: "/joint-director/employee-management/transport-manager" },
            { icon: Sparkles, title: "House Keeping Manager", to: "/joint-director/employee-management/housekeeping-manager" },
            { icon: Car, title: "Drivers List", to: "/joint-director/employee-management/drivers" },
        ],
    },
    {
        id: 4,
        title: "Request Approvals",
        to: "/joint-director/request-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 5,
        title: "Escalations",
        to: "/joint-director/escalations",
        icon: ShieldAlert,
    },
    {
        id: 6,
        title: "Meetings & Calendar",
        to: "/joint-director/meetings-calendar",
        icon: CalendarDays,
    },
    {
        id: 7,
        title: "Assets & Inventory Overview",
        to: "/joint-director/assets-inventory",
        icon: Package,
    },
    {
        id: 8,
        title: "Announcement",
        to: "/joint-director/broadcast",
        icon: Rss,
    },
];

export const jointDirectorAssistantSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/joint-director-assistant/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Task Management",
        to: "/joint-director-assistant/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 3,
        title: "Employee Management",
        to: "#0",
        icon: UsersRound,
        subLinks: [
            { icon: UtensilsCrossed, title: "Canteen Manager", to: "/joint-director-assistant/employee-management/canteen-manager" },
            { icon: ShoppingCart, title: "Store Manager", to: "/joint-director-assistant/employee-management/store-manager" },
            { icon: Monitor, title: "IT Team Manager", to: "/joint-director-assistant/employee-management/it-team-manager" },
            { icon: Bus, title: "Transport Manager", to: "/joint-director-assistant/employee-management/transport-manager" },
            { icon: Sparkles, title: "House Keeping Manager", to: "/joint-director-assistant/employee-management/housekeeping-manager" },
            { icon: Car, title: "Drivers List", to: "/joint-director-assistant/employee-management/drivers" },
        ],
    },
    {
        id: 4,
        title: "Request Approvals",
        to: "/joint-director-assistant/request-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 5,
        title: "Escalations",
        to: "/joint-director-assistant/escalations",
        icon: ShieldAlert,
    },
    {
        id: 6,
        title: "Meetings & Calendar",
        to: "/joint-director-assistant/meetings-calendar",
        icon: CalendarDays,
    },
    {
        id: 7,
        title: "Assets & Inventory Overview",
        to: "/joint-director-assistant/assets-inventory",
        icon: Package,
    },
    {
        id: 8,
        title: "Announcement",
        to: "/joint-director-assistant/broadcast",
        icon: Rss,
    },
];

export const jointDirectorAuditSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/joint-director-audit/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Audit Configuration",
        to: "#0",
        icon: Settings,
        subLinks: [
            { icon: FileText, title: "Audit Templates", to: "/joint-director-audit/audit-configuration/audit-templates" },
            { icon: ListChecks, title: "Checklist Sections", to: "/joint-director-audit/audit-configuration/checklist-sections" },
            { icon: CircleHelp, title: "Question Bank", to: "/joint-director-audit/audit-configuration/question-bank" },
            { icon: MessageCircle, title: "Response Types", to: "/joint-director-audit/audit-configuration/response-types" },
            { icon: Trophy, title: "Scoring Rules", to: "/joint-director-audit/audit-configuration/scoring-rules" },
            { icon: Route, title: "Workflow Rules", to: "/joint-director-audit/audit-configuration/workflow-rules" },
            { icon: ShieldCheck, title: "Visibility Rules", to: "/joint-director-audit/audit-configuration/visibility-rules" },
            { icon: History, title: "Template Versioning", to: "/joint-director-audit/audit-configuration/template-versioning" },
            { icon: Send, title: "Publish Templates", to: "/joint-director-audit/audit-configuration/publish-templates" },
        ],
    },
    {
        id: 3,
        title: "Audit Planning",
        to: "/joint-director-audit/audit-planning",
        icon: ClipboardPen,
    },
    {
        id: 4,
        title: "Audit Assignment",
        to: "#0",
        icon: ClipboardList,
        subLinks: [
            { icon: ClipboardPen, title: "Assign Audits", to: "/joint-director-audit/audit-assignment/assign-audits" },
            { icon: History, title: "Assignment History", to: "/joint-director-audit/audit-assignment/assignment-history" },
            { icon: BarChart3, title: "Workload Overview", to: "/joint-director-audit/audit-assignment/workload-overview" },
            { icon: ArrowRightLeft, title: "Reassign Audit", to: "/joint-director-audit/audit-assignment/reassign-audit" },
        ],
    },
    {
        id: 5,
        title: "Audit Monitoring",
        to: "/joint-director-audit/audit-monitoring",
        icon: ListChecks,
    },
    {
        id: 6,
        title: "Findings & Compliance",
        to: "/joint-director-audit/findings-compliance",
        icon: ShieldCheck,
    },
    {
        id: 7,
        title: "Reports & Analytics",
        to: "/joint-director-audit/reports-analytics",
        icon: BarChart3,
    },
    {
        id: 8,
        title: "Task Management",
        to: "/joint-director-audit/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 9,
        title: "Employee Management",
        to: "#0",
        icon: UsersRound,
        subLinks: [
            { icon: Users, title: "HR Manager", to: "/joint-director-audit/employee-management/hr-manager" },
            { icon: UserRound, title: "HR Executive", to: "/joint-director-audit/employee-management/hr-executive" },
            { icon: ClipboardList, title: "Process Audit Manager", to: "/joint-director-audit/employee-management/process-audit-manager" },
            { icon: ListChecks, title: "Process Audit Executive", to: "/joint-director-audit/employee-management/process-audit-executive" },
            { icon: GraduationCap, title: "Quality Audit Principal", to: "/joint-director-audit/employee-management/quality-audit-principal" },
            { icon: BookOpenCheck, title: "Quality Audit Executive", to: "/joint-director-audit/employee-management/quality-audit-executive" },
        ],
    },
    {
        id: 10,
        title: "Request Approvals",
        to: "/joint-director-audit/request-approvals",
        icon: ClipboardCheck,
    },
    {
        id: 11,
        title: "Escalations",
        to: "/joint-director-audit/escalations",
        icon: ShieldAlert,
    },
    {
        id: 12,
        title: "Meetings & Calendar",
        to: "/joint-director-audit/meetings-calendar",
        icon: CalendarDays,
    },
    {
        id: 13,
        title: "Announcement",
        to: "/joint-director-audit/broadcast",
        icon: Rss,
    },
];

export const processAuditorSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/process-auditor/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Audit Management",
        to: "#0",
        icon: ClipboardPen,
        subLinks: [
            { icon: ClipboardList, title: "My Audits", to: "/process-auditor/audit-management/my-audits" },
            { icon: CalendarDays, title: "Audit Schedule", to: "/process-auditor/audit-management/audit-schedule" },
            { icon: History, title: "Audit History", to: "/process-auditor/audit-management/audit-history" },
        ],
    },
    {
        id: 3,
        title: "Observations",
        to: "#0",
        icon: ShieldAlert,
        subLinks: [
            { icon: AlertTriangle, title: "Open Observations", to: "/process-auditor/observations/open" },
            { icon: ShieldCheck, title: "Closed Observations", to: "/process-auditor/observations/closed" },
        ],
    },
    {
        id: 4,
        title: "Corrective Actions",
        to: "#0",
        icon: ShieldCheck,
        subLinks: [
            { icon: ShieldAlert, title: "Escalations", to: "/process-auditor/corrective-actions/escalations" },
            { icon: CircleHelp, title: "Root Cause Analysis", to: "/process-auditor/corrective-actions/root-cause-analysis" },
            { icon: FileText, title: "Action Taken Reports", to: "/process-auditor/corrective-actions/action-taken-reports" },
        ],
    },
    {
        id: 5,
        title: "Reports",
        to: "#0",
        icon: BarChart3,
        subLinks: [
            { icon: FileText, title: "Audit Reports", to: "/process-auditor/reports/audit-reports" },
            { icon: ShieldAlert, title: "Observation Reports", to: "/process-auditor/reports/observation-reports" },
            { icon: BarChart3, title: "Compliance Reports", to: "/process-auditor/reports/compliance-reports" },
            { icon: AlertTriangle, title: "Pending Actions", to: "/process-auditor/reports/pending-actions" },
            { icon: ShieldCheck, title: "Closed Actions", to: "/process-auditor/reports/closed-actions" },
        ],
    },
    {
        id: 6,
        title: "Communication",
        to: "/process-auditor/communication",
        icon: MessageCircle,
    },
    {
        id: 7,
        title: "Components & Rubrics",
        to: "/process-auditor/components",
        icon: ClipboardList,
    },
    {
        id: 8,
        title: "Shared Deviations",
        to: "/process-auditor/shared-deviations",
        icon: ShieldAlert,
    },
];

export const qualityAuditorSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/quality-auditor/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Audit Management",
        to: "#0",
        icon: ClipboardPen,
        subLinks: [
            { icon: ClipboardList, title: "My Audits", to: "/quality-auditor/audit-management/my-audits" },
            { icon: CalendarDays, title: "Audit Schedule", to: "/quality-auditor/audit-management/audit-schedule" },
            { icon: History, title: "Audit History", to: "/quality-auditor/audit-management/audit-history" },
        ],
    },
    {
        id: 3,
        title: "Observations",
        to: "#0",
        icon: ShieldAlert,
        subLinks: [
            { icon: AlertTriangle, title: "Open Observations", to: "/quality-auditor/observations/open" },
            { icon: ShieldCheck, title: "Closed Observations", to: "/quality-auditor/observations/closed" },
        ],
    },
    {
        id: 4,
        title: "Corrective Actions",
        to: "#0",
        icon: ShieldCheck,
        subLinks: [
            { icon: ShieldAlert, title: "Escalations", to: "/quality-auditor/corrective-actions/escalations" },
            { icon: CircleHelp, title: "Root Cause Analysis", to: "/quality-auditor/corrective-actions/root-cause-analysis" },
            { icon: FileText, title: "Action Taken Reports", to: "/quality-auditor/corrective-actions/action-taken-reports" },
        ],
    },
    {
        id: 5,
        title: "Reports",
        to: "#0",
        icon: BarChart3,
        subLinks: [
            { icon: FileText, title: "Audit Reports", to: "/quality-auditor/reports/audit-reports" },
            { icon: ShieldAlert, title: "Observation Reports", to: "/quality-auditor/reports/observation-reports" },
            { icon: BarChart3, title: "Compliance Reports", to: "/quality-auditor/reports/compliance-reports" },
            { icon: AlertTriangle, title: "Pending Actions", to: "/quality-auditor/reports/pending-actions" },
            { icon: ShieldCheck, title: "Closed Actions", to: "/quality-auditor/reports/closed-actions" },
        ],
    },
    {
        id: 6,
        title: "Communication",
        to: "/quality-auditor/communication",
        icon: MessageCircle,
    },
    {
        id: 7,
        title: "Components & Rubrics",
        to: "/quality-auditor/components",
        icon: ClipboardList,
    },
    {
        id: 8,
        title: "Shared Deviations",
        to: "/quality-auditor/shared-deviations",
        icon: ShieldAlert,
    },
];

export const hrSidebarLinks = [
    { id: 1, title: "Dashboard", to: "/hr/dashboard", icon: LayoutDashboard },
    {
        id: 2, title: "Staff Management", to: "#0", icon: UsersRound,
        subLinks: [
            { icon: Users, title: "Employees", to: "/hr/employee-management/employees" },
            { icon: FileText, title: "Employee Documents", to: "/hr/employee-management/documents" },
        ],
    },
    {
        id: 3, title: "Recruitment", to: "#0", icon: Briefcase,
        subLinks: [
            { icon: ClipboardList, title: "Job Openings", to: "/hr/recruitment/job-openings" },
            { icon: UserRoundSearch, title: "Candidates", to: "/hr/recruitment/candidates" },
            { icon: CalendarCheck, title: "Interviews", to: "/hr/recruitment/interviews" },
            { icon: ClipboardPen, title: "Interview Feedback", to: "/hr/recruitment/interview-feedback" },
        ],
    },
    {
        id: 4, title: "Onboarding", to: "#0", icon: UserPlus,
        subLinks: [
            { icon: FileText, title: "Offer / Appointment", to: "/hr/onboarding/offers" },
            { icon: UserRound, title: "New Joiner Details", to: "/hr/onboarding/joiners" },
            { icon: ClipboardCheck, title: "New Joinee Observation", to: "/hr/onboarding/observations" },
            { icon: Users, title: "Shadow Mentor", to: "/hr/onboarding/shadow-mentor" },
            { icon: ListChecks, title: "Checklist", to: "/hr/onboarding-checklist" },
        ],
    },
    {
        id: 5, title: "Attendance & Leave", to: "#0", icon: CalendarCheck,
        subLinks: [
            { icon: CalendarCheck, title: "Attendance", to: "/hr/attendance" },
            { icon: CalendarOff, title: "Leave Management", to: "/hr/leave-management" },
            { icon: FileText, title: "Leave Policies", to: "/hr/leave-management/policies" },
        ],
    },
    {
        id: 6, title: "Training", to: "#0", icon: GraduationCap,
        subLinks: [
            { icon: CalendarDays, title: "Training Schedule", to: "/hr/training" },
            { icon: ClipboardList, title: "Training Records", to: "/hr/training-records" },
            { icon: Star, title: "Training Feedback", to: "/hr/training-feedback" },
        ],
    },
    {
        id: 7, title: "Performance", to: "#0", icon: Star,
        subLinks: [
            { icon: Star, title: "Performance Review", to: "/hr/performance-review" },
            { icon: BarChart3, title: "Performance Comparison", to: "/hr/performance-comparison" },
            { icon: ClipboardCheck, title: "BSC / Audit Score", to: "/hr/performance-bsc" },
            { icon: BadgeDollarSign, title: "Increment / Promotion", to: "/hr/performance-increment" },
        ],
    },
    {
        id: 8, title: "Payroll & Benefits", to: "#0", icon: Wallet,
        subLinks: [
            { icon: BadgeDollarSign, title: "Salary Statement", to: "/hr/payroll/salary-statement" },
            { icon: Receipt, title: "Payslip", to: "/hr/payroll/payslip" },
            { icon: Wallet, title: "Salary Advance / Loan", to: "/hr/payroll/salary-advance" },
            { icon: Landmark, title: "CTC", to: "/hr/payroll/ctc" },
            { icon: Users, title: "Referral Bonus", to: "/hr/payroll/referral-bonus" },
            { icon: HeartPulse, title: "Employee Child Concession", to: "/hr/payroll/child-concession" },
            { icon: Receipt, title: "Claim Compensation", to: "/hr/payroll/claim-compensation" },
        ],
    },
    { id: 9, title: "Disciplinary Action", to: "/hr/disciplinary", icon: ShieldAlert },
    { id: 10, title: "Exit Formalities", to: "/hr/exit", icon: DoorOpen },
    { id: 11, title: "Reports", to: "/hr/reports", icon: BarChart3 },
    {
        id: 12, title: "Notifications / Announcements", to: "#0", icon: BellDot,
        subLinks: [
            { icon: BellDot, title: "Notifications", to: "/hr/notifications" },
            { icon: Rss, title: "Announcements", to: "/hr/announcements" },
        ],
    },
];

export const accountHeadSidebarLinks = [
    {
        id: 1,
        title: "Dashboard",
        to: "/account-head/dashboard",
        icon: LayoutDashboard,
    },
    {
        id: 2,
        title: "Fees Management",
        to: "/account-head/fees-management",
        icon: BadgeDollarSign,
    },
    {
        id: 3,
        title: "Collections",
        to: "/account-head/collections",
        icon: BadgeDollarSign,
    },
    {
        id: 4,
        title: "Wallet Management",
        to: "/account-head/wallet-management",
        icon: Wallet,
    },
    {
        id: 5,
        title: "Transport Finance",
        to: "/account-head/transport-finance",
        icon: Bus,
    },
    {
        id: 6,
        title: "Accounting",
        to: "#0",
        icon: BookCopy,
        subLinks: [
            { icon: BookOpen, title: "Day Book", to: "/account-head/accounting/day-book" },
            { icon: Monitor, title: "Online Book", to: "/account-head/accounting/online-book" },
            { icon: BookCopy, title: "General Ledger", to: "/account-head/accounting/general-ledger" },
            { icon: Wallet, title: "Cash Book", to: "/account-head/accounting/cash-book" },
            { icon: Landmark, title: "Bank Book", to: "/account-head/accounting/bank-book" },
            { icon: BookMarked, title: "Chart of Accounts", to: "/account-head/accounting/chart-of-accounts" },
            { icon: Receipt, title: "Journal Vouchers", to: "/account-head/accounting/journal-vouchers" },
            { icon: ArrowRightLeft, title: "Bank Reconciliation", to: "/account-head/accounting/bank-reconciliation" },
            { icon: FileText, title: "Financial Statements", to: "/account-head/accounting/financial-statements" },
        ],
    },
    {
        id: 7,
        title: "Approvals",
        to: "/account-head/approvals",
        icon: ClipboardCheck,
    },
    {
        id: 8,
        title: "Reports & Analytics",
        to: "/account-head/reports-analytics",
        icon: BarChart3,
    },
    {
        id: 9,
        title: "Task Management",
        to: "/account-head/task-management/my-tasks",
        icon: ClipboardList,
    },
    {
        id: 10,
        title: "Settings",
        to: "/account-head/settings",
        icon: Settings,
    },
    {
        id: 11,
        title: "Payment Vouchers",
        to: "/account-head/payment-vouchers",
        icon: Receipt,
    },
    {
        id: 15,
        title: "Book Fee",
        to: "/account-head/book-fee",
        icon: BookOpen,
    },
    {
        id: 12,
        title: "Annual Budget",
        to: "/account-head/annual-budget",
        icon: Wallet,
    },
    {
        id: 13,
        title: "MFP Report",
        to: "/account-head/mfp",
        icon: FileText,
    },
];

export const driverSidebarLinks = [
    {
        id: 1,
        title: "Vehicle Management",
        to: "#0",
        icon: Bus,
        subLinks: [
            { icon: Car, title: "Vehicle Details", to: "/driver/vehicle-management/vehicle-details" },
            { icon: FileText, title: "Vehicle Documents", to: "/driver/vehicle-management/vehicle-documents" },
            { icon: HeartPulse, title: "Vehicle Health Status", to: "/driver/vehicle-management/vehicle-health-status" },
        ],
    },
    {
        id: 2,
        title: "Attendance Management",
        to: "#0",
        icon: ClipboardCheck,
        subLinks: [
            { icon: ClipboardCheck, title: "Student Attendance", to: "/driver/attendance-management/student-attendance" },
            { icon: History, title: "Attendance History", to: "/driver/attendance-management/attendance-history" },
        ],
    },
];

export const directorSidebarLinks = [
    {
        id: 1,
        title: "Task Management",
        to: "#0",
        icon: ClipboardList,
        subLinks: [
            { icon: UserPlus, title: "Assign Tasks", to: "/director/task-management/assign-tasks" },
            { icon: ListChecks, title: "My Tasks", to: "/director/task-management/my-tasks" },
        ],
    },
    {
        id: 2,
        title: "Star Ratings",
        to: "#0",
        icon: Star,
        subLinks: [
            { icon: Star, title: "Star of the Month", to: "/director/star-ratings/star-of-month" },
            { icon: Trophy, title: "Star of the Year", to: "/director/star-ratings/star-of-year" },
        ],
    },
    {
        id: 3,
        title: "Timetable Approvals",
        to: "#0",
        icon: CalendarCheck,
        subLinks: [
            { icon: CalendarCheck, title: "Exam Timetable", to: "/director/examination-approvals" },
        ],
    },
    {
        id: 5,
        title: "User Database",
        to: "#0",
        icon: Users,
        subLinks: [
            { icon: UserRound, title: "Student Database", to: "/director/user-management/student-database" },
            { icon: UserRoundCog, title: "Employee Database", to: "/director/user-management/employee-database" },
        ],
    },
    {
        id: 6,
        title: "Activities",
        to: "#0",
        icon: Trophy,
        subLinks: [
            { icon: Palette, title: "Cultural", to: "/director/activities/cultural-list" },
            { icon: Dumbbell, title: "Sports", to: "/director/activities/sports-list" },
            { icon: Trophy, title: "Chess Result", to: "/director/activities/chess-result" },
            { icon: Award, title: "Competitions", to: "/director/activities/competitions-list" },
        ],
    },
    {
        id: 7,
        title: "Lesson Plan Approval",
        to: "/director/lesson-plan-approval",
        icon: NotebookPen,
    },
    {
        id: 8,
        title: "Mark Entry Approval",
        to: "/director/mark-entry-approval",
        icon: ClipboardPen,
    },
    {
        id: 9,
        title: "Home Fun",
        to: "#0",
        icon: BookOpen,
        subLinks: [
            { icon: BookOpenCheck, title: "Student Home Fun", to: "/director/lms/student-lms" },
            { icon: BookOpenCheck, title: "Teacher Home Fun", to: "/director/lms/teacher-lms" },
        ],
    },
    {
        id: 10,
        title: "Request Approvals",
        to: "/director/request-approvals",
        icon: ClipboardList,
    },
    {
        id: 11,
        title: "Leave Request",
        to: "#0",
        icon: FileX,
        subLinks: [
            { icon: FileText, title: "My Leave Requests", to: "/director/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/director/leave-request/received" },
        ],
    },
    {
        id: 12,
        title: "My Attendance",
        to: "/director/attendance/my-attendance",
        icon: CalendarCheck,
    },
    {
        id: 13,
        title: "Announcement",
        to: "/director/broadcast",
        icon: Rss,
    },
    {
        id: 14,
        title: "Communication",
        to: "/director/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 15,
        title: "Calendar",
        to: "/director/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 16,
        title: "Notifications",
        to: "/director/notifications",
        icon: BellDot,
    },
    {
        id: 17,
        title: "Escalation Management",
        to: "/director/escalation-management",
        icon: ShieldAlert,
    },
];

export const principalSidebarLinks = [
    {
        id: 1,
        title: "Task Management",
        to: "#0",
        icon: ClipboardList,
        subLinks: [
            { icon: UserPlus, title: "Assign Tasks", to: "/principal/task-management/assign-tasks" },
            { icon: ListChecks, title: "My Tasks", to: "/principal/task-management/my-tasks" },
        ],
    },
    {
        id: 2,
        title: "Star Ratings",
        to: "#0",
        icon: Star,
        subLinks: [
            { icon: Star, title: "Star of the Month", to: "/principal/star-ratings/star-of-month" },
            { icon: Trophy, title: "Star of the Year", to: "/principal/star-ratings/star-of-year" },
        ],
    },
    {
        id: 3,
        title: "Examination Timetable",
        to: "/principal/examination-timetable",
        icon: CalendarCheck,
    },
    {
        id: 4,
        title: "Class Timetable",
        to: "/principal/class-timetable",
        icon: CalendarDays,
    },
    {
        id: 5,
        title: "User Database",
        to: "#0",
        icon: Users,
        subLinks: [
            { icon: UserRound, title: "Student Database", to: "/principal/user-management/student-database" },
            { icon: UserRoundCog, title: "Employee Database", to: "/principal/user-management/employee-database" },
        ],
    },
    {
        id: 6,
        title: "Teacher Allocation",
        to: "/principal/academic/teacher-allocation",
        icon: UserRoundCog,
    },
    {
        id: 7,
        title: "Student Allocation",
        to: "/principal/student-allocation-approval",
        icon: UserPlus,
    },
    {
        id: 16,
        title: "Extended Class",
        to: "/principal/class/extra-class",
        icon: UserPlus,
    },
    {
        id: 8,
        title: "Home Fun",
        to: "#0",
        icon: BookOpen,
        subLinks: [
            { icon: BookOpenCheck, title: "Student Home Fun", to: "/principal/lms/student-lms" },
            { icon: BookOpenCheck, title: "Teacher Home Fun", to: "/principal/lms/teacher-lms" },
        ],
    },
    {
        id: 9,
        title: "Leave Request",
        to: "#0",
        icon: FileX,
        subLinks: [
            { icon: FileText, title: "My Leave Requests", to: "/principal/leave-request/my-requests" },
            { icon: ListChecks, title: "Received Leave Requests", to: "/principal/leave-request/received" },
        ],
    },
    {
        id: 10,
        title: "My Attendance",
        to: "/principal/attendance/my-attendance",
        icon: CalendarCheck,
    },
    {
        id: 11,
        title: "Announcement",
        to: "/principal/announcement",
        icon: Rss,
    },
    {
        id: 12,
        title: "Communication",
        to: "/principal/communication/inbox",
        icon: MessageCircle,
    },
    {
        id: 13,
        title: "Calendar",
        to: "/principal/academic-calendar",
        icon: CalendarDays,
    },
    {
        id: 14,
        title: "Notifications",
        to: "/principal/notifications",
        icon: BellDot,
    },
    {
        id: 15,
        title: "Escalation Management",
        to: "/principal/escalation-management",
        icon: ShieldAlert,
    },
];

export const roleBasedSidebarLinks = {
    SuperAdmin: superAdminSidebarLinks,
    Administrator: adminSidebarLinks,
    Student: studentSidebarLinks,
    Parent: parentSidebarLinks,
    Teacher: teacherSidebarLinks,
    Coordinator: coordinatorSidebarLinks,
    Librarian: librarianSidebarLinks,
    PRM: prmSidebarLinks,
    GateKeeper: gateKeeperSidebarLinks,
    GateKeeperManager: gateKeeperManagerSidebarLinks,
    CanteenManager: canteenManagerSidebarLinks,
    ITSupportManager: itSupportManagerSidebarLinks,
    StationeryStoreManager: stationeryStoreManagerSidebarLinks,
    HousekeepingManager: housekeepingManagerSidebarLinks,
    TransportManager: transportManagerSidebarLinks,
    JointDirector: jointDirectorSidebarLinks,
    JointDirectorAssistant: jointDirectorAssistantSidebarLinks,
    JointDirectorAudit: jointDirectorAuditSidebarLinks,
    ProcessAuditor: processAuditorSidebarLinks,
    QualityAuditor: qualityAuditorSidebarLinks,
    HR: hrSidebarLinks,
    AccountHead: accountHeadSidebarLinks,
    Driver: driverSidebarLinks,
    Director: directorSidebarLinks,
    Principal: principalSidebarLinks,
};
