import { SUBJECTS } from '../AssignedClass/assignedClassData'

export const TEACHER_NAME = 'Mr. Anil Kumar'
export const TEACHER_EMPLOYEE_ID = 'EMP-T-1042'

export const EXAM_HALL_DUTY_LIST = [
    {
        id: 'DUTY-1001',
        dutyId: 'DUTY-1001',
        teacherName: TEACHER_NAME,
        employeeId: TEACHER_EMPLOYEE_ID,
        examName: 'Mid Term Examination',
        subject: 'Mathematics',
        examDate: '15-09-2025',
        hallNumber: 'Hall 12',
        buildingName: 'Main Block',
        floorNumber: '2nd Floor',
        reportingTime: '09:30 AM',
        examStartTime: '10:30 AM',
        examEndTime: '12:30 PM',
        assignedBy: 'Principal Office',
    },
    {
        id: 'DUTY-1002',
        dutyId: 'DUTY-1002',
        teacherName: TEACHER_NAME,
        employeeId: TEACHER_EMPLOYEE_ID,
        examName: 'Mid Term Examination',
        subject: 'Physics',
        examDate: '16-09-2025',
        hallNumber: 'Hall 08',
        buildingName: 'Science Block',
        floorNumber: '1st Floor',
        reportingTime: '09:15 AM',
        examStartTime: '10:30 AM',
        examEndTime: '12:30 PM',
        assignedBy: 'Exam Coordinator',
    },
    {
        id: 'DUTY-1003',
        dutyId: 'DUTY-1003',
        teacherName: TEACHER_NAME,
        employeeId: TEACHER_EMPLOYEE_ID,
        examName: 'Unit Test — Term 1',
        subject: 'Computer Science',
        examDate: '06-08-2025',
        hallNumber: 'Hall 05',
        buildingName: 'Computer Lab Block',
        floorNumber: 'Ground Floor',
        reportingTime: '08:45 AM',
        examStartTime: '09:00 AM',
        examEndTime: '11:00 AM',
        assignedBy: 'Principal Office',
    },
    {
        id: 'DUTY-1004',
        dutyId: 'DUTY-1004',
        teacherName: TEACHER_NAME,
        employeeId: TEACHER_EMPLOYEE_ID,
        examName: 'Pre-Board Examination',
        subject: 'Mathematics',
        examDate: '12-01-2026',
        hallNumber: 'Hall 15',
        buildingName: 'Main Block',
        floorNumber: '3rd Floor',
        reportingTime: '09:00 AM',
        examStartTime: '10:30 AM',
        examEndTime: '01:30 PM',
        assignedBy: 'Vice Principal',
    },
    {
        id: 'DUTY-1005',
        dutyId: 'DUTY-1005',
        teacherName: TEACHER_NAME,
        employeeId: TEACHER_EMPLOYEE_ID,
        examName: 'Practical Examination',
        subject: 'Physics',
        examDate: '25-09-2025',
        hallNumber: 'Lab 03',
        buildingName: 'Science Block',
        floorNumber: '2nd Floor',
        reportingTime: '08:30 AM',
        examStartTime: '09:00 AM',
        examEndTime: '12:00 PM',
        assignedBy: 'Exam Coordinator',
    },
    {
        id: 'DUTY-1006',
        dutyId: 'DUTY-1006',
        teacherName: TEACHER_NAME,
        employeeId: TEACHER_EMPLOYEE_ID,
        examName: 'Mid Term Examination',
        subject: 'English',
        examDate: '17-09-2025',
        hallNumber: 'Hall 10',
        buildingName: 'Arts Block',
        floorNumber: '1st Floor',
        reportingTime: '01:30 PM',
        examStartTime: '02:30 PM',
        examEndTime: '04:30 PM',
        assignedBy: 'Principal Office',
    },
]

export { SUBJECTS }
