export const DEPARTMENTS = [
    'Academic',
    'Administration',
    'Finance',
    'HR',
    'IT Support',
    'Transport',
    'Housekeeping',
    'Canteen',
    'All Departments',
]

export const TRAINING_SESSIONS = [
    {
        id: 'TRN-2026-009',
        trainingName: 'Child Safety & POCSO Awareness',
        department: 'All Departments',
        trainer: 'Dr. Kavita Menon — External Consultant',
        date: '25-06-2026',
        attendance: '42 / 45',
        feedback: '4.6 / 5 — Highly relevant content',
    },
    {
        id: 'TRN-2026-008',
        trainingName: 'Classroom Management Techniques',
        department: 'Academic',
        trainer: 'Prof. Ramesh Iyer — Senior Faculty',
        date: '18-06-2026',
        attendance: '28 / 30',
        feedback: '4.3 / 5 — Practical examples appreciated',
    },
    {
        id: 'TRN-2026-007',
        trainingName: 'GST Compliance & TDS Filing',
        department: 'Finance',
        trainer: 'CA Neha Gupta',
        date: '12-06-2026',
        attendance: '6 / 6',
        feedback: '4.8 / 5 — Clear walkthrough of updates',
    },
    {
        id: 'TRN-2026-006',
        trainingName: 'First Aid & Emergency Response',
        department: 'Transport',
        trainer: 'Red Cross Certified Trainer',
        date: '05-06-2026',
        attendance: '14 / 16',
        feedback: '4.5 / 5 — Hands-on drills were useful',
    },
    {
        id: 'TRN-2026-005',
        trainingName: 'ERP System — HR Module',
        department: 'HR',
        trainer: 'IT Support Team',
        date: '28-05-2026',
        attendance: '4 / 4',
        feedback: '4.2 / 5 — Needs follow-up session',
    },
    {
        id: 'TRN-2026-004',
        trainingName: 'Food Hygiene & FSSAI Standards',
        department: 'Canteen',
        trainer: 'FSSAI Certified Auditor',
        date: '20-05-2026',
        attendance: '8 / 8',
        feedback: '4.7 / 5 — Updated checklist provided',
    },
]
