export const EXAM_TYPES = [
    'Monthly Progress Tracker 1',
    'Monthly Progress Tracker 2',
    'Monthly Progress Tracker 3',
    'Monthly Progress Tracker 4',
    'Monthly Progress Tracker 5',
    'Monthly Progress Tracker 6',
    'Split Test 1',
    'Split Test 2',
    'Split Test 3',
    'Split Test 4',
    'Term 1 Progress Tracker',
    'Term 2 Progress Tracker',
    'Half Portion 1',
    'Half Portion 2',
    'Half Portion 3',
    'Full Portion',
    'Pre Board',
    'Revision Test 1',
    'Revision Test 2',
    'Revision Test 3',
    'Revision Test 4',
    'Revision Test 5',
    'Revision Test 6',
    'CA / RCT',
]
