const BASE_ATTENDANCE = [
    { date: '02-06-2025', day: 'Monday', checkIn: '08:30 AM', checkOut: '05:00 PM', status: 'Present', remarks: 'Audit planning session' },
    { date: '03-06-2025', day: 'Tuesday', checkIn: '08:45 AM', checkOut: '05:15 PM', status: 'Present', remarks: 'HR site visit — Finance' },
    { date: '04-06-2025', day: 'Wednesday', checkIn: '—', checkOut: '—', status: 'Leave', remarks: 'Training leave' },
    { date: '05-06-2025', day: 'Thursday', checkIn: '09:00 AM', checkOut: '05:30 PM', status: 'Present', remarks: 'Findings review meeting' },
    { date: '06-06-2025', day: 'Friday', checkIn: '08:30 AM', checkOut: '01:30 PM', status: 'Half Day', remarks: 'Report submission' },
    { date: '09-06-2025', day: 'Monday', checkIn: '08:35 AM', checkOut: '05:05 PM', status: 'Present', remarks: 'Process audit walkthrough' },
    { date: '10-06-2025', day: 'Tuesday', checkIn: '08:30 AM', checkOut: '05:00 PM', status: 'Present', remarks: 'On time' },
]

export const attendanceBadgeColor = {
    Present: 'bg-[#4CAF5033] text-[#4CAF50]',
    Absent: 'bg-[#FF000033] text-[#FF0000]',
    Leave: 'bg-[#FF980033] text-[#FF9800]',
    'Half Day': 'bg-[#2196F333] text-[#2196F3]',
}

export const taskStatusBadgeColor = {
    Pending: 'bg-[#66708533] text-[#667085]',
    Completed: 'bg-[#4CAF5033] text-[#4CAF50]',
    'In Progress': 'bg-[#FF980033] text-[#FF9800]',
    'In Complete': 'bg-[#FF000033] text-[#FF0000]',
}

export const EMPLOYEE_PROFILES = {
    'hr-manager': {
        roleTitle: 'HR Manager',
        profileLabel: 'HR Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'HRM-1001',
            userId: 'USR-500001',
            firstName: 'Deepak',
            middleName: 'R.',
            lastName: 'Joseph',
            gender: 'Male',
            dateOfBirth: '12-03-1984',
            bloodGroup: 'B+',
            height: '178 cm',
            weight: '74 kg',
            medicalHistory: 'None.',
            address: {
                address: '45, Audit Lane, Nungambakkam',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600034',
            },
            contact: {
                mobileNumber: '+91 98765 70101',
                alternativeNumber: '+91 91234 70101',
                email: 'd.joseph@school.edu',
            },
            professionalInfo: {
                qualification: 'MBA in Human Resources, SHRM-CP',
                designation: 'HR Manager — Audit Team',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '14 Years',
                previousOrganization: 'ComplianceFirst HR Consulting',
                joiningDate: '2015-07-01',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹72,000 / month',
                workShift: 'Standard (8:30 AM – 5:00 PM)',
                assignedCampus: 'Audit Office — Main Campus',
                managedStaff: 'HR Executive (1), HR audit associates (2)',
                reportingTo: 'Joint Director — Audit',
            },
            account: { username: 'd.joseph', password: 'HRM@2025' },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'MBA & SHRM-CP Certificates',
                experienceCertificate: 'Experience Letter — ComplianceFirst',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'AUD-T-001', title: 'HR policy compliance review — Q2', assignedDate: '10-06-2026', dueDate: '18-06-2026', status: 'In Progress' },
            { taskId: 'AUD-T-007', title: 'Cross-audit team findings review meeting', assignedDate: '10-06-2026', dueDate: '18-06-2026', status: 'Pending' },
        ],
    },
    'hr-executive': {
        roleTitle: 'HR Executive',
        profileLabel: 'HR Executive Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'HRE-1001',
            userId: 'USR-500002',
            firstName: 'Sneha',
            middleName: 'P.',
            lastName: 'Priya',
            gender: 'Female',
            dateOfBirth: '28-08-1992',
            bloodGroup: 'O+',
            height: '163 cm',
            weight: '55 kg',
            medicalHistory: 'None.',
            address: {
                address: '18, Green Park, Adyar',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600020',
            },
            contact: {
                mobileNumber: '+91 98765 70202',
                alternativeNumber: '+91 91234 70202',
                email: 's.priya@school.edu',
            },
            professionalInfo: {
                qualification: 'M.A. in Industrial Relations',
                designation: 'HR Executive — Audit Team',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '6 Years',
                previousOrganization: 'TalentBridge Solutions',
                joiningDate: '2020-02-10',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹48,000 / month',
                workShift: 'Standard (8:30 AM – 5:00 PM)',
                assignedCampus: 'Audit Office — Main Campus',
                managedStaff: 'HR audit field support',
                reportingTo: 'HR Manager — Audit Team',
            },
            account: { username: 's.priya', password: 'HRE@2025' },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'M.A. Industrial Relations Certificate',
                experienceCertificate: 'Experience Letter — TalentBridge',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'AUD-T-004', title: 'HR documentation sampling — new hires', assignedDate: '08-06-2026', dueDate: '12-06-2026', status: 'Completed' },
            { taskId: 'AUD-T-008', title: 'Policy acknowledgment gap follow-up', assignedDate: '09-06-2026', dueDate: '14-06-2026', status: 'In Progress' },
        ],
    },
    'process-audit-manager': {
        roleTitle: 'Process Audit Manager',
        profileLabel: 'Process Audit Manager Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'PAM-1001',
            userId: 'USR-500003',
            firstName: 'Rajesh',
            middleName: 'V.',
            lastName: 'Mehta',
            gender: 'Male',
            dateOfBirth: '05-01-1980',
            bloodGroup: 'A+',
            height: '175 cm',
            weight: '78 kg',
            medicalHistory: 'None.',
            address: {
                address: '92, Process Road, T Nagar',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600017',
            },
            contact: {
                mobileNumber: '+91 98765 70303',
                alternativeNumber: '+91 91234 70303',
                email: 'r.mehta@school.edu',
            },
            professionalInfo: {
                qualification: 'CA, CIA (Certified Internal Auditor)',
                designation: 'Process Audit Manager',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '16 Years',
                previousOrganization: 'AuditPro India Pvt. Ltd.',
                joiningDate: '2013-09-15',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹85,000 / month',
                workShift: 'Standard (8:30 AM – 5:30 PM)',
                assignedCampus: 'All departments — process audit scope',
                managedStaff: 'Process Audit Executive (1), audit associates (3)',
                reportingTo: 'Joint Director — Audit',
            },
            account: { username: 'r.mehta', password: 'PAM@2025' },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'CA & CIA Certificates',
                experienceCertificate: 'Experience Letter — AuditPro',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'AUD-T-002', title: 'Process audit checklist — Finance operations', assignedDate: '09-06-2026', dueDate: '16-06-2026', status: 'Pending' },
            { taskId: 'AUD-T-006', title: 'Cross-audit findings consolidation', assignedDate: '10-06-2026', dueDate: '12-06-2026', status: 'In Progress' },
        ],
    },
    'process-audit-executive': {
        roleTitle: 'Process Audit Executive',
        profileLabel: 'Process Audit Executive Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'PAE-1001',
            userId: 'USR-500004',
            firstName: 'Arif',
            middleName: 'H.',
            lastName: 'Khan',
            gender: 'Male',
            dateOfBirth: '19-11-1990',
            bloodGroup: 'B+',
            height: '172 cm',
            weight: '68 kg',
            medicalHistory: 'None.',
            address: {
                address: '33, Audit Circle, Velachery',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600042',
            },
            contact: {
                mobileNumber: '+91 98765 70404',
                alternativeNumber: '+91 91234 70404',
                email: 'a.khan@school.edu',
            },
            professionalInfo: {
                qualification: 'B.Com., Diploma in Internal Audit',
                designation: 'Process Audit Executive',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '8 Years',
                previousOrganization: 'ProcessWise Auditors',
                joiningDate: '2018-04-02',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹52,000 / month',
                workShift: 'Standard (8:30 AM – 5:00 PM)',
                assignedCampus: 'Field audit — all process scopes',
                managedStaff: 'Process audit field support',
                reportingTo: 'Process Audit Manager',
            },
            account: { username: 'a.khan', password: 'PAE@2025' },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'B.Com. & Internal Audit Diploma',
                experienceCertificate: 'Experience Letter — ProcessWise',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'AUD-T-005', title: 'Process walkthrough — Transport maintenance logs', assignedDate: '07-06-2026', dueDate: '15-06-2026', status: 'In Complete' },
            { taskId: 'AUD-T-009', title: 'IT backup log verification — site visit', assignedDate: '06-06-2026', dueDate: '14-06-2026', status: 'In Progress' },
        ],
    },
    'quality-audit-principal': {
        roleTitle: 'Quality Audit Principal',
        profileLabel: 'Quality Audit Principal Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'QAP-1001',
            userId: 'USR-500005',
            firstName: 'Vijaya',
            middleName: 'L.',
            lastName: 'Lakshmi',
            gender: 'Female',
            dateOfBirth: '14-06-1978',
            bloodGroup: 'AB+',
            height: '165 cm',
            weight: '62 kg',
            medicalHistory: 'None.',
            address: {
                address: '7, Quality Heights, Anna Nagar',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600040',
            },
            contact: {
                mobileNumber: '+91 98765 70505',
                alternativeNumber: '+91 91234 70505',
                email: 'v.lakshmi@school.edu',
            },
            professionalInfo: {
                qualification: 'M.Ed., Ph.D. in Educational Assessment',
                designation: 'Quality Audit Principal',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '20 Years',
                previousOrganization: 'National Board for Quality Education',
                joiningDate: '2010-06-01',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹95,000 / month',
                workShift: 'Standard (8:30 AM – 5:00 PM)',
                assignedCampus: 'Academic blocks — quality audit scope',
                managedStaff: 'Quality audit analysts (2)',
                reportingTo: 'Joint Director — Audit',
            },
            account: { username: 'v.lakshmi', password: 'QAP@2025' },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'M.Ed. & Ph.D. Certificates',
                experienceCertificate: 'Experience Letter — NBQE',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'AUD-T-003', title: 'Quality audit — Academic assessment records', assignedDate: '10-06-2026', dueDate: '14-06-2026', status: 'In Progress' },
            { taskId: 'AUD-T-010', title: 'Assessment rubric compliance report', assignedDate: '08-06-2026', dueDate: '13-06-2026', status: 'Pending' },
        ],
    },
    'quality-audit-executive': {
        roleTitle: 'Quality Audit Executive',
        profileLabel: 'Quality Audit Executive Profile',
        idLabel: 'Employee ID',
        employee: {
            profileImage: null,
            employeeId: 'QAE-1001',
            userId: 'USR-500006',
            firstName: 'Nisha',
            middleName: 'K.',
            lastName: 'Verma',
            gender: 'Female',
            dateOfBirth: '03-09-1993',
            bloodGroup: 'O+',
            height: '162 cm',
            weight: '56 kg',
            medicalHistory: 'None.',
            address: {
                address: '24, Campus View, Tambaram',
                country: 'India',
                state: 'Tamil Nadu',
                city: 'Chennai',
                zipCode: '600045',
            },
            contact: {
                mobileNumber: '+91 98765 70606',
                alternativeNumber: '+91 91234 70606',
                email: 'n.verma@school.edu',
            },
            professionalInfo: {
                qualification: 'M.Sc. in Educational Measurement & Evaluation',
                designation: 'Quality Audit Executive',
                schoolName: 'Queen Mira International School',
                yearsOfExperience: '5 Years',
                previousOrganization: 'EduMetrics Research Lab',
                joiningDate: '2021-08-16',
            },
            employmentInfo: {
                employeeType: 'Full-time',
                salary: '₹46,000 / month',
                workShift: 'Standard (8:30 AM – 5:00 PM)',
                assignedCampus: 'Academic blocks — quality audit field work',
                managedStaff: 'Quality audit documentation support',
                reportingTo: 'Quality Audit Principal',
            },
            account: { username: 'n.verma', password: 'QAE@2025' },
            documents: {
                idProof: 'Aadhaar Card',
                qualificationCertificate: 'M.Sc. Educational Measurement Certificate',
                experienceCertificate: 'Experience Letter — EduMetrics',
            },
        },
        attendanceRecords: BASE_ATTENDANCE,
        recentTasks: [
            { taskId: 'AUD-T-011', title: 'Grade entry sampling — Grade 10 Mathematics', assignedDate: '09-06-2026', dueDate: '13-06-2026', status: 'In Progress' },
            { taskId: 'AUD-T-012', title: 'Moderation log verification — Term II', assignedDate: '07-06-2026', dueDate: '11-06-2026', status: 'Pending' },
        ],
    },
}

export const EMPLOYEE_ROLE_SLUGS = Object.keys(EMPLOYEE_PROFILES)
